/* eslint-disable */
'use client';

/**
 * Clover & Biscuit 🐰 — Bunny and cat, classic-cute proportions.
 *
 * AUTO-GENERATED by tools/stickers/gen_pack_jsx.py. Do not edit by hand:
 * re-run the generator instead, or the drawings drift from the sheets.
 *
 * Ten poses, one 120x120 board each, house palette and plum ink. The
 * `an-*` classes are the little motion loops; they live in globals.css and
 * switch themselves off under prefers-reduced-motion.
 */

import { Board } from './board';

/* Begging — clover-biscuit/begging */
export function CloverBiscuitBegging(props) {
  return (
    <Board {...props}>
      <g className="an-twinkle">
        <path d="M18 41.8 q0.8 2.6 4.2 4.2 q-2.6 0.8 -4.2 4.2 q-0.8 -2.6 -4.2 -4.2 q2.6 -0.8 4.2 -4.2Z" fill="#F2B880" opacity="1" />
      </g>
      <g className="an-twinkle an-d2">
        <path d="M102 50.4 q0.6 2.2 3.6 3.6 q-2.2 0.6 -3.6 3.6 q-0.6 -2.2 -3.6 -3.6 q2.2 -0.6 3.6 -3.6Z" fill="#F2B880" opacity="1" />
      </g>
      <g className="an-bob an-d2">
        <path d="M99 27.8 c2.2 2.5 3.4 4.6 0 8 c-3.4 0 -3.4 -2 0 -8Z" fill="#BFD6F5" stroke="#3D2137" strokeWidth="2.2" strokeLinejoin="round" />
      </g>
      <g className="an-plead">
        <path d="M80 90 c9 2 13 -3 11 -9" stroke="#3D2137" strokeWidth="13.6" strokeLinecap="round" fill="none" />
        <path d="M80 90 c9 2 13 -3 11 -9" stroke="#E8A854" strokeWidth="6.8" strokeLinecap="round" fill="none" />
        <ellipse cx="60" cy="86" rx="23" ry="16" fill="#E8A854" stroke="#3D2137" strokeWidth="4.2" />
        <path d="M53.2 34 L38.9 19.8 L40.8 31.6 Z" fill="#E8A854" stroke="#3D2137" strokeWidth="4.2" strokeLinejoin="round" />
        <path d="M50.8 32.8 L38.9 25.8 L42.8 31.2 Z" fill="#F0B9A6" />
        <path d="M66.8 34 L81.1 19.8 L79.2 31.6 Z" fill="#E8A854" stroke="#3D2137" strokeWidth="4.2" strokeLinejoin="round" />
        <path d="M69.2 32.8 L81.1 25.8 L77.2 31.2 Z" fill="#F0B9A6" />
        <circle cx="60" cy="50" r="20" fill="#E8A854" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="60" cy="59.2" rx="10.4" ry="7.2" fill="#F7D3A8" />
        <ellipse cx="52" cy="49.2" rx="6.5" ry="7.4" fill="#3D2137" />
        <circle cx="49.8" cy="46.7" r="2.6" fill="#FFFFFF" />
        <circle cx="54" cy="51.6" r="1.4" fill="#FFFFFF" opacity="0.9" />
        <ellipse cx="68" cy="49.2" rx="6.5" ry="7.4" fill="#3D2137" />
        <circle cx="65.8" cy="46.7" r="2.6" fill="#FFFFFF" />
        <circle cx="70" cy="51.6" r="1.4" fill="#FFFFFF" opacity="0.9" />
        <path d="M57.2 56 q1.4 -2.6 5.6 0 q1.4 3.4 2.8 3.4 q1.4 0 2.8 -3.4Z" fill="#E85D75" />
        <path d="M54.8 62 q1.3 -2.2 2.6 0 q1.3 2.2 2.6 0 q1.3 -2.2 2.6 0 q1.3 2.2 2.6 0" stroke="#3D2137" strokeWidth="3.2" fill="none" strokeLinecap="round" />
        <path d="M49.6 55 L37.2 53.6" stroke="#3D2137" strokeWidth="1.8" strokeLinecap="round" opacity=".5" />
        <path d="M49.6 57 L37.2 57.2" stroke="#3D2137" strokeWidth="1.8" strokeLinecap="round" opacity=".5" />
        <path d="M49.6 59 L37.2 60.8" stroke="#3D2137" strokeWidth="1.8" strokeLinecap="round" opacity=".5" />
        <path d="M70.4 55 L82.8 53.6" stroke="#3D2137" strokeWidth="1.8" strokeLinecap="round" opacity=".5" />
        <path d="M70.4 57 L82.8 57.2" stroke="#3D2137" strokeWidth="1.8" strokeLinecap="round" opacity=".5" />
        <path d="M70.4 59 L82.8 60.8" stroke="#3D2137" strokeWidth="1.8" strokeLinecap="round" opacity=".5" />
        <ellipse cx="45.2" cy="56" rx="6" ry="4.2" fill="#F2748C" opacity="0.75" />
        <ellipse cx="74.8" cy="56" rx="6" ry="4.2" fill="#F2748C" opacity="0.75" />
        <path d="M45 90 C48 82 52 75 56 73" stroke="#3D2137" strokeWidth="14.2" strokeLinecap="round" fill="none" />
        <path d="M45 90 C48 82 52 75 56 73" stroke="#E8A854" strokeWidth="7" strokeLinecap="round" fill="none" />
        <path d="M75 90 C72 82 68 75 64 73" stroke="#3D2137" strokeWidth="14.2" strokeLinecap="round" fill="none" />
        <path d="M75 90 C72 82 68 75 64 73" stroke="#E8A854" strokeWidth="7" strokeLinecap="round" fill="none" />
        <ellipse cx="55" cy="71" rx="6" ry="5.2" fill="#E8A854" stroke="#3D2137" strokeWidth="3.4" transform="rotate(-22 55 71)" />
        <ellipse cx="65" cy="71" rx="6" ry="5.2" fill="#E8A854" stroke="#3D2137" strokeWidth="3.4" transform="rotate(22 65 71)" />
      </g>
    </Board>
  );
}

/* Waterfall cry — clover-biscuit/waterfall-cry */
export function CloverBiscuitWaterfallCry(props) {
  return (
    <Board {...props}>
      <ellipse cx="60" cy="102" rx="25" ry="4.6" fill="#BFD6F5" opacity=".75" />
      <g className="an-sob">
        <ellipse cx="60" cy="82" rx="21" ry="15" fill="#FFF1E2" stroke="#3D2137" strokeWidth="4.2" />
        <path d="M43 80 C36 84 34 90 37 94" stroke="#3D2137" strokeWidth="14.6" strokeLinecap="round" fill="none" />
        <path d="M43 80 C36 84 34 90 37 94" stroke="#FFF1E2" strokeWidth="7.2" strokeLinecap="round" fill="none" />
        <path d="M77 80 C84 84 86 90 83 94" stroke="#3D2137" strokeWidth="14.6" strokeLinecap="round" fill="none" />
        <path d="M77 80 C84 84 86 90 83 94" stroke="#FFF1E2" strokeWidth="7.2" strokeLinecap="round" fill="none" />
        <path d="M47.5 31.6C46.5 17.9 41.5 11 32.9 16" stroke="#3D2137" strokeWidth="17.8" strokeLinecap="round" fill="none" />
        <path d="M47.5 31.6C46.5 17.9 41.5 11 32.9 16" stroke="#FFF1E2" strokeWidth="9.4" strokeLinecap="round" fill="none" />
        <path d="M47.5 30.8L45.2 19.5" stroke="#F6D9BE" strokeWidth="4" strokeLinecap="round" fill="none" />
        <path d="M72.5 31.6C73.5 17.9 78.5 11 87.1 16" stroke="#3D2137" strokeWidth="17.8" strokeLinecap="round" fill="none" />
        <path d="M72.5 31.6C73.5 17.9 78.5 11 87.1 16" stroke="#FFF1E2" strokeWidth="9.4" strokeLinecap="round" fill="none" />
        <path d="M72.5 30.8L74.8 19.5" stroke="#F6D9BE" strokeWidth="4" strokeLinecap="round" fill="none" />
        <path d="M87.1 16 c-3 -3 -7.5 -1.5 -7.5 3.5" stroke="#3D2137" strokeWidth="17.8" strokeLinecap="round" fill="none" />
        <path d="M87.1 16 c-3 -3 -7.5 -1.5 -7.5 3.5" stroke="#FFF1E2" strokeWidth="9.4" strokeLinecap="round" fill="none" />
        <circle cx="60" cy="46" r="19.5" fill="#FFF1E2" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="43.2" cy="51.9" rx="6.6" ry="6" fill="#FFF1E2" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="76.8" cy="51.9" rx="6.6" ry="6" fill="#FFF1E2" stroke="#3D2137" strokeWidth="4.2" />
        <path d="M46.6 49.9 L52.2 42.8 L57.8 49.9" stroke="#3D2137" strokeWidth="3.4" fill="none" strokeLinecap="round" strokeLinejoin="round" />
        <path d="M62.2 49.9 L67.8 42.8 L73.4 49.9" stroke="#3D2137" strokeWidth="3.4" fill="none" strokeLinecap="round" strokeLinejoin="round" />
        <path d="M57.5 50.3 q1.3 -2.4 5.1 0 q1.3 3.2 2.5 3.2 q1.3 0 2.5 -3.2Z" fill="#E85D75" />
        <ellipse cx="60" cy="60" rx="4.3" ry="5.3" fill="#7A2E44" stroke="#3D2137" strokeWidth="3" />
        <ellipse cx="43.6" cy="52.6" rx="5.8" ry="4.1" fill="#FF9FB0" opacity="0.85" />
        <ellipse cx="76.4" cy="52.6" rx="5.8" ry="4.1" fill="#FF9FB0" opacity="0.85" />
      </g>
      <g className="an-stream">
        <path d="M52.2 51.4 v38" stroke="#BFD6F5" strokeWidth="6.2" strokeLinecap="round" opacity=".95" />
      </g>
      <g className="an-stream an-d2">
        <path d="M67.8 51.4 v38" stroke="#BFD6F5" strokeWidth="6.2" strokeLinecap="round" opacity=".95" />
      </g>
      <g className="an-teardrop">
        <path d="M24 43.3 c2 2.7 3.4 4.2 3.4 5.9 c0 2 -1.6 3.4 -3.4 3.4 c-2 0 -3.4 -1.7 -3.4 -3.4Z" fill="#BFD6F5" stroke="#3D2137" strokeWidth="2.6" strokeLinejoin="round" />
      </g>
      <g className="an-teardrop an-d3">
        <path d="M98 49.9 c1.8 2.3 3 3.7 3 5.2 c0 1.8 -1.4 3 -3 3 c-1.8 0 -3 -1.5 -3 -3Z" fill="#BFD6F5" stroke="#3D2137" strokeWidth="2.6" strokeLinejoin="round" />
      </g>
    </Board>
  );
}

/* Big hug — clover-biscuit/big-hug */
export function CloverBiscuitBigHug(props) {
  return (
    <Board {...props}>
      <g className="an-squeeze">
        <path d="M96 90 c9 1 14 -5 12 -12 c-1.4 -5 -7.5 -5.6 -9 -1" stroke="#3D2137" strokeWidth="13.6" strokeLinecap="round" fill="none" />
        <path d="M96 90 c9 1 14 -5 12 -12 c-1.4 -5 -7.5 -5.6 -9 -1" stroke="#E8A854" strokeWidth="6.8" strokeLinecap="round" fill="none" />
        <path d="M68 86 C56 80 42 79 28 82" stroke="#3D2137" strokeWidth="14.6" strokeLinecap="round" fill="none" />
        <path d="M68 86 C56 80 42 79 28 82" stroke="#E8A854" strokeWidth="7.2" strokeLinecap="round" fill="none" />
        <ellipse cx="24" cy="81" rx="7" ry="6" fill="#E8A854" stroke="#3D2137" strokeWidth="3.4" transform="rotate(18 24 81)" />
        <path d="M54 92 C66 88 82 87 96 89" stroke="#3D2137" strokeWidth="14.6" strokeLinecap="round" fill="none" />
        <path d="M54 92 C66 88 82 87 96 89" stroke="#FFF1E2" strokeWidth="7.2" strokeLinecap="round" fill="none" />
        <ellipse cx="100" cy="88" rx="7" ry="6" fill="#FFF1E2" stroke="#3D2137" strokeWidth="3.4" transform="rotate(-18 100 88)" />
        <ellipse cx="43" cy="91" rx="20" ry="14" fill="#FFF1E2" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="80" cy="92" rx="20" ry="14" fill="#E8A854" stroke="#3D2137" strokeWidth="4.2" />
        <path d="M30.5 40.7C29.6 28.1 24.9 18.3 20 20.8" stroke="#3D2137" strokeWidth="17.8" strokeLinecap="round" fill="none" />
        <path d="M30.5 40.7C29.6 28.1 24.9 18.3 20 20.8" stroke="#FFF1E2" strokeWidth="9.4" strokeLinecap="round" fill="none" />
        <path d="M30.5 40L28.3 29.5" stroke="#F6D9BE" strokeWidth="4" strokeLinecap="round" fill="none" />
        <path d="M53.5 40.7C54.4 28.1 59.1 18.3 64 20.8" stroke="#3D2137" strokeWidth="17.8" strokeLinecap="round" fill="none" />
        <path d="M53.5 40.7C54.4 28.1 59.1 18.3 64 20.8" stroke="#FFF1E2" strokeWidth="9.4" strokeLinecap="round" fill="none" />
        <path d="M53.5 40L55.7 29.5" stroke="#F6D9BE" strokeWidth="4" strokeLinecap="round" fill="none" />
        <path d="M64 20.8 c-3 -3 -7.5 -1.5 -7.5 3.5" stroke="#3D2137" strokeWidth="17.8" strokeLinecap="round" fill="none" />
        <path d="M64 20.8 c-3 -3 -7.5 -1.5 -7.5 3.5" stroke="#FFF1E2" strokeWidth="9.4" strokeLinecap="round" fill="none" />
        <circle cx="42" cy="54" r="18" fill="#FFF1E2" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="26.5" cy="59.4" rx="6.1" ry="5.6" fill="#FFF1E2" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="57.5" cy="59.4" rx="6.1" ry="5.6" fill="#FFF1E2" stroke="#3D2137" strokeWidth="4.2" />
        <path d="M30.1 54.4 q4.7 -7 9.4 0" stroke="#3D2137" strokeWidth="3.4" fill="none" strokeLinecap="round" />
        <path d="M44.5 54.4 q4.7 -7 9.4 0" stroke="#3D2137" strokeWidth="3.4" fill="none" strokeLinecap="round" />
        <path d="M39.7 58 q1.2 -2.4 4.7 0 q1.2 3.2 2.3 3.2 q1.2 0 2.3 -3.2Z" fill="#E85D75" />
        <path d="M42 63.2v1.8M42 64.8q-2.8 2.6 -4.4 0M42 64.8q2.8 2.6 4.4 0" stroke="#3D2137" strokeWidth="2.8" fill="none" strokeLinecap="round" />
        <ellipse cx="26.9" cy="60.1" rx="5.4" ry="3.8" fill="#FF9FB0" opacity="0.85" />
        <ellipse cx="57.1" cy="60.1" rx="5.4" ry="3.8" fill="#FF9FB0" opacity="0.85" />
        <path d="M73.5 41.8 L62.9 26.1 L61.8 39.5 Z" fill="#E8A854" stroke="#3D2137" strokeWidth="4.2" strokeLinejoin="round" />
        <path d="M71.3 40.7 L62.9 31.8 L63.7 39.1 Z" fill="#F0B9A6" />
        <path d="M86.5 41.8 L97.1 26.1 L98.2 39.5 Z" fill="#E8A854" stroke="#3D2137" strokeWidth="4.2" strokeLinejoin="round" />
        <path d="M88.7 40.7 L97.1 31.8 L96.3 39.1 Z" fill="#F0B9A6" />
        <circle cx="80" cy="57" r="19" fill="#E8A854" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="80" cy="65.7" rx="9.9" ry="6.8" fill="#F7D3A8" />
        <path d="M67.5 56.2 q4.9 -7.4 9.9 0" stroke="#3D2137" strokeWidth="3.4" fill="none" strokeLinecap="round" />
        <path d="M82.7 56.2 q4.9 -7.4 9.9 0" stroke="#3D2137" strokeWidth="3.4" fill="none" strokeLinecap="round" />
        <path d="M77.3 62.7 q1.3 -2.6 5.3 0 q1.3 3.4 2.7 3.4 q1.3 0 2.7 -3.4Z" fill="#E85D75" />
        <path d="M80 66.5q-3.0 3.0 -5.0 0M80 66.5q3.0 3.0 5.0 0" stroke="#3D2137" strokeWidth="2.8" fill="none" strokeLinecap="round" />
        <path d="M81.9 66.9 l2.6 0 l-1.3 3.4 Z" fill="#FFFFFF" stroke="#3D2137" strokeWidth="1.2" strokeLinejoin="round" />
        <path d="M70.1 61.7 L58.3 60.3" stroke="#3D2137" strokeWidth="1.8" strokeLinecap="round" opacity=".5" />
        <path d="M70.1 63.7 L58.3 63.9" stroke="#3D2137" strokeWidth="1.8" strokeLinecap="round" opacity=".5" />
        <path d="M70.1 65.7 L58.3 67.5" stroke="#3D2137" strokeWidth="1.8" strokeLinecap="round" opacity=".5" />
        <path d="M89.9 61.7 L101.7 60.3" stroke="#3D2137" strokeWidth="1.8" strokeLinecap="round" opacity=".5" />
        <path d="M89.9 63.7 L101.7 63.9" stroke="#3D2137" strokeWidth="1.8" strokeLinecap="round" opacity=".5" />
        <path d="M89.9 65.7 L101.7 67.5" stroke="#3D2137" strokeWidth="1.8" strokeLinecap="round" opacity=".5" />
        <ellipse cx="65.9" cy="62.7" rx="5.7" ry="4" fill="#F2748C" opacity="0.75" />
        <ellipse cx="94.1" cy="62.7" rx="5.7" ry="4" fill="#F2748C" opacity="0.75" />
        <path d="M68 80 C60 76 50 76 44 79" stroke="#3D2137" strokeWidth="14.2" strokeLinecap="round" fill="none" />
        <path d="M68 80 C60 76 50 76 44 79" stroke="#FFF1E2" strokeWidth="7" strokeLinecap="round" fill="none" />
      </g>
      <g className="an-bob">
        <path d="M60 17.8 C57 15 54.6 12.8 54.6 11 C54.6 8.8 57.4 7.8 58.7 9.5 C59.3 10.2 59.7 10.6 60 10.9 C60.3 10.6 60.7 10.2 61.3 9.5 C62.6 7.8 65.4 8.8 65.4 11 C65.4 12.8 63 15 60 17.8 Z" fill="#E85D75" stroke="#3D2137" strokeWidth="3.2" strokeLinejoin="round" />
      </g>
      <g className="an-bob an-d2">
        <path d="M100 25.4 C97.8 23.5 96.2 21.9 96.2 20.5 C96.2 19 98.1 18.2 99.1 19.5 C99.5 20 99.8 20.3 100 20.5 C100.2 20.3 100.5 20 100.9 19.5 C101.9 18.2 103.8 19 103.8 20.5 C103.8 21.9 102.2 23.5 100 25.4 Z" fill="#E85D75" stroke="#3D2137" strokeWidth="3.2" strokeLinejoin="round" />
      </g>
    </Board>
  );
}

/* Flowers, shy — clover-biscuit/flowers-shy */
export function CloverBiscuitFlowersShy(props) {
  return (
    <Board {...props}>
      <g className="an-shy">
        <path d="M28 90 c9 1 14 -5 12 -12 c-1.4 -5 -7.5 -5.6 -9 -1" stroke="#3D2137" strokeWidth="13.6" strokeLinecap="round" fill="none" />
        <path d="M28 90 c9 1 14 -5 12 -12 c-1.4 -5 -7.5 -5.6 -9 -1" stroke="#E8A854" strokeWidth="6.8" strokeLinecap="round" fill="none" />
        <ellipse cx="48" cy="86" rx="21" ry="15" fill="#E8A854" stroke="#3D2137" strokeWidth="4.2" />
        <path d="M39.4 34.4 L28.6 18.1 L27.3 32.1 Z" fill="#E8A854" stroke="#3D2137" strokeWidth="4.2" strokeLinejoin="round" />
        <path d="M37 33.2 L28.6 23.9 L29.2 31.7 Z" fill="#F0B9A6" />
        <path d="M52.6 34.4 L63.4 18.1 L64.7 32.1 Z" fill="#E8A854" stroke="#3D2137" strokeWidth="4.2" strokeLinejoin="round" />
        <path d="M55 33.2 L63.4 23.9 L62.8 31.7 Z" fill="#F0B9A6" />
        <circle cx="46" cy="50" r="19.5" fill="#E8A854" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="46" cy="59" rx="10.1" ry="7" fill="#F7D3A8" />
        <path d="M33.1 49.2 q5.1 -7.6 10.1 0" stroke="#3D2137" strokeWidth="3.4" fill="none" strokeLinecap="round" />
        <path d="M48.7 49.2 q5.1 -7.6 10.1 0" stroke="#3D2137" strokeWidth="3.4" fill="none" strokeLinecap="round" />
        <path d="M43.3 55.9 q1.4 -2.6 5.5 0 q1.4 3.4 2.7 3.4 q1.4 0 2.7 -3.4Z" fill="#E85D75" />
        <path d="M46 59.8q-3.0 3.0 -5.0 0M46 59.8q3.0 3.0 5.0 0" stroke="#3D2137" strokeWidth="2.8" fill="none" strokeLinecap="round" />
        <path d="M48 60.1 l2.6 0 l-1.3 3.4 Z" fill="#FFFFFF" stroke="#3D2137" strokeWidth="1.2" strokeLinejoin="round" />
        <path d="M35.9 54.9 L23.8 53.4" stroke="#3D2137" strokeWidth="1.8" strokeLinecap="round" opacity=".5" />
        <path d="M35.9 56.9 L23.8 57" stroke="#3D2137" strokeWidth="1.8" strokeLinecap="round" opacity=".5" />
        <path d="M35.9 58.8 L23.8 60.6" stroke="#3D2137" strokeWidth="1.8" strokeLinecap="round" opacity=".5" />
        <path d="M56.1 54.9 L68.2 53.4" stroke="#3D2137" strokeWidth="1.8" strokeLinecap="round" opacity=".5" />
        <path d="M56.1 56.9 L68.2 57" stroke="#3D2137" strokeWidth="1.8" strokeLinecap="round" opacity=".5" />
        <path d="M56.1 58.8 L68.2 60.6" stroke="#3D2137" strokeWidth="1.8" strokeLinecap="round" opacity=".5" />
        <ellipse cx="31.6" cy="55.9" rx="5.8" ry="4.1" fill="#F2748C" opacity="0.75" />
        <ellipse cx="60.4" cy="55.9" rx="5.8" ry="4.1" fill="#F2748C" opacity="0.75" />
        <ellipse cx="31.6" cy="55.9" rx="7" ry="5" fill="#F2748C" opacity="0.9" />
        <ellipse cx="60.4" cy="55.9" rx="7" ry="5" fill="#F2748C" opacity="0.9" />
        <path d="M64 84 C74 80 80 78 85 74" stroke="#3D2137" strokeWidth="14.6" strokeLinecap="round" fill="none" />
        <path d="M64 84 C74 80 80 78 85 74" stroke="#E8A854" strokeWidth="7.2" strokeLinecap="round" fill="none" />
        <ellipse cx="86" cy="76" rx="6.4" ry="5.6" fill="#E8A854" stroke="#3D2137" strokeWidth="3.4" transform="rotate(-10 86 76)" />
      </g>
      <g className="an-sway-s">
        <path d="M86 72 Q82.2 63.2 75 56" stroke="#6FA96E" strokeWidth="3.6" strokeLinecap="round" fill="none" />
        <path d="M86 72 Q86.3 57.8 87 47" stroke="#6FA96E" strokeWidth="3.6" strokeLinecap="round" fill="none" />
        <path d="M86 72 Q90.2 64.4 98 58" stroke="#6FA96E" strokeWidth="3.6" strokeLinecap="round" fill="none" />
        <path d="M83 62 l-6 3 M89 66 l6 4" stroke="#6FA96E" strokeWidth="3.2" strokeLinecap="round" fill="none" />
        <circle cx="75" cy="50.9" r="3.6" fill="#FFF3E9" stroke="#3D2137" strokeWidth="2.4" />
        <circle cx="79.8" cy="54.4" r="3.6" fill="#FFF3E9" stroke="#3D2137" strokeWidth="2.4" />
        <circle cx="78" cy="60.1" r="3.6" fill="#FFF3E9" stroke="#3D2137" strokeWidth="2.4" />
        <circle cx="72" cy="60.1" r="3.6" fill="#FFF3E9" stroke="#3D2137" strokeWidth="2.4" />
        <circle cx="70.2" cy="54.4" r="3.6" fill="#FFF3E9" stroke="#3D2137" strokeWidth="2.4" />
        <circle cx="75" cy="56" r="2.7" fill="#F2B880" stroke="#3D2137" strokeWidth="2.4" />
        <circle cx="87" cy="41.6" r="3.8" fill="#FFF3E9" stroke="#3D2137" strokeWidth="2.4" />
        <circle cx="92.1" cy="45.3" r="3.8" fill="#FFF3E9" stroke="#3D2137" strokeWidth="2.4" />
        <circle cx="90.2" cy="51.4" r="3.8" fill="#FFF3E9" stroke="#3D2137" strokeWidth="2.4" />
        <circle cx="83.8" cy="51.4" r="3.8" fill="#FFF3E9" stroke="#3D2137" strokeWidth="2.4" />
        <circle cx="81.9" cy="45.3" r="3.8" fill="#FFF3E9" stroke="#3D2137" strokeWidth="2.4" />
        <circle cx="87" cy="47" r="2.9" fill="#F2B880" stroke="#3D2137" strokeWidth="2.4" />
        <circle cx="98" cy="53.2" r="3.4" fill="#FFF3E9" stroke="#3D2137" strokeWidth="2.4" />
        <circle cx="102.5" cy="56.5" r="3.4" fill="#FFF3E9" stroke="#3D2137" strokeWidth="2.4" />
        <circle cx="100.8" cy="61.8" r="3.4" fill="#FFF3E9" stroke="#3D2137" strokeWidth="2.4" />
        <circle cx="95.2" cy="61.8" r="3.4" fill="#FFF3E9" stroke="#3D2137" strokeWidth="2.4" />
        <circle cx="93.5" cy="56.5" r="3.4" fill="#FFF3E9" stroke="#3D2137" strokeWidth="2.4" />
        <circle cx="98" cy="58" r="2.6" fill="#F2B880" stroke="#3D2137" strokeWidth="2.4" />
      </g>
      <g className="an-twinkle">
        <path d="M18 28 q0.7 2.5 4 4 q-2.5 0.7 -4 4 q-0.7 -2.5 -4 -4 q2.5 -0.7 4 -4Z" fill="#F2B880" opacity="1" />
      </g>
    </Board>
  );
}

/* Pouty — clover-biscuit/pouty */
export function CloverBiscuitPouty(props) {
  return (
    <Board {...props}>
      <g className="an-steam">
        <path d="M94 24c6-4 3-10-2-12s-6-7-1-10" stroke="#D5CDE6" strokeWidth="5.4" strokeLinecap="round" fill="none" />
      </g>
      <g className="an-steam an-d2">
        <path d="M106 38c5-4 2-9-2-11" stroke="#D5CDE6" strokeWidth="4.6" strokeLinecap="round" fill="none" />
      </g>
      <g className="an-huff">
        <g transform="rotate(-6 54 60)">
          <path d="M82 100 c11 -1 16 -7 14 -14" stroke="#3D2137" strokeWidth="20.6" strokeLinecap="round" fill="none" />
          <path d="M82 100 c11 -1 16 -7 14 -14" stroke="#E8A854" strokeWidth="13.8" strokeLinecap="round" fill="none" />
          <path d="M90 88 l4 -5 M95 94 l6 -1 M88 85 l3 6" stroke="#3D2137" strokeWidth="3.2" strokeLinecap="round" fill="none" />
          <ellipse cx="54" cy="88" rx="25" ry="17" fill="#E8A854" stroke="#3D2137" strokeWidth="4.2" />
          <path d="M45 29.6 L26.4 18.1 L32.3 27.1 Z" fill="#E8A854" stroke="#3D2137" strokeWidth="4.2" strokeLinejoin="round" />
          <path d="M42.6 28.4 L26.4 24.2 L34.4 26.7 Z" fill="#F0B9A6" />
          <path d="M59 29.6 L77.6 18.1 L71.7 27.1 Z" fill="#E8A854" stroke="#3D2137" strokeWidth="4.2" strokeLinejoin="round" />
          <path d="M61.4 28.4 L77.6 24.2 L69.6 26.7 Z" fill="#F0B9A6" />
          <circle cx="52" cy="46" r="20.5" fill="#E8A854" stroke="#3D2137" strokeWidth="4.2" />
          <ellipse cx="52" cy="55.4" rx="10.7" ry="7.4" fill="#F7D3A8" />
          <path d="M38.5 31 L49.1 36" stroke="#3D2137" strokeWidth="3.2" fill="none" strokeLinecap="round" />
          <path d="M54.9 36 L65.5 31" stroke="#3D2137" strokeWidth="3.2" fill="none" strokeLinecap="round" />
          <path d="M38.7 45.2 h10.1" stroke="#3D2137" strokeWidth="3.4" fill="none" strokeLinecap="round" />
          <path d="M55.1 45.2 h10.1" stroke="#3D2137" strokeWidth="3.4" fill="none" strokeLinecap="round" />
          <path d="M49.1 52.1 q1.4 -2.6 5.7 0 q1.4 3.4 2.9 3.4 q1.4 0 2.9 -3.4Z" fill="#E85D75" />
          <path d="M46.1 57.5 q3 -5.4 5.9 0 q3 5.4 5.9 0" stroke="#3D2137" strokeWidth="3.6" fill="none" strokeLinecap="round" />
          <path d="M41.3 51.2 L28.6 49.8" stroke="#3D2137" strokeWidth="1.8" strokeLinecap="round" opacity=".5" />
          <path d="M41.3 53.2 L28.6 53.4" stroke="#3D2137" strokeWidth="1.8" strokeLinecap="round" opacity=".5" />
          <path d="M41.3 55.2 L28.6 57" stroke="#3D2137" strokeWidth="1.8" strokeLinecap="round" opacity=".5" />
          <path d="M62.7 51.2 L75.4 49.8" stroke="#3D2137" strokeWidth="1.8" strokeLinecap="round" opacity=".5" />
          <path d="M62.7 53.2 L75.4 53.4" stroke="#3D2137" strokeWidth="1.8" strokeLinecap="round" opacity=".5" />
          <path d="M62.7 55.2 L75.4 57" stroke="#3D2137" strokeWidth="1.8" strokeLinecap="round" opacity=".5" />
          <ellipse cx="36.8" cy="52.1" rx="6.1" ry="4.3" fill="#F2748C" opacity="0.75" />
          <ellipse cx="67.2" cy="52.1" rx="6.1" ry="4.3" fill="#F2748C" opacity="0.75" />
          <path d="M34 78 C44 85 58 89 70 88" stroke="#3D2137" strokeWidth="13.4" strokeLinecap="round" fill="none" />
          <path d="M34 78 C44 85 58 89 70 88" stroke="#E8A854" strokeWidth="6.8" strokeLinecap="round" fill="none" />
          <path d="M74 77 C64 84 50 88 38 87" stroke="#3D2137" strokeWidth="13.4" strokeLinecap="round" fill="none" />
          <path d="M74 77 C64 84 50 88 38 87" stroke="#E8A854" strokeWidth="6.8" strokeLinecap="round" fill="none" />
          <ellipse cx="72" cy="88" rx="6.2" ry="5.4" fill="#E8A854" stroke="#3D2137" strokeWidth="3.4" transform="rotate(14 72 88)" />
          <ellipse cx="36" cy="87" rx="6.2" ry="5.4" fill="#E8A854" stroke="#3D2137" strokeWidth="3.4" transform="rotate(-14 36 87)" />
        </g>
      </g>
    </Board>
  );
}

/* Cheek kiss — clover-biscuit/cheek-kiss */
export function CloverBiscuitCheekKiss(props) {
  return (
    <Board {...props}>
      <g className="an-startle">
        <path d="M102 88 c10 -2 13 -10 10 -17 c-1.6 -3.8 -6.6 -4 -8 0" stroke="#3D2137" strokeWidth="13.6" strokeLinecap="round" fill="none" />
        <path d="M102 88 c10 -2 13 -10 10 -17 c-1.6 -3.8 -6.6 -4 -8 0" stroke="#E8A854" strokeWidth="6.8" strokeLinecap="round" fill="none" />
        <ellipse cx="86" cy="92" rx="21" ry="15" fill="#E8A854" stroke="#3D2137" strokeWidth="4.2" />
        <path d="M77.2 36 L67.3 18.4 L64.8 33.6 Z" fill="#E8A854" stroke="#3D2137" strokeWidth="4.2" strokeLinejoin="round" />
        <path d="M74.8 34.8 L67.3 24.4 L66.8 33.2 Z" fill="#F0B9A6" />
        <path d="M90.8 36 L100.7 18.4 L103.2 33.6 Z" fill="#E8A854" stroke="#3D2137" strokeWidth="4.2" strokeLinejoin="round" />
        <path d="M93.2 34.8 L100.7 24.4 L101.2 33.2 Z" fill="#F0B9A6" />
        <circle cx="84" cy="52" r="20" fill="#E8A854" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="84" cy="61.2" rx="10.4" ry="7.2" fill="#F7D3A8" />
        <ellipse cx="76" cy="51.2" rx="6.5" ry="7.4" fill="#3D2137" />
        <circle cx="73.8" cy="48.7" r="2.6" fill="#FFFFFF" />
        <circle cx="78" cy="53.6" r="1.4" fill="#FFFFFF" opacity="0.9" />
        <ellipse cx="92" cy="51.2" rx="6.5" ry="7.4" fill="#3D2137" />
        <circle cx="89.8" cy="48.7" r="2.6" fill="#FFFFFF" />
        <circle cx="94" cy="53.6" r="1.4" fill="#FFFFFF" opacity="0.9" />
        <path d="M81.2 58 q1.4 -2.6 5.6 0 q1.4 3.4 2.8 3.4 q1.4 0 2.8 -3.4Z" fill="#E85D75" />
        <ellipse cx="84" cy="64" rx="3.4" ry="4.2" fill="#7A2E44" stroke="#3D2137" strokeWidth="3" />
        <path d="M73.6 57 L61.2 55.6" stroke="#3D2137" strokeWidth="1.8" strokeLinecap="round" opacity=".5" />
        <path d="M73.6 59 L61.2 59.2" stroke="#3D2137" strokeWidth="1.8" strokeLinecap="round" opacity=".5" />
        <path d="M73.6 61 L61.2 62.8" stroke="#3D2137" strokeWidth="1.8" strokeLinecap="round" opacity=".5" />
        <path d="M94.4 57 L106.8 55.6" stroke="#3D2137" strokeWidth="1.8" strokeLinecap="round" opacity=".5" />
        <path d="M94.4 59 L106.8 59.2" stroke="#3D2137" strokeWidth="1.8" strokeLinecap="round" opacity=".5" />
        <path d="M94.4 61 L106.8 62.8" stroke="#3D2137" strokeWidth="1.8" strokeLinecap="round" opacity=".5" />
        <ellipse cx="69.2" cy="58" rx="6" ry="4.2" fill="#F2748C" opacity="0.75" />
        <ellipse cx="98.8" cy="58" rx="6" ry="4.2" fill="#F2748C" opacity="0.75" />
        <ellipse cx="68.4" cy="58.8" rx="8" ry="5.6" fill="#F2748C" opacity="0.92" />
        <ellipse cx="99.6" cy="58.8" rx="7.2" ry="5.2" fill="#F2748C" opacity="0.92" />
      </g>
      <g className="an-lean">
        <g transform="rotate(9 30 64)">
          <ellipse cx="30" cy="94" rx="19" ry="13" fill="#FFF1E2" stroke="#3D2137" strokeWidth="4.2" />
          <path d="M18.5 46.7C17.6 34.1 12.9 24.9 7.2 27.8" stroke="#3D2137" strokeWidth="17.8" strokeLinecap="round" fill="none" />
          <path d="M18.5 46.7C17.6 34.1 12.9 24.9 7.2 27.8" stroke="#FFF1E2" strokeWidth="9.4" strokeLinecap="round" fill="none" />
          <path d="M18.5 46L16.3 35.5" stroke="#F6D9BE" strokeWidth="4" strokeLinecap="round" fill="none" />
          <path d="M41.5 46.7C42.4 34.1 47.1 24.9 52.8 27.8" stroke="#3D2137" strokeWidth="17.8" strokeLinecap="round" fill="none" />
          <path d="M41.5 46.7C42.4 34.1 47.1 24.9 52.8 27.8" stroke="#FFF1E2" strokeWidth="9.4" strokeLinecap="round" fill="none" />
          <path d="M41.5 46L43.7 35.5" stroke="#F6D9BE" strokeWidth="4" strokeLinecap="round" fill="none" />
          <path d="M52.8 27.8 c-3 -3 -7.5 -1.5 -7.5 3.5" stroke="#3D2137" strokeWidth="17.8" strokeLinecap="round" fill="none" />
          <path d="M52.8 27.8 c-3 -3 -7.5 -1.5 -7.5 3.5" stroke="#FFF1E2" strokeWidth="9.4" strokeLinecap="round" fill="none" />
          <circle cx="30" cy="60" r="18" fill="#FFF1E2" stroke="#3D2137" strokeWidth="4.2" />
          <ellipse cx="14.5" cy="65.4" rx="6.1" ry="5.6" fill="#FFF1E2" stroke="#3D2137" strokeWidth="4.2" />
          <ellipse cx="45.5" cy="65.4" rx="6.1" ry="5.6" fill="#FFF1E2" stroke="#3D2137" strokeWidth="4.2" />
          <path d="M18.1 60.4 q4.7 -7 9.4 0" stroke="#3D2137" strokeWidth="3.4" fill="none" strokeLinecap="round" />
          <path d="M32.5 60.4 q4.7 -7 9.4 0" stroke="#3D2137" strokeWidth="3.4" fill="none" strokeLinecap="round" />
          <path d="M27.7 64 q1.2 -2.4 4.7 0 q1.2 3.2 2.3 3.2 q1.2 0 2.3 -3.2Z" fill="#E85D75" />
          <ellipse cx="30" cy="71.9" rx="3.1" ry="3.8" fill="#7A2E44" stroke="#3D2137" strokeWidth="3" />
          <ellipse cx="14.9" cy="66.1" rx="5.4" ry="3.8" fill="#FF9FB0" opacity="0.85" />
          <ellipse cx="45.1" cy="66.1" rx="5.4" ry="3.8" fill="#FF9FB0" opacity="0.85" />
        </g>
        <g transform="rotate(-16 65 50)">
          <ellipse cx="65" cy="50" rx="6.6" ry="5.2" fill="#FFD9E2" stroke="#3D2137" strokeWidth="3.0" />
          <path d="M60.4 50 h9.2" stroke="#3D2137" strokeWidth="2.0" strokeLinecap="round" />
        </g>
      </g>
      <g className="an-bob">
        <path d="M106 30.1 C103.4 27.7 101.5 25.8 101.5 24.3 C101.5 22.4 103.8 21.6 104.9 23 C105.4 23.7 105.7 24 106 24.2 C106.3 24 106.6 23.7 107.1 23 C108.2 21.6 110.5 22.4 110.5 24.3 C110.5 25.8 108.6 27.7 106 30.1 Z" fill="#E85D75" stroke="#3D2137" strokeWidth="3.2" strokeLinejoin="round" />
      </g>
      <g className="an-bob an-d2">
        <path d="M97 12.9 C95.2 11.2 93.7 9.9 93.7 8.8 C93.7 7.4 95.4 6.8 96.2 7.9 C96.6 8.3 96.8 8.5 97 8.7 C97.2 8.5 97.4 8.3 97.8 7.9 C98.6 6.8 100.3 7.4 100.3 8.8 C100.3 9.9 98.8 11.2 97 12.9 Z" fill="#E85D75" stroke="#3D2137" strokeWidth="3.2" strokeLinejoin="round" />
      </g>
    </Board>
  );
}

/* Head pat — clover-biscuit/head-pat */
export function CloverBiscuitHeadPat(props) {
  return (
    <Board {...props}>
      <g className="an-melt">
        <path d="M56 100 c10 -2 13 -10 10 -17 c-1.6 -3.8 -6.6 -4 -8 0" stroke="#3D2137" strokeWidth="13.6" strokeLinecap="round" fill="none" />
        <path d="M56 100 c10 -2 13 -10 10 -17 c-1.6 -3.8 -6.6 -4 -8 0" stroke="#E8A854" strokeWidth="6.8" strokeLinecap="round" fill="none" />
        <ellipse cx="38" cy="100" rx="23" ry="15" fill="#E8A854" stroke="#3D2137" strokeWidth="4.2" />
        <path d="M30.9 53.2 L19.3 35.6 L17.8 50.7 Z" fill="#E8A854" stroke="#3D2137" strokeWidth="4.2" strokeLinejoin="round" />
        <path d="M28.3 51.9 L19.3 41.9 L19.9 50.3 Z" fill="#F0B9A6" />
        <path d="M45.1 53.2 L56.7 35.6 L58.2 50.7 Z" fill="#E8A854" stroke="#3D2137" strokeWidth="4.2" strokeLinejoin="round" />
        <path d="M47.7 51.9 L56.7 41.9 L56.1 50.3 Z" fill="#F0B9A6" />
        <circle cx="38" cy="70" r="21" fill="#E8A854" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="38" cy="79.7" rx="10.9" ry="7.6" fill="#F7D3A8" />
        <path d="M24.1 69.2 q5.5 -8.2 10.9 0" stroke="#3D2137" strokeWidth="3.4" fill="none" strokeLinecap="round" />
        <path d="M40.9 69.2 q5.5 -8.2 10.9 0" stroke="#3D2137" strokeWidth="3.4" fill="none" strokeLinecap="round" />
        <path d="M35.1 76.3 q1.5 -2.6 5.9 0 q1.5 3.4 2.9 3.4 q1.5 0 2.9 -3.4Z" fill="#E85D75" />
        <path d="M38 80.5q-3.0 3.0 -5.0 0M38 80.5q3.0 3.0 5.0 0" stroke="#3D2137" strokeWidth="2.8" fill="none" strokeLinecap="round" />
        <path d="M40.1 80.9 l2.6 0 l-1.3 3.4 Z" fill="#FFFFFF" stroke="#3D2137" strokeWidth="1.2" strokeLinejoin="round" />
        <path d="M27.1 75.4 L14.1 73.9" stroke="#3D2137" strokeWidth="1.8" strokeLinecap="round" opacity=".5" />
        <path d="M27.1 77.4 L14.1 77.5" stroke="#3D2137" strokeWidth="1.8" strokeLinecap="round" opacity=".5" />
        <path d="M27.1 79.3 L14.1 81.1" stroke="#3D2137" strokeWidth="1.8" strokeLinecap="round" opacity=".5" />
        <path d="M48.9 75.4 L61.9 73.9" stroke="#3D2137" strokeWidth="1.8" strokeLinecap="round" opacity=".5" />
        <path d="M48.9 77.4 L61.9 77.5" stroke="#3D2137" strokeWidth="1.8" strokeLinecap="round" opacity=".5" />
        <path d="M48.9 79.3 L61.9 81.1" stroke="#3D2137" strokeWidth="1.8" strokeLinecap="round" opacity=".5" />
        <ellipse cx="22.5" cy="76.3" rx="6.3" ry="4.4" fill="#F2748C" opacity="0.75" />
        <ellipse cx="53.5" cy="76.3" rx="6.3" ry="4.4" fill="#F2748C" opacity="0.75" />
      </g>
      <ellipse cx="92" cy="96" rx="19" ry="15" fill="#FFF1E2" stroke="#3D2137" strokeWidth="4.2" />
      <path d="M81.4 45.8C80.6 34.2 76.3 24.7 72 26.6" stroke="#3D2137" strokeWidth="17.8" strokeLinecap="round" fill="none" />
      <path d="M81.4 45.8C80.6 34.2 76.3 24.7 72 26.6" stroke="#FFF1E2" strokeWidth="9.4" strokeLinecap="round" fill="none" />
      <path d="M81.4 45.1L79.5 35.6" stroke="#F6D9BE" strokeWidth="4" strokeLinecap="round" fill="none" />
      <path d="M102.6 45.8C103.4 34.2 107.7 24.7 112 26.6" stroke="#3D2137" strokeWidth="17.8" strokeLinecap="round" fill="none" />
      <path d="M102.6 45.8C103.4 34.2 107.7 24.7 112 26.6" stroke="#FFF1E2" strokeWidth="9.4" strokeLinecap="round" fill="none" />
      <path d="M102.6 45.1L104.5 35.6" stroke="#F6D9BE" strokeWidth="4" strokeLinecap="round" fill="none" />
      <path d="M112 26.6 c-3 -3 -7.5 -1.5 -7.5 3.5" stroke="#3D2137" strokeWidth="17.8" strokeLinecap="round" fill="none" />
      <path d="M112 26.6 c-3 -3 -7.5 -1.5 -7.5 3.5" stroke="#FFF1E2" strokeWidth="9.4" strokeLinecap="round" fill="none" />
      <circle cx="92" cy="58" r="16.5" fill="#FFF1E2" stroke="#3D2137" strokeWidth="4.2" />
      <ellipse cx="77.8" cy="63" rx="5.6" ry="5.1" fill="#FFF1E2" stroke="#3D2137" strokeWidth="4.2" />
      <ellipse cx="106.2" cy="63" rx="5.6" ry="5.1" fill="#FFF1E2" stroke="#3D2137" strokeWidth="4.2" />
      <path d="M81.1 58.3 q4.3 -6.4 8.6 0" stroke="#3D2137" strokeWidth="3.4" fill="none" strokeLinecap="round" />
      <path d="M94.3 58.3 q4.3 -6.4 8.6 0" stroke="#3D2137" strokeWidth="3.4" fill="none" strokeLinecap="round" />
      <path d="M89.9 61.6 q1.1 -2.4 4.3 0 q1.1 3.2 2.1 3.2 q1.1 0 2.1 -3.2Z" fill="#E85D75" />
      <path d="M92 66.4v1.8M92 67.9q-2.8 2.6 -4.4 0M92 67.9q2.8 2.6 4.4 0" stroke="#3D2137" strokeWidth="2.8" fill="none" strokeLinecap="round" />
      <ellipse cx="78.1" cy="63.6" rx="5" ry="3.5" fill="#FF9FB0" opacity="0.85" />
      <ellipse cx="105.9" cy="63.6" rx="5" ry="3.5" fill="#FF9FB0" opacity="0.85" />
      <g className="an-pat">
        <path d="M82 74 C74 60 60 48 48 43" stroke="#3D2137" strokeWidth="13" strokeLinecap="round" fill="none" />
        <path d="M82 74 C74 60 60 48 48 43" stroke="#FFF1E2" strokeWidth="6.4" strokeLinecap="round" fill="none" />
        <g transform="rotate(-34 42 41)">
          <ellipse cx="42" cy="41" rx="9.8" ry="6.2" fill="#FFF1E2" stroke="#3D2137" strokeWidth="4.2" />
          <circle cx="36.4" cy="43.8" r="1.9" fill="#F6D9BE" />
          <circle cx="42" cy="44.6" r="1.9" fill="#F6D9BE" />
          <circle cx="47.6" cy="43.8" r="1.9" fill="#F6D9BE" />
        </g>
      </g>
      <g className="an-twinkle">
        <path d="M10 47.8 q0.8 2.6 4.2 4.2 q-2.6 0.8 -4.2 4.2 q-0.8 -2.6 -4.2 -4.2 q2.6 -0.8 4.2 -4.2Z" fill="#F2B880" opacity="1" />
      </g>
      <g className="an-twinkle an-d2">
        <path d="M66 26.6 q0.6 2.1 3.4 3.4 q-2.1 0.6 -3.4 3.4 q-0.6 -2.1 -3.4 -3.4 q2.1 -0.6 3.4 -3.4Z" fill="#F2B880" opacity="1" />
      </g>
    </Board>
  );
}

/* Forgive me? — clover-biscuit/forgive-sign */
export function CloverBiscuitForgiveSign(props) {
  return (
    <Board {...props}>
      <path d="M83 104 c9 2 13 -3 11 -9" stroke="#3D2137" strokeWidth="13.6" strokeLinecap="round" fill="none" />
      <path d="M83 104 c9 2 13 -3 11 -9" stroke="#E8A854" strokeWidth="6.8" strokeLinecap="round" fill="none" />
      <ellipse cx="60" cy="106" rx="24" ry="15" fill="#E8A854" stroke="#3D2137" strokeWidth="4.2" />
      <path d="M43 94 C34 84 42 70 51 65" stroke="#3D2137" strokeWidth="14.6" strokeLinecap="round" fill="none" />
      <path d="M43 94 C34 84 42 70 51 65" stroke="#E8A854" strokeWidth="7.2" strokeLinecap="round" fill="none" />
      <path d="M77 94 C86 84 78 70 69 65" stroke="#3D2137" strokeWidth="14.6" strokeLinecap="round" fill="none" />
      <path d="M77 94 C86 84 78 70 69 65" stroke="#E8A854" strokeWidth="7.2" strokeLinecap="round" fill="none" />
      <g className="an-tilt">
        <path d="M60 38 V72" stroke="#3D2137" strokeWidth="6" strokeLinecap="round" />
        <rect x="8" y="4" width="104" height="38" rx="10" fill="#FFF7F2" stroke="#3D2137" strokeWidth="4.2" />
        <text x="60" y="29.8" textAnchor="middle" className="hand" fontSize="14.8" textLength="86.0" lengthAdjust="spacingAndGlyphs" fill="#E85D75">forgive me?</text>
      </g>
      <path d="M53.4 64.4 L43.2 47.7 L41.3 62.1 Z" fill="#E8A854" stroke="#3D2137" strokeWidth="4.2" strokeLinejoin="round" />
      <path d="M51 63.2 L43.2 53.5 L43.2 61.7 Z" fill="#F0B9A6" />
      <path d="M66.6 64.4 L76.8 47.7 L78.7 62.1 Z" fill="#E8A854" stroke="#3D2137" strokeWidth="4.2" strokeLinejoin="round" />
      <path d="M69 63.2 L76.8 53.5 L76.8 61.7 Z" fill="#F0B9A6" />
      <circle cx="60" cy="80" r="19.5" fill="#E8A854" stroke="#3D2137" strokeWidth="4.2" />
      <ellipse cx="60" cy="89" rx="10.1" ry="7" fill="#F7D3A8" />
      <ellipse cx="52.2" cy="79.2" rx="6.3" ry="7.2" fill="#3D2137" />
      <circle cx="50" cy="76.8" r="2.5" fill="#FFFFFF" />
      <circle cx="54.1" cy="81.5" r="1.3" fill="#FFFFFF" opacity="0.9" />
      <ellipse cx="67.8" cy="79.2" rx="6.3" ry="7.2" fill="#3D2137" />
      <circle cx="65.6" cy="76.8" r="2.5" fill="#FFFFFF" />
      <circle cx="69.7" cy="81.5" r="1.3" fill="#FFFFFF" opacity="0.9" />
      <path d="M57.3 85.8 q1.4 -2.6 5.5 0 q1.4 3.4 2.7 3.4 q1.4 0 2.7 -3.4Z" fill="#E85D75" />
      <path d="M54.9 91.7 q1.3 -2.2 2.5 0 q1.3 2.2 2.5 0 q1.3 -2.2 2.5 0 q1.3 2.2 2.5 0" stroke="#3D2137" strokeWidth="3.2" fill="none" strokeLinecap="round" />
      <path d="M49.9 84.9 L37.8 83.4" stroke="#3D2137" strokeWidth="1.8" strokeLinecap="round" opacity=".5" />
      <path d="M49.9 86.8 L37.8 87" stroke="#3D2137" strokeWidth="1.8" strokeLinecap="round" opacity=".5" />
      <path d="M49.9 88.8 L37.8 90.6" stroke="#3D2137" strokeWidth="1.8" strokeLinecap="round" opacity=".5" />
      <path d="M70.1 84.9 L82.2 83.4" stroke="#3D2137" strokeWidth="1.8" strokeLinecap="round" opacity=".5" />
      <path d="M70.1 86.8 L82.2 87" stroke="#3D2137" strokeWidth="1.8" strokeLinecap="round" opacity=".5" />
      <path d="M70.1 88.8 L82.2 90.6" stroke="#3D2137" strokeWidth="1.8" strokeLinecap="round" opacity=".5" />
      <ellipse cx="45.6" cy="85.8" rx="5.8" ry="4.1" fill="#F2748C" opacity="0.75" />
      <ellipse cx="74.4" cy="85.8" rx="5.8" ry="4.1" fill="#F2748C" opacity="0.75" />
    </Board>
  );
}

/* Sulk & rain — clover-biscuit/sulk-rain */
export function CloverBiscuitSulkRain(props) {
  return (
    <Board {...props}>
      <g className="an-cloud">
        <path d="M21.8 18a8.6 8.6 0 0 1 14.6 -4.3 8.2 8.2 0 0 1 12.9 3.4 7.3 7.3 0 0 1 -1.7 13.8H25.3 a7.7 7.7 0 0 1 -3.4 -12.9Z" fill="#D5CDE6" stroke="#3D2137" strokeWidth="4.2" strokeLinejoin="round" />
      </g>
      <g className="an-rain">
        <path d="M25 36 v9" stroke="#BFD6F5" strokeWidth="4.6" strokeLinecap="round" />
      </g>
      <g className="an-rain an-d2">
        <path d="M33 36 v9" stroke="#BFD6F5" strokeWidth="4.6" strokeLinecap="round" />
      </g>
      <g className="an-rain an-d3">
        <path d="M41 36 v9" stroke="#BFD6F5" strokeWidth="4.6" strokeLinecap="round" />
      </g>
      <g transform="rotate(-5 32 84)">
        <path d="M47 100 c9 3 12 8 10 14" stroke="#3D2137" strokeWidth="13.6" strokeLinecap="round" fill="none" />
        <path d="M47 100 c9 3 12 8 10 14" stroke="#E8A854" strokeWidth="6.8" strokeLinecap="round" fill="none" />
        <ellipse cx="32" cy="98" rx="20" ry="13" fill="#E8A854" stroke="#3D2137" strokeWidth="4.2" />
        <path d="M26.2 54.4 L9.9 45.5 L15.7 52.4 Z" fill="#E8A854" stroke="#3D2137" strokeWidth="4.2" strokeLinejoin="round" />
        <path d="M24.2 53.4 L9.9 50.6 L17.4 52 Z" fill="#F0B9A6" />
        <path d="M37.8 54.4 L54.1 45.5 L48.3 52.4 Z" fill="#E8A854" stroke="#3D2137" strokeWidth="4.2" strokeLinejoin="round" />
        <path d="M39.8 53.4 L54.1 50.6 L46.6 52 Z" fill="#F0B9A6" />
        <circle cx="32" cy="68" r="17" fill="#E8A854" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="32" cy="75.8" rx="8.8" ry="6.1" fill="#F7D3A8" />
        <path d="M21 67.3 h8.4" stroke="#3D2137" strokeWidth="3.4" fill="none" strokeLinecap="round" />
        <path d="M34.6 67.3 h8.4" stroke="#3D2137" strokeWidth="3.4" fill="none" strokeLinecap="round" />
        <path d="M29.6 73.1 q1.2 -2.6 4.8 0 q1.2 3.4 2.4 3.4 q1.2 0 2.4 -3.4Z" fill="#E85D75" />
        <path d="M29.1 78.2 h5.8" stroke="#3D2137" strokeWidth="3.4" fill="none" strokeLinecap="round" />
        <path d="M23.2 72 L12.6 70.6" stroke="#3D2137" strokeWidth="1.8" strokeLinecap="round" opacity=".5" />
        <path d="M23.2 74 L12.6 74.2" stroke="#3D2137" strokeWidth="1.8" strokeLinecap="round" opacity=".5" />
        <path d="M23.2 76 L12.6 77.8" stroke="#3D2137" strokeWidth="1.8" strokeLinecap="round" opacity=".5" />
        <path d="M40.8 72 L51.4 70.6" stroke="#3D2137" strokeWidth="1.8" strokeLinecap="round" opacity=".5" />
        <path d="M40.8 74 L51.4 74.2" stroke="#3D2137" strokeWidth="1.8" strokeLinecap="round" opacity=".5" />
        <path d="M40.8 76 L51.4 77.8" stroke="#3D2137" strokeWidth="1.8" strokeLinecap="round" opacity=".5" />
      </g>
      <ellipse cx="88" cy="96" rx="19" ry="13" fill="#FFF1E2" stroke="#3D2137" strokeWidth="4.2" />
      <path d="M75.4 53.8C74.6 42.2 70.3 39.2 64.5 45" stroke="#3D2137" strokeWidth="17.8" strokeLinecap="round" fill="none" />
      <path d="M75.4 53.8C74.6 42.2 70.3 39.2 64.5 45" stroke="#FFF1E2" strokeWidth="9.4" strokeLinecap="round" fill="none" />
      <path d="M75.4 53.1L73.5 43.6" stroke="#F6D9BE" strokeWidth="4" strokeLinecap="round" fill="none" />
      <path d="M96.6 53.8C97.4 42.2 101.7 39.2 107.5 45" stroke="#3D2137" strokeWidth="17.8" strokeLinecap="round" fill="none" />
      <path d="M96.6 53.8C97.4 42.2 101.7 39.2 107.5 45" stroke="#FFF1E2" strokeWidth="9.4" strokeLinecap="round" fill="none" />
      <path d="M96.6 53.1L98.5 43.6" stroke="#F6D9BE" strokeWidth="4" strokeLinecap="round" fill="none" />
      <path d="M107.5 45 c-3 -3 -7.5 -1.5 -7.5 3.5" stroke="#3D2137" strokeWidth="17.8" strokeLinecap="round" fill="none" />
      <path d="M107.5 45 c-3 -3 -7.5 -1.5 -7.5 3.5" stroke="#FFF1E2" strokeWidth="9.4" strokeLinecap="round" fill="none" />
      <circle cx="86" cy="66" r="16.5" fill="#FFF1E2" stroke="#3D2137" strokeWidth="4.2" />
      <ellipse cx="71.8" cy="71" rx="5.6" ry="5.1" fill="#FFF1E2" stroke="#3D2137" strokeWidth="4.2" />
      <ellipse cx="100.2" cy="71" rx="5.6" ry="5.1" fill="#FFF1E2" stroke="#3D2137" strokeWidth="4.2" />
      <path d="M75.1 68 q4.3 5.6 8.6 0" stroke="#3D2137" strokeWidth="3.4" fill="none" strokeLinecap="round" />
      <path d="M88.3 68 q4.3 5.6 8.6 0" stroke="#3D2137" strokeWidth="3.4" fill="none" strokeLinecap="round" />
      <path d="M83.9 69.6 q1.1 -2.4 4.3 0 q1.1 3.2 2.1 3.2 q1.1 0 2.1 -3.2Z" fill="#E85D75" />
      <path d="M83.2 76.9 h5.6" stroke="#3D2137" strokeWidth="3.4" fill="none" strokeLinecap="round" />
      <ellipse cx="72.1" cy="71.6" rx="5" ry="3.5" fill="#FF9FB0" opacity="0.85" />
      <ellipse cx="99.9" cy="71.6" rx="5" ry="3.5" fill="#FF9FB0" opacity="0.85" />
      <path d="M76 92 C70 90 66 91 63 92" stroke="#3D2137" strokeWidth="13" strokeLinecap="round" fill="none" />
      <path d="M76 92 C70 90 66 91 63 92" stroke="#FFF1E2" strokeWidth="6.4" strokeLinecap="round" fill="none" />
      <g transform="rotate(12 58 92)">
        <ellipse cx="58" cy="92" rx="8" ry="5.4" fill="#FFF1E2" stroke="#3D2137" strokeWidth="4.2" />
        <circle cx="53.4" cy="94.4" r="1.9" fill="#F6D9BE" />
        <circle cx="58" cy="95.1" r="1.9" fill="#F6D9BE" />
        <circle cx="62.6" cy="94.4" r="1.9" fill="#F6D9BE" />
      </g>
    </Board>
  );
}

/* Made up — clover-biscuit/made-up */
export function CloverBiscuitMadeUp(props) {
  return (
    <Board {...props}>
      <path d="M95 92 c10 0 14 -5 13 -10" stroke="#3D2137" strokeWidth="13.6" strokeLinecap="round" fill="none" />
      <path d="M95 92 c10 0 14 -5 13 -10" stroke="#E8A854" strokeWidth="6.8" strokeLinecap="round" fill="none" />
      <path d="M110.5 83.3 C107.8 80.8 105.7 78.8 105.7 77.2 C105.7 75.2 108.2 74.3 109.3 75.9 C109.9 76.5 110.2 76.9 110.5 77.1 C110.8 76.9 111.1 76.5 111.7 75.9 C112.8 74.3 115.3 75.2 115.3 77.2 C115.3 78.8 113.2 80.8 110.5 83.3 Z" fill="#E85D75" stroke="#3D2137" strokeWidth="3.2" strokeLinejoin="round" />
      <g className="an-cheer">
        <ellipse cx="37" cy="96" rx="21" ry="15" fill="#FFF1E2" stroke="#3D2137" strokeWidth="4.2" />
        <path d="M24.2 42.3C23.2 29.4 18.4 18.9 12.9 21.2" stroke="#3D2137" strokeWidth="17.8" strokeLinecap="round" fill="none" />
        <path d="M24.2 42.3C23.2 29.4 18.4 18.9 12.9 21.2" stroke="#FFF1E2" strokeWidth="9.4" strokeLinecap="round" fill="none" />
        <path d="M24.2 41.6L21.9 30.8" stroke="#F6D9BE" strokeWidth="4" strokeLinecap="round" fill="none" />
        <path d="M47.8 42.3C48.8 29.4 53.6 18.9 59.1 21.2" stroke="#3D2137" strokeWidth="17.8" strokeLinecap="round" fill="none" />
        <path d="M47.8 42.3C48.8 29.4 53.6 18.9 59.1 21.2" stroke="#FFF1E2" strokeWidth="9.4" strokeLinecap="round" fill="none" />
        <path d="M47.8 41.6L50.1 30.8" stroke="#F6D9BE" strokeWidth="4" strokeLinecap="round" fill="none" />
        <path d="M59.1 21.2 c-3 -3 -7.5 -1.5 -7.5 3.5" stroke="#3D2137" strokeWidth="17.8" strokeLinecap="round" fill="none" />
        <path d="M59.1 21.2 c-3 -3 -7.5 -1.5 -7.5 3.5" stroke="#FFF1E2" strokeWidth="9.4" strokeLinecap="round" fill="none" />
        <circle cx="36" cy="56" r="18.5" fill="#FFF1E2" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="20.1" cy="61.5" rx="6.3" ry="5.7" fill="#FFF1E2" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="51.9" cy="61.5" rx="6.3" ry="5.7" fill="#FFF1E2" stroke="#3D2137" strokeWidth="4.2" />
        <path d="M23.8 56.4 q4.8 -7.2 9.6 0" stroke="#3D2137" strokeWidth="3.4" fill="none" strokeLinecap="round" />
        <path d="M38.6 56.4 q4.8 -7.2 9.6 0" stroke="#3D2137" strokeWidth="3.4" fill="none" strokeLinecap="round" />
        <path d="M33.6 60.1 q1.2 -2.4 4.8 0 q1.2 3.2 2.4 3.2 q1.2 0 2.4 -3.2Z" fill="#E85D75" />
        <path d="M30.4 63.8 q5.5 -2.6 11.1 0 q-1.1 7.4 -5.5 7.4 q-4.4 0 -5.5 -7.4Z" fill="#7A2E44" stroke="#3D2137" strokeWidth="3.2" strokeLinejoin="round" />
        <ellipse cx="20.5" cy="62.3" rx="5.5" ry="3.9" fill="#FF9FB0" opacity="0.85" />
        <ellipse cx="51.5" cy="62.3" rx="5.5" ry="3.9" fill="#FF9FB0" opacity="0.85" />
      </g>
      <g className="an-cheer an-d2">
        <ellipse cx="84" cy="98" rx="21" ry="15" fill="#E8A854" stroke="#3D2137" strokeWidth="4.2" />
        <path d="M77.4 44.4 L67.7 27.3 L65.3 42.1 Z" fill="#E8A854" stroke="#3D2137" strokeWidth="4.2" strokeLinejoin="round" />
        <path d="M75 43.2 L67.7 33.1 L67.2 41.7 Z" fill="#F0B9A6" />
        <path d="M90.6 44.4 L100.3 27.3 L102.7 42.1 Z" fill="#E8A854" stroke="#3D2137" strokeWidth="4.2" strokeLinejoin="round" />
        <path d="M93 43.2 L100.3 33.1 L100.8 41.7 Z" fill="#F0B9A6" />
        <circle cx="84" cy="60" r="19.5" fill="#E8A854" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="84" cy="69" rx="10.1" ry="7" fill="#F7D3A8" />
        <path d="M71.1 59.2 q5.1 -7.6 10.1 0" stroke="#3D2137" strokeWidth="3.4" fill="none" strokeLinecap="round" />
        <path d="M86.7 59.2 q5.1 -7.6 10.1 0" stroke="#3D2137" strokeWidth="3.4" fill="none" strokeLinecap="round" />
        <path d="M81.3 65.8 q1.4 -2.6 5.5 0 q1.4 3.4 2.7 3.4 q1.4 0 2.7 -3.4Z" fill="#E85D75" />
        <path d="M78.2 68.6 q5.8 -2.6 11.7 0 q-1.2 7.8 -5.8 7.8 q-4.7 0 -5.8 -7.8Z" fill="#7A2E44" stroke="#3D2137" strokeWidth="3.2" strokeLinejoin="round" />
        <path d="M73.9 64.9 L61.8 63.4" stroke="#3D2137" strokeWidth="1.8" strokeLinecap="round" opacity=".5" />
        <path d="M73.9 66.8 L61.8 67" stroke="#3D2137" strokeWidth="1.8" strokeLinecap="round" opacity=".5" />
        <path d="M73.9 68.8 L61.8 70.6" stroke="#3D2137" strokeWidth="1.8" strokeLinecap="round" opacity=".5" />
        <path d="M94.1 64.9 L106.2 63.4" stroke="#3D2137" strokeWidth="1.8" strokeLinecap="round" opacity=".5" />
        <path d="M94.1 66.8 L106.2 67" stroke="#3D2137" strokeWidth="1.8" strokeLinecap="round" opacity=".5" />
        <path d="M94.1 68.8 L106.2 70.6" stroke="#3D2137" strokeWidth="1.8" strokeLinecap="round" opacity=".5" />
        <ellipse cx="69.6" cy="65.8" rx="5.8" ry="4.1" fill="#F2748C" opacity="0.75" />
        <ellipse cx="98.4" cy="65.8" rx="5.8" ry="4.1" fill="#F2748C" opacity="0.75" />
      </g>
      <path d="M56 96 C62 99 68 99 74 96" stroke="#3D2137" strokeWidth="14.2" strokeLinecap="round" fill="none" />
      <path d="M56 96 C62 99 68 99 74 96" stroke="#FFF1E2" strokeWidth="7" strokeLinecap="round" fill="none" />
      <g className="an-bob">
        <path d="M60 18.9 C56.9 16.1 54.5 13.8 54.5 11.9 C54.5 9.6 57.3 8.6 58.6 10.4 C59.3 11.2 59.7 11.5 60 11.8 C60.3 11.5 60.7 11.2 61.4 10.4 C62.7 8.6 65.5 9.6 65.5 11.9 C65.5 13.8 63.1 16.1 60 18.9 Z" fill="#E85D75" stroke="#3D2137" strokeWidth="3.2" strokeLinejoin="round" />
      </g>
      <g className="an-bob an-d2">
        <path d="M16 28.9 C14.2 27.2 12.7 25.9 12.7 24.8 C12.7 23.4 14.4 22.8 15.2 23.9 C15.6 24.3 15.8 24.5 16 24.7 C16.2 24.5 16.4 24.3 16.8 23.9 C17.6 22.8 19.3 23.4 19.3 24.8 C19.3 25.9 17.8 27.2 16 28.9 Z" fill="#E85D75" stroke="#3D2137" strokeWidth="3.2" strokeLinejoin="round" />
      </g>
      <g className="an-twinkle">
        <path d="M6 58.6 q0.6 2.1 3.4 3.4 q-2.1 0.6 -3.4 3.4 q-0.6 -2.1 -3.4 -3.4 q2.1 -0.6 3.4 -3.4Z" fill="#F2B880" opacity="1" />
      </g>
      <g className="an-twinkle an-d2">
        <path d="M114 67 q0.5 1.9 3 3 q-1.9 0.5 -3 3 q-0.5 -1.9 -3 -3 q1.9 -0.5 3 -3Z" fill="#F2B880" opacity="1" />
      </g>
    </Board>
  );
}

/* id -> component, ready for the registry in ./index.jsx */
export const COMPONENTS = {
  'clover-biscuit/begging': CloverBiscuitBegging,
  'clover-biscuit/waterfall-cry': CloverBiscuitWaterfallCry,
  'clover-biscuit/big-hug': CloverBiscuitBigHug,
  'clover-biscuit/flowers-shy': CloverBiscuitFlowersShy,
  'clover-biscuit/pouty': CloverBiscuitPouty,
  'clover-biscuit/cheek-kiss': CloverBiscuitCheekKiss,
  'clover-biscuit/head-pat': CloverBiscuitHeadPat,
  'clover-biscuit/forgive-sign': CloverBiscuitForgiveSign,
  'clover-biscuit/sulk-rain': CloverBiscuitSulkRain,
  'clover-biscuit/made-up': CloverBiscuitMadeUp,
};

export default COMPONENTS;
