/* eslint-disable */
'use client';

/**
 * Mochi & Bao 🐼 — Panda couple, chunkier heads and glossy eyes.
 *
 * AUTO-GENERATED by tools/stickers/gen_pack_jsx.py. Do not edit by hand:
 * re-run the generator instead, or the drawings drift from the sheets.
 *
 * Ten poses, one 120x120 board each, house palette and plum ink. The
 * `an-*` classes are the little motion loops; they live in globals.css and
 * switch themselves off under prefers-reduced-motion.
 */

import { Board } from './board';

/* Begging — mochi-bao/begging */
export function MochiBaoBegging(props) {
  return (
    <Board {...props}>
      <g className="an-twinkle">
        <path d="M16 35.6 q0.8 2.7 4.4 4.4 q-2.7 0.8 -4.4 4.4 q-0.8 -2.7 -4.4 -4.4 q2.7 -0.8 4.4 -4.4Z" fill="#F2B880" opacity="1" />
      </g>
      <g className="an-twinkle an-d2">
        <path d="M104 46.4 q0.6 2.2 3.6 3.6 q-2.2 0.6 -3.6 3.6 q-0.6 -2.2 -3.6 -3.6 q2.2 -0.6 3.6 -3.6Z" fill="#F2B880" opacity="1" />
      </g>
      <g className="an-bob an-d2">
        <path d="M103 21.5 c2.3 2.7 3.6 4.9 0 8.5 c-3.6 0 -3.6 -2.2 0 -8.5Z" fill="#BFD6F5" stroke="#3D2137" strokeWidth="2.2" strokeLinejoin="round" />
      </g>
      <g className="an-plead">
        <ellipse cx="50" cy="95.3" rx="6.8" ry="5.1" fill="#3D2137" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="70" cy="95.3" rx="6.8" ry="5.1" fill="#3D2137" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="60" cy="75.5" rx="20" ry="23" fill="#FFFDFC" stroke="#3D2137" strokeWidth="4.2" />
        <circle cx="41" cy="20.8" r="9" fill="#3D2137" stroke="#3D2137" strokeWidth="4.2" />
        <circle cx="79" cy="20.8" r="9" fill="#3D2137" stroke="#3D2137" strokeWidth="4.2" />
        <circle cx="60" cy="40" r="25" fill="#FFFDFC" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="48.8" cy="42.8" rx="8.8" ry="10.8" fill="#3D2137" transform="rotate(-26 48.8 42.8)" />
        <ellipse cx="71.2" cy="42.8" rx="8.8" ry="10.8" fill="#3D2137" transform="rotate(26 71.2 42.8)" />
        <ellipse cx="48.8" cy="42.2" rx="8.2" ry="9.3" fill="#FFF7F2" />
        <ellipse cx="48.8" cy="42.7" rx="5.6" ry="6.4" fill="#3D2137" />
        <circle cx="46.8" cy="40.4" r="2.6" fill="#FFFFFF" />
        <circle cx="50.7" cy="44.6" r="1.3" fill="#FFFFFF" opacity=".92" />
        <ellipse cx="71.2" cy="42.2" rx="8.2" ry="9.3" fill="#FFF7F2" />
        <ellipse cx="71.2" cy="42.7" rx="5.6" ry="6.4" fill="#3D2137" />
        <circle cx="69.3" cy="40.4" r="2.6" fill="#FFFFFF" />
        <circle cx="73.2" cy="44.6" r="1.3" fill="#FFFFFF" opacity=".92" />
        <path d="M58 49 q2 -2.4 4 0 q-0.4 3.1 -2 3.1 q-1.6 0 -2 -3.1Z" fill="#3D2137" />
        <path d="M54.5 55 q1.4 -2.2 2.8 0 q1.4 2.2 2.8 0 q1.4 -2.2 2.8 0 q1.4 2.2 2.8 0" stroke="#3D2137" strokeWidth="3" fill="none" strokeLinecap="round" />
        <ellipse cx="42.5" cy="53" rx="5.2" ry="3.9" fill="#FF9FB0" opacity="0.9" />
        <ellipse cx="77.5" cy="53" rx="5.2" ry="3.9" fill="#FF9FB0" opacity="0.9" />
        <path d="M42.8 68.6 Q42.7 73.6 51.5 76.5" stroke="#3D2137" strokeWidth="11.2" strokeLinecap="round" fill="none" />
        <path d="M42.8 68.6 Q42.7 73.6 51.5 76.5" stroke="#3D2137" strokeWidth="5.4" strokeLinecap="round" fill="none" />
        <path d="M77.2 68.6 Q69.3 73.6 68.5 76.5" stroke="#3D2137" strokeWidth="11.2" strokeLinecap="round" fill="none" />
        <path d="M77.2 68.6 Q69.3 73.6 68.5 76.5" stroke="#3D2137" strokeWidth="5.4" strokeLinecap="round" fill="none" />
        <ellipse cx="51" cy="76.5" rx="5.4" ry="4.7" fill="#3D2137" stroke="#3D2137" strokeWidth="3.4" transform="rotate(-26 51 76.5)" />
        <ellipse cx="69" cy="76.5" rx="5.4" ry="4.7" fill="#3D2137" stroke="#3D2137" strokeWidth="3.4" transform="rotate(26 69 76.5)" />
      </g>
    </Board>
  );
}

/* Waterfall cry — mochi-bao/waterfall-cry */
export function MochiBaoWaterfallCry(props) {
  return (
    <Board {...props}>
      <ellipse cx="60" cy="108" rx="27" ry="4.8" fill="#BFD6F5" opacity=".75" />
      <g className="an-sob">
        <ellipse cx="50.4" cy="91.1" rx="6.5" ry="4.9" fill="#3D2137" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="69.6" cy="91.1" rx="6.5" ry="4.9" fill="#3D2137" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="60" cy="72.1" rx="19.2" ry="22.1" fill="#FFFDFC" stroke="#3D2137" strokeWidth="4.2" />
        <path d="M43.5 65.5 Q43 76.1 33.6 86" stroke="#3D2137" strokeWidth="11.2" strokeLinecap="round" fill="none" />
        <path d="M43.5 65.5 Q43 76.1 33.6 86" stroke="#3D2137" strokeWidth="5.4" strokeLinecap="round" fill="none" />
        <path d="M76.5 65.5 Q85 76.1 86.4 86" stroke="#3D2137" strokeWidth="11.2" strokeLinecap="round" fill="none" />
        <path d="M76.5 65.5 Q85 76.1 86.4 86" stroke="#3D2137" strokeWidth="5.4" strokeLinecap="round" fill="none" />
        <ellipse cx="32.6" cy="87" rx="5.4" ry="4.7" fill="#3D2137" stroke="#3D2137" strokeWidth="3.4" transform="rotate(-18 32.6 87)" />
        <ellipse cx="87.4" cy="87" rx="5.4" ry="4.7" fill="#3D2137" stroke="#3D2137" strokeWidth="3.4" transform="rotate(18 87.4 87)" />
        <circle cx="41.8" cy="20.7" r="8.6" fill="#3D2137" stroke="#3D2137" strokeWidth="4.2" />
        <circle cx="78.2" cy="20.7" r="8.6" fill="#3D2137" stroke="#3D2137" strokeWidth="4.2" />
        <circle cx="60" cy="38" r="24" fill="#FFFDFC" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="49.2" cy="40.6" rx="8.4" ry="10.3" fill="#3D2137" transform="rotate(-26 49.2 40.6)" />
        <ellipse cx="70.8" cy="40.6" rx="8.4" ry="10.3" fill="#3D2137" transform="rotate(26 70.8 40.6)" />
        <path d="M42.7 44.5 L49.2 35.8 L55.7 44.5" stroke="#FFF7F2" strokeWidth="3.6" fill="none" strokeLinecap="round" strokeLinejoin="round" />
        <path d="M64.3 44.5 L70.8 35.8 L77.3 44.5" stroke="#FFF7F2" strokeWidth="3.6" fill="none" strokeLinecap="round" strokeLinejoin="round" />
        <path d="M58.1 46.6 q1.9 -2.4 3.8 0 q-0.4 3 -1.9 3 q-1.5 0 -1.9 -3Z" fill="#3D2137" />
        <ellipse cx="60" cy="53.6" rx="4.1" ry="5" fill="#7A2E44" stroke="#3D2137" strokeWidth="3" />
        <ellipse cx="43.2" cy="50.5" rx="5" ry="3.7" fill="#FF9FB0" opacity="0.9" />
        <ellipse cx="76.8" cy="50.5" rx="5" ry="3.7" fill="#FF9FB0" opacity="0.9" />
      </g>
      <g className="an-stream">
        <path d="M49.2 44.5 v38" stroke="#BFD6F5" strokeWidth="6.2" strokeLinecap="round" opacity=".95" />
      </g>
      <g className="an-stream an-d2">
        <path d="M70.8 44.5 v38" stroke="#BFD6F5" strokeWidth="6.2" strokeLinecap="round" opacity=".95" />
      </g>
      <g className="an-teardrop">
        <path d="M18 41.3 c2 2.7 3.4 4.2 3.4 5.9 c0 2 -1.6 3.4 -3.4 3.4 c-2 0 -3.4 -1.7 -3.4 -3.4Z" fill="#BFD6F5" stroke="#3D2137" strokeWidth="2.6" strokeLinejoin="round" />
      </g>
      <g className="an-teardrop an-d3">
        <path d="M103 47.9 c1.8 2.3 3 3.7 3 5.2 c0 1.8 -1.4 3 -3 3 c-1.8 0 -3 -1.5 -3 -3Z" fill="#BFD6F5" stroke="#3D2137" strokeWidth="2.6" strokeLinejoin="round" />
      </g>
    </Board>
  );
}

/* Big hug — mochi-bao/big-hug */
export function MochiBaoBigHug(props) {
  return (
    <Board {...props}>
      <g className="an-squeeze">
        <path d="M75.2 79.6 C61.5 85.2 36.9 83.2 26.3 75.2" stroke="#3D2137" strokeWidth="11.8" strokeLinecap="round" fill="none" />
        <path d="M75.2 79.6 C61.5 85.2 36.9 83.2 26.3 75.2" stroke="#3D2137" strokeWidth="5.8" strokeLinecap="round" fill="none" />
        <ellipse cx="24.5" cy="74.9" rx="5.7" ry="4.9" fill="#3D2137" stroke="#3D2137" strokeWidth="3.4" transform="rotate(18 24.5 74.9)" />
        <path d="M47.6 78.7 C61.5 93.2 86.4 91.2 97.6 82.4" stroke="#3D2137" strokeWidth="11.8" strokeLinecap="round" fill="none" />
        <path d="M47.6 78.7 C61.5 93.2 86.4 91.2 97.6 82.4" stroke="#3D2137" strokeWidth="5.8" strokeLinecap="round" fill="none" />
        <ellipse cx="99.5" cy="82.1" rx="5.7" ry="4.9" fill="#3D2137" stroke="#3D2137" strokeWidth="3.4" transform="rotate(-18 99.5 82.1)" />
        <ellipse cx="35.4" cy="92" rx="5.2" ry="3.8" fill="#3D2137" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="50.6" cy="92" rx="5.2" ry="3.8" fill="#3D2137" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="43" cy="77" rx="15.2" ry="17.5" fill="#FFFDFC" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="72" cy="97.2" rx="5.4" ry="4" fill="#3D2137" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="88" cy="97.2" rx="5.4" ry="4" fill="#3D2137" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="80" cy="81.4" rx="16" ry="18.4" fill="#FBEEDF" stroke="#3D2137" strokeWidth="4.2" />
        <circle cx="28.6" cy="35.6" r="6.8" fill="#3D2137" stroke="#3D2137" strokeWidth="4.2" />
        <circle cx="57.4" cy="35.6" r="6.8" fill="#3D2137" stroke="#3D2137" strokeWidth="4.2" />
        <circle cx="43" cy="50" r="19" fill="#FFFDFC" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="34.5" cy="52.1" rx="6.6" ry="8.2" fill="#3D2137" transform="rotate(-26 34.5 52.1)" />
        <ellipse cx="51.5" cy="52.1" rx="6.6" ry="8.2" fill="#3D2137" transform="rotate(26 51.5 52.1)" />
        <path d="M29.5 51.7 q4.9 -7.4 9.8 0" stroke="#FFF7F2" strokeWidth="3.6" fill="none" strokeLinecap="round" />
        <path d="M46.6 51.7 q4.9 -7.4 9.8 0" stroke="#FFF7F2" strokeWidth="3.6" fill="none" strokeLinecap="round" />
        <path d="M41.5 56.8 q1.5 -2.4 3 0 q-0.3 2.4 -1.5 2.4 q-1.2 0 -1.5 -2.4Z" fill="#3D2137" />
        <path d="M40.1 61.4 q2.9 3.2 5.7 0" stroke="#3D2137" strokeWidth="3.2" fill="none" strokeLinecap="round" />
        <ellipse cx="29.7" cy="59.9" rx="4" ry="2.9" fill="#FF9FB0" opacity="0.9" />
        <ellipse cx="56.3" cy="59.9" rx="4" ry="2.9" fill="#FF9FB0" opacity="0.9" />
        <circle cx="64.8" cy="37.8" r="7.2" fill="#3D2137" stroke="#3D2137" strokeWidth="4.2" />
        <circle cx="64.8" cy="38.5" r="3.3" fill="#FFC9D6" />
        <circle cx="95.2" cy="37.8" r="7.2" fill="#3D2137" stroke="#3D2137" strokeWidth="4.2" />
        <circle cx="95.2" cy="38.5" r="3.3" fill="#FFC9D6" />
        <circle cx="80" cy="53" r="20" fill="#FBEEDF" stroke="#3D2137" strokeWidth="4.2" />
        <path d="M78.4 33.2 c-1.2 -4.4 3.4 -5.8 5.4 -2.8" stroke="#3D2137" strokeWidth="4.6" strokeLinecap="round" fill="none" />
        <ellipse cx="80" cy="62.6" rx="6.8" ry="5.2" fill="#FFF9F2" />
        <ellipse cx="71" cy="55.2" rx="7.6" ry="7.6" fill="#3D2137" transform="rotate(-6 71 55.2)" />
        <ellipse cx="89" cy="55.2" rx="7.6" ry="7.6" fill="#3D2137" transform="rotate(6 89 55.2)" />
        <path d="M65.8 54.8 q5.2 -7.7 10.3 0" stroke="#FFF7F2" strokeWidth="3.6" fill="none" strokeLinecap="round" />
        <path d="M83.8 54.8 q5.2 -7.7 10.3 0" stroke="#FFF7F2" strokeWidth="3.6" fill="none" strokeLinecap="round" />
        <path d="M78.4 60.2 q1.6 -2.4 3.2 0 q-0.3 2.5 -1.6 2.5 q-1.3 0 -1.6 -2.5Z" fill="#3D2137" />
        <path d="M77 65 q3 3.4 6 0" stroke="#3D2137" strokeWidth="3.2" fill="none" strokeLinecap="round" />
        <ellipse cx="66" cy="63.4" rx="4.2" ry="3.1" fill="#F2748C" opacity="0.9" />
        <ellipse cx="94" cy="63.4" rx="4.2" ry="3.1" fill="#F2748C" opacity="0.9" />
        <path d="M66 80 C58 76 48 76 42 79" stroke="#3D2137" strokeWidth="11.4" strokeLinecap="round" fill="none" />
        <path d="M66 80 C58 76 48 76 42 79" stroke="#3D2137" strokeWidth="5.6" strokeLinecap="round" fill="none" />
      </g>
      <g className="an-bob">
        <path d="M60 16.8 C57 14 54.6 11.8 54.6 10 C54.6 7.8 57.4 6.8 58.7 8.5 C59.3 9.2 59.7 9.6 60 9.9 C60.3 9.6 60.7 9.2 61.3 8.5 C62.6 6.8 65.4 7.8 65.4 10 C65.4 11.8 63 14 60 16.8 Z" fill="#E85D75" stroke="#3D2137" strokeWidth="3.2" strokeLinejoin="round" />
      </g>
      <g className="an-bob an-d2">
        <path d="M102 23.3 C99.9 21.4 98.3 19.9 98.3 18.6 C98.3 17.1 100.2 16.4 101.1 17.6 C101.5 18.1 101.8 18.3 102 18.5 C102.2 18.3 102.5 18.1 102.9 17.6 C103.8 16.4 105.7 17.1 105.7 18.6 C105.7 19.9 104.1 21.4 102 23.3 Z" fill="#E85D75" stroke="#3D2137" strokeWidth="3.2" strokeLinejoin="round" />
      </g>
    </Board>
  );
}

/* Flowers, shy — mochi-bao/flowers-shy */
export function MochiBaoFlowersShy(props) {
  return (
    <Board {...props}>
      <g className="an-shy">
        <ellipse cx="34.4" cy="95.1" rx="6.5" ry="4.9" fill="#3D2137" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="53.6" cy="95.1" rx="6.5" ry="4.9" fill="#3D2137" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="44" cy="76.1" rx="19.2" ry="22.1" fill="#FBEEDF" stroke="#3D2137" strokeWidth="4.2" />
        <path d="M27.5 69.5 Q32 74.9 30.8 79.2" stroke="#3D2137" strokeWidth="11.2" strokeLinecap="round" fill="none" />
        <path d="M27.5 69.5 Q32 74.9 30.8 79.2" stroke="#3D2137" strokeWidth="5.4" strokeLinecap="round" fill="none" />
        <circle cx="25.8" cy="24" r="8.6" fill="#3D2137" stroke="#3D2137" strokeWidth="4.2" />
        <circle cx="25.8" cy="24.9" r="4" fill="#FFC9D6" />
        <circle cx="62.2" cy="24" r="8.6" fill="#3D2137" stroke="#3D2137" strokeWidth="4.2" />
        <circle cx="62.2" cy="24.9" r="4" fill="#FFC9D6" />
        <circle cx="44" cy="42" r="24" fill="#FBEEDF" stroke="#3D2137" strokeWidth="4.2" />
        <path d="M42.1 18.2 c-1.2 -4.4 3.4 -5.8 5.4 -2.8" stroke="#3D2137" strokeWidth="4.6" strokeLinecap="round" fill="none" />
        <ellipse cx="44" cy="53.5" rx="8.2" ry="6.2" fill="#FFF9F2" />
        <ellipse cx="33.2" cy="44.6" rx="9.1" ry="9.1" fill="#3D2137" transform="rotate(-6 33.2 44.6)" />
        <ellipse cx="54.8" cy="44.6" rx="9.1" ry="9.1" fill="#3D2137" transform="rotate(6 54.8 44.6)" />
        <path d="M27 44.2 q6.2 -9.3 12.4 0" stroke="#FFF7F2" strokeWidth="3.6" fill="none" strokeLinecap="round" />
        <path d="M48.6 44.2 q6.2 -9.3 12.4 0" stroke="#FFF7F2" strokeWidth="3.6" fill="none" strokeLinecap="round" />
        <path d="M42.1 50.6 q1.9 -2.4 3.8 0 q-0.4 3 -1.9 3 q-1.5 0 -1.9 -3Z" fill="#3D2137" />
        <path d="M40.4 56.4 q3.6 4.1 7.2 0" stroke="#3D2137" strokeWidth="3.2" fill="none" strokeLinecap="round" />
        <ellipse cx="27.2" cy="54.5" rx="5" ry="3.7" fill="#F2748C" opacity="0.9" />
        <ellipse cx="60.8" cy="54.5" rx="5" ry="3.7" fill="#F2748C" opacity="0.9" />
        <ellipse cx="27.2" cy="54.5" rx="6.3" ry="4.6" fill="#F2748C" opacity="0.9" />
        <ellipse cx="60.8" cy="54.5" rx="6.3" ry="4.6" fill="#F2748C" opacity="0.9" />
        <path d="M60.5 69.5 Q69.3 72 89 72" stroke="#3D2137" strokeWidth="11.2" strokeLinecap="round" fill="none" />
        <path d="M60.5 69.5 Q69.3 72 89 72" stroke="#3D2137" strokeWidth="5.4" strokeLinecap="round" fill="none" />
        <ellipse cx="92" cy="74" rx="5.4" ry="4.7" fill="#3D2137" stroke="#3D2137" strokeWidth="3.4" transform="rotate(-10 92 74)" />
      </g>
      <g className="an-sway-s">
        <path d="M92 70 Q88.2 61.2 81 54" stroke="#6FA96E" strokeWidth="3.6" strokeLinecap="round" fill="none" />
        <path d="M92 70 Q92.3 55.8 93 45" stroke="#6FA96E" strokeWidth="3.6" strokeLinecap="round" fill="none" />
        <path d="M92 70 Q96.2 62.4 104 56" stroke="#6FA96E" strokeWidth="3.6" strokeLinecap="round" fill="none" />
        <path d="M89 60 l-6 3 M95 64 l6 4" stroke="#6FA96E" strokeWidth="3.2" strokeLinecap="round" fill="none" />
        <circle cx="81" cy="48.9" r="3.6" fill="#FFF3E9" stroke="#3D2137" strokeWidth="2.4" />
        <circle cx="85.8" cy="52.4" r="3.6" fill="#FFF3E9" stroke="#3D2137" strokeWidth="2.4" />
        <circle cx="84" cy="58.1" r="3.6" fill="#FFF3E9" stroke="#3D2137" strokeWidth="2.4" />
        <circle cx="78" cy="58.1" r="3.6" fill="#FFF3E9" stroke="#3D2137" strokeWidth="2.4" />
        <circle cx="76.2" cy="52.4" r="3.6" fill="#FFF3E9" stroke="#3D2137" strokeWidth="2.4" />
        <circle cx="81" cy="54" r="2.7" fill="#F2B880" stroke="#3D2137" strokeWidth="2.4" />
        <circle cx="93" cy="39.6" r="3.8" fill="#FFF3E9" stroke="#3D2137" strokeWidth="2.4" />
        <circle cx="98.1" cy="43.3" r="3.8" fill="#FFF3E9" stroke="#3D2137" strokeWidth="2.4" />
        <circle cx="96.2" cy="49.4" r="3.8" fill="#FFF3E9" stroke="#3D2137" strokeWidth="2.4" />
        <circle cx="89.8" cy="49.4" r="3.8" fill="#FFF3E9" stroke="#3D2137" strokeWidth="2.4" />
        <circle cx="87.9" cy="43.3" r="3.8" fill="#FFF3E9" stroke="#3D2137" strokeWidth="2.4" />
        <circle cx="93" cy="45" r="2.9" fill="#F2B880" stroke="#3D2137" strokeWidth="2.4" />
        <circle cx="104" cy="51.2" r="3.4" fill="#FFF3E9" stroke="#3D2137" strokeWidth="2.4" />
        <circle cx="108.5" cy="54.5" r="3.4" fill="#FFF3E9" stroke="#3D2137" strokeWidth="2.4" />
        <circle cx="106.8" cy="59.8" r="3.4" fill="#FFF3E9" stroke="#3D2137" strokeWidth="2.4" />
        <circle cx="101.2" cy="59.8" r="3.4" fill="#FFF3E9" stroke="#3D2137" strokeWidth="2.4" />
        <circle cx="99.5" cy="54.5" r="3.4" fill="#FFF3E9" stroke="#3D2137" strokeWidth="2.4" />
        <circle cx="104" cy="56" r="2.6" fill="#F2B880" stroke="#3D2137" strokeWidth="2.4" />
      </g>
      <g className="an-twinkle">
        <path d="M14 22 q0.7 2.5 4 4 q-2.5 0.7 -4 4 q-0.7 -2.5 -4 -4 q2.5 -0.7 4 -4Z" fill="#F2B880" opacity="1" />
      </g>
      <g className="an-twinkle an-d2">
        <path d="M110 36.8 q0.6 2 3.2 3.2 q-2 0.6 -3.2 3.2 q-0.6 -2 -3.2 -3.2 q2 -0.6 3.2 -3.2Z" fill="#F2B880" opacity="1" />
      </g>
    </Board>
  );
}

/* Pouty — mochi-bao/pouty */
export function MochiBaoPouty(props) {
  return (
    <Board {...props}>
      <g className="an-steam">
        <path d="M100 24c6-4 3-10-2-12s-6-7-1-10" stroke="#D5CDE6" strokeWidth="5.4" strokeLinecap="round" fill="none" />
      </g>
      <g className="an-steam an-d2">
        <path d="M111 40c5-4 2-9-2-11" stroke="#D5CDE6" strokeWidth="4.6" strokeLinecap="round" fill="none" />
      </g>
      <g className="an-huff">
        <g transform="rotate(-6 56 66)">
          <ellipse cx="46" cy="97.3" rx="6.8" ry="5.1" fill="#3D2137" stroke="#3D2137" strokeWidth="4.2" />
          <ellipse cx="66" cy="97.3" rx="6.8" ry="5.1" fill="#3D2137" stroke="#3D2137" strokeWidth="4.2" />
          <ellipse cx="56" cy="77.5" rx="20" ry="23" fill="#FBEEDF" stroke="#3D2137" strokeWidth="4.2" />
          <circle cx="37" cy="25" r="9" fill="#3D2137" stroke="#3D2137" strokeWidth="4.2" />
          <circle cx="37" cy="25.9" r="4.1" fill="#FFC9D6" />
          <circle cx="75" cy="25" r="9" fill="#3D2137" stroke="#3D2137" strokeWidth="4.2" />
          <circle cx="75" cy="25.9" r="4.1" fill="#FFC9D6" />
          <circle cx="56" cy="42" r="25" fill="#FBEEDF" stroke="#3D2137" strokeWidth="4.2" />
          <path d="M54 17.2 c-1.2 -4.4 3.4 -5.8 5.4 -2.8" stroke="#3D2137" strokeWidth="4.6" strokeLinecap="round" fill="none" />
          <ellipse cx="56" cy="54" rx="8.5" ry="6.5" fill="#FFF9F2" />
          <ellipse cx="44.8" cy="44.8" rx="9.5" ry="9.5" fill="#3D2137" transform="rotate(-6 44.8 44.8)" />
          <ellipse cx="67.2" cy="44.8" rx="9.5" ry="9.5" fill="#3D2137" transform="rotate(6 67.2 44.8)" />
          <path d="M38.3 33.9 L51.2 28.9" stroke="#FFF7F2" strokeWidth="3.2" strokeLinecap="round" />
          <path d="M60.8 28.9 L73.7 33.9" stroke="#FFF7F2" strokeWidth="3.2" strokeLinecap="round" />
          <path d="M38.9 44.2 h11.6" stroke="#FFF7F2" strokeWidth="3.6" fill="none" strokeLinecap="round" />
          <path d="M61.4 44.2 h11.6" stroke="#FFF7F2" strokeWidth="3.6" fill="none" strokeLinecap="round" />
          <path d="M54 51 q2 -2.4 4 0 q-0.4 3.1 -2 3.1 q-1.6 0 -2 -3.1Z" fill="#3D2137" />
          <path d="M50.2 57 q2.9 -5.4 5.8 0 q2.9 5.4 5.8 0" stroke="#3D2137" strokeWidth="3.4" fill="none" strokeLinecap="round" />
          <ellipse cx="38.5" cy="55" rx="5.2" ry="3.9" fill="#F2748C" opacity="0.9" />
          <ellipse cx="73.5" cy="55" rx="5.2" ry="3.9" fill="#F2748C" opacity="0.9" />
          <path d="M44 85.3 C51.6 89 60.4 89 67.6 86.2" stroke="#3D2137" strokeWidth="9.6" strokeLinecap="round" fill="none" />
          <path d="M44 85.3 C51.6 89 60.4 89 67.6 86.2" stroke="#3D2137" strokeWidth="4.7" strokeLinecap="round" fill="none" />
          <path d="M68 81.2 C60.4 84.4 51.6 84.4 44.4 81.6" stroke="#3D2137" strokeWidth="9.6" strokeLinecap="round" fill="none" />
          <path d="M68 81.2 C60.4 84.4 51.6 84.4 44.4 81.6" stroke="#3D2137" strokeWidth="4.7" strokeLinecap="round" fill="none" />
          <ellipse cx="68" cy="86.2" rx="4.5" ry="3.9" fill="#3D2137" stroke="#3D2137" strokeWidth="3.4" transform="rotate(16 68 86.2)" />
          <ellipse cx="44" cy="81.6" rx="4.5" ry="3.9" fill="#3D2137" stroke="#3D2137" strokeWidth="3.4" transform="rotate(-16 44 81.6)" />
        </g>
      </g>
    </Board>
  );
}

/* Cheek kiss — mochi-bao/cheek-kiss */
export function MochiBaoCheekKiss(props) {
  return (
    <Board {...props}>
      <g className="an-startle">
        <ellipse cx="72" cy="92.2" rx="5.4" ry="4" fill="#3D2137" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="88" cy="92.2" rx="5.4" ry="4" fill="#3D2137" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="80" cy="76.4" rx="16" ry="18.4" fill="#FBEEDF" stroke="#3D2137" strokeWidth="4.2" />
        <circle cx="64.8" cy="32" r="7.2" fill="#3D2137" stroke="#3D2137" strokeWidth="4.2" />
        <circle cx="64.8" cy="32.7" r="3.3" fill="#FFC9D6" />
        <circle cx="95.2" cy="32" r="7.2" fill="#3D2137" stroke="#3D2137" strokeWidth="4.2" />
        <circle cx="95.2" cy="32.7" r="3.3" fill="#FFC9D6" />
        <circle cx="80" cy="48" r="20" fill="#FBEEDF" stroke="#3D2137" strokeWidth="4.2" />
        <path d="M78.4 28.2 c-1.2 -4.4 3.4 -5.8 5.4 -2.8" stroke="#3D2137" strokeWidth="4.6" strokeLinecap="round" fill="none" />
        <ellipse cx="80" cy="57.6" rx="6.8" ry="5.2" fill="#FFF9F2" />
        <ellipse cx="71" cy="50.2" rx="7.6" ry="7.6" fill="#3D2137" transform="rotate(-6 71 50.2)" />
        <ellipse cx="89" cy="50.2" rx="7.6" ry="7.6" fill="#3D2137" transform="rotate(6 89 50.2)" />
        <ellipse cx="71" cy="49.8" rx="6.1" ry="6.9" fill="#FFF7F2" />
        <ellipse cx="71" cy="50.2" rx="4.2" ry="4.8" fill="#3D2137" />
        <circle cx="69.6" cy="48.4" r="1.9" fill="#FFFFFF" />
        <circle cx="72.4" cy="51.6" r="1" fill="#FFFFFF" opacity=".92" />
        <ellipse cx="89" cy="49.8" rx="6.1" ry="6.9" fill="#FFF7F2" />
        <ellipse cx="89" cy="50.2" rx="4.2" ry="4.8" fill="#3D2137" />
        <circle cx="87.6" cy="48.4" r="1.9" fill="#FFFFFF" />
        <circle cx="90.4" cy="51.6" r="1" fill="#FFFFFF" opacity=".92" />
        <path d="M78.4 55.2 q1.6 -2.4 3.2 0 q-0.3 2.5 -1.6 2.5 q-1.3 0 -1.6 -2.5Z" fill="#3D2137" />
        <ellipse cx="80" cy="60" rx="2.6" ry="3.2" fill="#7A2E44" stroke="#3D2137" strokeWidth="3" />
        <ellipse cx="66" cy="58.4" rx="4.2" ry="3.1" fill="#F2748C" opacity="0.9" />
        <ellipse cx="94" cy="58.4" rx="4.2" ry="3.1" fill="#F2748C" opacity="0.9" />
        <ellipse cx="66" cy="58.4" rx="5.5" ry="4" fill="#F2748C" opacity="0.9" />
        <ellipse cx="94" cy="58.4" rx="5.5" ry="4" fill="#F2748C" opacity="0.9" />
      </g>
      <g className="an-lean">
        <g transform="rotate(9 34 62)">
          <ellipse cx="26.8" cy="97.8" rx="4.9" ry="3.6" fill="#3D2137" stroke="#3D2137" strokeWidth="4.2" />
          <ellipse cx="41.2" cy="97.8" rx="4.9" ry="3.6" fill="#3D2137" stroke="#3D2137" strokeWidth="4.2" />
          <ellipse cx="34" cy="83.6" rx="14.4" ry="16.6" fill="#FFFDFC" stroke="#3D2137" strokeWidth="4.2" />
          <circle cx="20.3" cy="44.3" r="6.5" fill="#3D2137" stroke="#3D2137" strokeWidth="4.2" />
          <circle cx="47.7" cy="44.3" r="6.5" fill="#3D2137" stroke="#3D2137" strokeWidth="4.2" />
          <circle cx="34" cy="58" r="18" fill="#FFFDFC" stroke="#3D2137" strokeWidth="4.2" />
          <ellipse cx="25.9" cy="60" rx="6.3" ry="7.7" fill="#3D2137" transform="rotate(-26 25.9 60)" />
          <ellipse cx="42.1" cy="60" rx="6.3" ry="7.7" fill="#3D2137" transform="rotate(26 42.1 60)" />
          <path d="M21.3 59.6 q4.6 -7 9.3 0" stroke="#FFF7F2" strokeWidth="3.6" fill="none" strokeLinecap="round" />
          <path d="M37.5 59.6 q4.6 -7 9.3 0" stroke="#FFF7F2" strokeWidth="3.6" fill="none" strokeLinecap="round" />
          <path d="M32.6 64.5 q1.4 -2.4 2.9 0 q-0.3 2.2 -1.4 2.2 q-1.2 0 -1.4 -2.2Z" fill="#3D2137" />
          <ellipse cx="34" cy="68.8" rx="2.3" ry="2.9" fill="#7A2E44" stroke="#3D2137" strokeWidth="3" />
          <ellipse cx="21.4" cy="67.4" rx="3.8" ry="2.8" fill="#FF9FB0" opacity="0.9" />
          <ellipse cx="46.6" cy="67.4" rx="3.8" ry="2.8" fill="#FF9FB0" opacity="0.9" />
        </g>
        <g transform="rotate(-16 63 58)">
          <ellipse cx="63" cy="58" rx="6.6" ry="5.2" fill="#FFD9E2" stroke="#3D2137" strokeWidth="3.0" />
          <path d="M58.4 58 h9.2" stroke="#3D2137" strokeWidth="2.0" strokeLinecap="round" />
        </g>
      </g>
      <g className="an-bob">
        <path d="M104 24.1 C101.4 21.7 99.5 19.8 99.5 18.3 C99.5 16.4 101.8 15.6 102.9 17 C103.4 17.7 103.7 18 104 18.2 C104.3 18 104.6 17.7 105.1 17 C106.2 15.6 108.5 16.4 108.5 18.3 C108.5 19.8 106.6 21.7 104 24.1 Z" fill="#E85D75" stroke="#3D2137" strokeWidth="3.2" strokeLinejoin="round" />
      </g>
      <g className="an-bob an-d2">
        <path d="M94 8.8 C92.2 7.2 90.9 5.9 90.9 4.8 C90.9 3.5 92.5 2.9 93.2 3.9 C93.6 4.4 93.8 4.6 94 4.8 C94.2 4.6 94.4 4.4 94.8 3.9 C95.5 2.9 97.1 3.5 97.1 4.8 C97.1 5.9 95.8 7.2 94 8.8 Z" fill="#E85D75" stroke="#3D2137" strokeWidth="3.2" strokeLinejoin="round" />
      </g>
    </Board>
  );
}

/* Head pat — mochi-bao/head-pat */
export function MochiBaoHeadPat(props) {
  return (
    <Board {...props}>
      <g className="an-melt">
        <ellipse cx="30" cy="106.2" rx="5.4" ry="4" fill="#3D2137" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="46" cy="106.2" rx="5.4" ry="4" fill="#3D2137" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="38" cy="90.4" rx="16" ry="18.4" fill="#FFFDFC" stroke="#3D2137" strokeWidth="4.2" />
        <circle cx="22.8" cy="47.8" r="7.2" fill="#3D2137" stroke="#3D2137" strokeWidth="4.2" />
        <circle cx="53.2" cy="47.8" r="7.2" fill="#3D2137" stroke="#3D2137" strokeWidth="4.2" />
        <circle cx="38" cy="62" r="20" fill="#FFFDFC" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="29" cy="64.2" rx="7" ry="8.6" fill="#3D2137" transform="rotate(-26 29 64.2)" />
        <ellipse cx="47" cy="64.2" rx="7" ry="8.6" fill="#3D2137" transform="rotate(26 47 64.2)" />
        <path d="M23.8 63.8 q5.2 -7.7 10.3 0" stroke="#FFF7F2" strokeWidth="3.6" fill="none" strokeLinecap="round" />
        <path d="M41.8 63.8 q5.2 -7.7 10.3 0" stroke="#FFF7F2" strokeWidth="3.6" fill="none" strokeLinecap="round" />
        <path d="M36.4 69.2 q1.6 -2.4 3.2 0 q-0.3 2.5 -1.6 2.5 q-1.3 0 -1.6 -2.5Z" fill="#3D2137" />
        <path d="M35 74 q3 3.4 6 0" stroke="#3D2137" strokeWidth="3.2" fill="none" strokeLinecap="round" />
        <ellipse cx="24" cy="72.4" rx="4.2" ry="3.1" fill="#FF9FB0" opacity="0.9" />
        <ellipse cx="52" cy="72.4" rx="4.2" ry="3.1" fill="#FF9FB0" opacity="0.9" />
      </g>
      <ellipse cx="85.2" cy="91.6" rx="4.6" ry="3.4" fill="#3D2137" stroke="#3D2137" strokeWidth="4.2" />
      <ellipse cx="98.8" cy="91.6" rx="4.6" ry="3.4" fill="#3D2137" stroke="#3D2137" strokeWidth="4.2" />
      <ellipse cx="92" cy="78.1" rx="13.6" ry="15.6" fill="#FBEEDF" stroke="#3D2137" strokeWidth="4.2" />
      <circle cx="79.1" cy="41.1" r="6.1" fill="#3D2137" stroke="#3D2137" strokeWidth="4.2" />
      <circle cx="79.1" cy="41.7" r="2.8" fill="#FFC9D6" />
      <circle cx="104.9" cy="41.1" r="6.1" fill="#3D2137" stroke="#3D2137" strokeWidth="4.2" />
      <circle cx="104.9" cy="41.7" r="2.8" fill="#FFC9D6" />
      <circle cx="92" cy="54" r="17" fill="#FBEEDF" stroke="#3D2137" strokeWidth="4.2" />
      <path d="M90.6 37.2 c-1.2 -4.4 3.4 -5.8 5.4 -2.8" stroke="#3D2137" strokeWidth="4.6" strokeLinecap="round" fill="none" />
      <ellipse cx="92" cy="62.2" rx="5.8" ry="4.4" fill="#FFF9F2" />
      <ellipse cx="84.3" cy="55.9" rx="6.5" ry="6.5" fill="#3D2137" transform="rotate(-6 84.3 55.9)" />
      <ellipse cx="99.7" cy="55.9" rx="6.5" ry="6.5" fill="#3D2137" transform="rotate(6 99.7 55.9)" />
      <path d="M80 55.5 q4.4 -6.6 8.8 0" stroke="#FFF7F2" strokeWidth="3.6" fill="none" strokeLinecap="round" />
      <path d="M95.3 55.5 q4.4 -6.6 8.8 0" stroke="#FFF7F2" strokeWidth="3.6" fill="none" strokeLinecap="round" />
      <path d="M90.6 60.1 q1.4 -2.4 2.7 0 q-0.3 2.1 -1.4 2.1 q-1.1 0 -1.4 -2.1Z" fill="#3D2137" />
      <path d="M89.5 64.2 q2.5 2.9 5.1 0" stroke="#3D2137" strokeWidth="3.2" fill="none" strokeLinecap="round" />
      <ellipse cx="80.1" cy="62.8" rx="3.6" ry="2.6" fill="#F2748C" opacity="0.9" />
      <ellipse cx="103.9" cy="62.8" rx="3.6" ry="2.6" fill="#F2748C" opacity="0.9" />
      <g className="an-pat">
        <path d="M80 70 C72 58 60 46 50 42" stroke="#3D2137" strokeWidth="10.2" strokeLinecap="round" fill="none" />
        <path d="M80 70 C72 58 60 46 50 42" stroke="#3D2137" strokeWidth="5" strokeLinecap="round" fill="none" />
        <g transform="rotate(-32 45 40)">
          <ellipse cx="45" cy="40" rx="8.6" ry="5.4" fill="#3D2137" stroke="#3D2137" strokeWidth="4.2" />
          <circle cx="40.1" cy="42.4" r="1.9" fill="#FFC9D6" />
          <circle cx="45" cy="43.1" r="1.9" fill="#FFC9D6" />
          <circle cx="49.9" cy="42.4" r="1.9" fill="#FFC9D6" />
        </g>
      </g>
      <g className="an-twinkle">
        <path d="M8 37.8 q0.8 2.6 4.2 4.2 q-2.6 0.8 -4.2 4.2 q-0.8 -2.6 -4.2 -4.2 q2.6 -0.8 4.2 -4.2Z" fill="#F2B880" opacity="1" />
      </g>
      <g className="an-twinkle an-d2">
        <path d="M66 18.6 q0.6 2.1 3.4 3.4 q-2.1 0.6 -3.4 3.4 q-0.6 -2.1 -3.4 -3.4 q2.1 -0.6 3.4 -3.4Z" fill="#F2B880" opacity="1" />
      </g>
    </Board>
  );
}

/* Forgive me? — mochi-bao/forgive-sign */
export function MochiBaoForgiveSign(props) {
  return (
    <Board {...props}>
      <g className="an-tilt">
        <ellipse cx="50.8" cy="90.9" rx="6.3" ry="4.7" fill="#3D2137" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="69.2" cy="90.9" rx="6.3" ry="4.7" fill="#3D2137" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="60" cy="72.7" rx="18.4" ry="21.2" fill="#FBEEDF" stroke="#3D2137" strokeWidth="4.2" />
        <circle cx="42.5" cy="22.3" r="8.3" fill="#3D2137" stroke="#3D2137" strokeWidth="4.2" />
        <circle cx="42.5" cy="23.1" r="3.8" fill="#FFC9D6" />
        <circle cx="77.5" cy="22.3" r="8.3" fill="#3D2137" stroke="#3D2137" strokeWidth="4.2" />
        <circle cx="77.5" cy="23.1" r="3.8" fill="#FFC9D6" />
        <circle cx="60" cy="40" r="23" fill="#FBEEDF" stroke="#3D2137" strokeWidth="4.2" />
        <path d="M58.2 17.2 c-1.2 -4.4 3.4 -5.8 5.4 -2.8" stroke="#3D2137" strokeWidth="4.6" strokeLinecap="round" fill="none" />
        <ellipse cx="60" cy="51" rx="7.8" ry="6" fill="#FFF9F2" />
        <ellipse cx="49.6" cy="42.5" rx="8.7" ry="8.7" fill="#3D2137" transform="rotate(-6 49.6 42.5)" />
        <ellipse cx="70.3" cy="42.5" rx="8.7" ry="8.7" fill="#3D2137" transform="rotate(6 70.3 42.5)" />
        <ellipse cx="49.6" cy="42.1" rx="7.5" ry="8.5" fill="#FFF7F2" />
        <ellipse cx="49.6" cy="42.5" rx="5.2" ry="5.9" fill="#3D2137" />
        <circle cx="47.9" cy="40.4" r="2.4" fill="#FFFFFF" />
        <circle cx="51.4" cy="44.3" r="1.2" fill="#FFFFFF" opacity=".92" />
        <ellipse cx="70.3" cy="42.1" rx="7.5" ry="8.5" fill="#FFF7F2" />
        <ellipse cx="70.3" cy="42.5" rx="5.2" ry="5.9" fill="#3D2137" />
        <circle cx="68.6" cy="40.4" r="2.4" fill="#FFFFFF" />
        <circle cx="72.1" cy="44.3" r="1.2" fill="#FFFFFF" opacity=".92" />
        <path d="M58.2 48.3 q1.8 -2.4 3.7 0 q-0.4 2.9 -1.8 2.9 q-1.5 0 -1.8 -2.9Z" fill="#3D2137" />
        <path d="M54.9 53.8 q1.3 -2.2 2.5 0 q1.3 2.2 2.5 0 q1.3 -2.2 2.5 0 q1.3 2.2 2.5 0" stroke="#3D2137" strokeWidth="3" fill="none" strokeLinecap="round" />
        <ellipse cx="43.9" cy="52" rx="4.8" ry="3.6" fill="#F2748C" opacity="0.9" />
        <ellipse cx="76.1" cy="52" rx="4.8" ry="3.6" fill="#F2748C" opacity="0.9" />
        <path d="M44.2 66.3 Q39.4 69.9 27 72" stroke="#3D2137" strokeWidth="11.2" strokeLinecap="round" fill="none" />
        <path d="M44.2 66.3 Q39.4 69.9 27 72" stroke="#3D2137" strokeWidth="5.4" strokeLinecap="round" fill="none" />
        <path d="M75.8 66.3 Q86.6 69.9 93 72" stroke="#3D2137" strokeWidth="11.2" strokeLinecap="round" fill="none" />
        <path d="M75.8 66.3 Q86.6 69.9 93 72" stroke="#3D2137" strokeWidth="5.4" strokeLinecap="round" fill="none" />
        <rect x="19" y="68" width="82" height="32" rx="11" fill="#FFF7F2" stroke="#3D2137" strokeWidth="4.2" />
        <text x="60" y="89.1" textAnchor="middle" className="hand" fontSize="11.0" textLength="64.0" lengthAdjust="spacingAndGlyphs" fill="#E85D75">forgive me?</text>
        <ellipse cx="27" cy="67" rx="6.5" ry="5.6" fill="#3D2137" stroke="#3D2137" strokeWidth="3.4" transform="rotate(-18 27 67)" />
        <ellipse cx="93" cy="67" rx="6.5" ry="5.6" fill="#3D2137" stroke="#3D2137" strokeWidth="3.4" transform="rotate(18 93 67)" />
      </g>
    </Board>
  );
}

/* Sulk & rain — mochi-bao/sulk-rain */
export function MochiBaoSulkRain(props) {
  return (
    <Board {...props}>
      <g className="an-cloud">
        <path d="M20.1 17a8.4 8.4 0 0 1 14.3 -4.2 8 8 0 0 1 12.6 3.4 7.1 7.1 0 0 1 -1.7 13.4H23.4 a7.6 7.6 0 0 1 -3.4 -12.6Z" fill="#D5CDE6" stroke="#3D2137" strokeWidth="4.2" strokeLinejoin="round" />
      </g>
      <g className="an-rain">
        <path d="M23 34 v9" stroke="#BFD6F5" strokeWidth="4.6" strokeLinecap="round" />
      </g>
      <g className="an-rain an-d2">
        <path d="M31 34 v9" stroke="#BFD6F5" strokeWidth="4.6" strokeLinecap="round" />
      </g>
      <g className="an-rain an-d3">
        <path d="M39 34 v9" stroke="#BFD6F5" strokeWidth="4.6" strokeLinecap="round" />
      </g>
      <g transform="rotate(-6 31 84)">
        <ellipse cx="24.2" cy="103.6" rx="4.6" ry="3.4" fill="#3D2137" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="37.8" cy="103.6" rx="4.6" ry="3.4" fill="#3D2137" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="31" cy="90.1" rx="13.6" ry="15.6" fill="#FFFDFC" stroke="#3D2137" strokeWidth="4.2" />
        <circle cx="18.1" cy="55" r="6.1" fill="#3D2137" stroke="#3D2137" strokeWidth="4.2" />
        <circle cx="43.9" cy="55" r="6.1" fill="#3D2137" stroke="#3D2137" strokeWidth="4.2" />
        <circle cx="31" cy="66" r="17" fill="#FFFDFC" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="23.4" cy="67.9" rx="5.9" ry="7.3" fill="#3D2137" transform="rotate(-26 23.4 67.9)" />
        <ellipse cx="38.6" cy="67.9" rx="5.9" ry="7.3" fill="#3D2137" transform="rotate(26 38.6 67.9)" />
        <path d="M19.4 67.5 h7.9" stroke="#FFF7F2" strokeWidth="3.6" fill="none" strokeLinecap="round" />
        <path d="M34.7 67.5 h7.9" stroke="#FFF7F2" strokeWidth="3.6" fill="none" strokeLinecap="round" />
        <path d="M29.6 72.1 q1.4 -2.4 2.7 0 q-0.3 2.1 -1.4 2.1 q-1.1 0 -1.4 -2.1Z" fill="#3D2137" />
        <path d="M28.4 77 q2.5 -2.7 5.1 0" stroke="#3D2137" strokeWidth="3.4" fill="none" strokeLinecap="round" />
      </g>
      <ellipse cx="81.2" cy="101.6" rx="4.6" ry="3.4" fill="#3D2137" stroke="#3D2137" strokeWidth="4.2" />
      <ellipse cx="94.8" cy="101.6" rx="4.6" ry="3.4" fill="#3D2137" stroke="#3D2137" strokeWidth="4.2" />
      <ellipse cx="88" cy="88.1" rx="13.6" ry="15.6" fill="#FBEEDF" stroke="#3D2137" strokeWidth="4.2" />
      <circle cx="75.1" cy="52.1" r="6.1" fill="#3D2137" stroke="#3D2137" strokeWidth="4.2" />
      <circle cx="75.1" cy="52.7" r="2.8" fill="#FFC9D6" />
      <circle cx="100.9" cy="52.1" r="6.1" fill="#3D2137" stroke="#3D2137" strokeWidth="4.2" />
      <circle cx="100.9" cy="52.7" r="2.8" fill="#FFC9D6" />
      <circle cx="88" cy="64" r="17" fill="#FBEEDF" stroke="#3D2137" strokeWidth="4.2" />
      <path d="M86.6 47.2 c-1.2 -4.4 3.4 -5.8 5.4 -2.8" stroke="#3D2137" strokeWidth="4.6" strokeLinecap="round" fill="none" />
      <ellipse cx="88" cy="72.2" rx="5.8" ry="4.4" fill="#FFF9F2" />
      <ellipse cx="80.3" cy="65.9" rx="6.5" ry="6.5" fill="#3D2137" transform="rotate(-6 80.3 65.9)" />
      <ellipse cx="95.7" cy="65.9" rx="6.5" ry="6.5" fill="#3D2137" transform="rotate(6 95.7 65.9)" />
      <path d="M76 67.1 q4.4 5.7 8.8 0" stroke="#FFF7F2" strokeWidth="3.6" fill="none" strokeLinecap="round" />
      <path d="M91.3 67.1 q4.4 5.7 8.8 0" stroke="#FFF7F2" strokeWidth="3.6" fill="none" strokeLinecap="round" />
      <path d="M86.6 70.1 q1.4 -2.4 2.7 0 q-0.3 2.1 -1.4 2.1 q-1.1 0 -1.4 -2.1Z" fill="#3D2137" />
      <path d="M85.8 74.2 h4.4" stroke="#3D2137" strokeWidth="3.6" fill="none" strokeLinecap="round" />
      <ellipse cx="76.1" cy="72.8" rx="3.6" ry="2.6" fill="#F2748C" opacity="0.9" />
      <ellipse cx="99.9" cy="72.8" rx="3.6" ry="2.6" fill="#F2748C" opacity="0.9" />
      <path d="M72 92 C66 90 62 91 58 92" stroke="#3D2137" strokeWidth="10.4" strokeLinecap="round" fill="none" />
      <path d="M72 92 C66 90 62 91 58 92" stroke="#3D2137" strokeWidth="5.2" strokeLinecap="round" fill="none" />
      <g transform="rotate(12 53 92)">
        <ellipse cx="53" cy="92" rx="7.8" ry="5.2" fill="#3D2137" stroke="#3D2137" strokeWidth="4.2" />
        <circle cx="48.6" cy="94.3" r="1.9" fill="#FFC9D6" />
        <circle cx="53" cy="95" r="1.9" fill="#FFC9D6" />
        <circle cx="57.4" cy="94.3" r="1.9" fill="#FFC9D6" />
      </g>
    </Board>
  );
}

/* Made up — mochi-bao/made-up */
export function MochiBaoMadeUp(props) {
  return (
    <Board {...props}>
      <g className="an-cheer">
        <ellipse cx="28.4" cy="94" rx="5.2" ry="3.8" fill="#3D2137" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="43.6" cy="94" rx="5.2" ry="3.8" fill="#3D2137" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="36" cy="79" rx="15.2" ry="17.5" fill="#FFFDFC" stroke="#3D2137" strokeWidth="4.2" />
        <circle cx="21.6" cy="36.4" r="6.8" fill="#3D2137" stroke="#3D2137" strokeWidth="4.2" />
        <circle cx="50.4" cy="36.4" r="6.8" fill="#3D2137" stroke="#3D2137" strokeWidth="4.2" />
        <circle cx="36" cy="52" r="19" fill="#FFFDFC" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="27.4" cy="54.1" rx="6.6" ry="8.2" fill="#3D2137" transform="rotate(-26 27.4 54.1)" />
        <ellipse cx="44.5" cy="54.1" rx="6.6" ry="8.2" fill="#3D2137" transform="rotate(26 44.5 54.1)" />
        <path d="M22.5 53.7 q4.9 -7.4 9.8 0" stroke="#FFF7F2" strokeWidth="3.6" fill="none" strokeLinecap="round" />
        <path d="M39.6 53.7 q4.9 -7.4 9.8 0" stroke="#FFF7F2" strokeWidth="3.6" fill="none" strokeLinecap="round" />
        <path d="M34.5 58.8 q1.5 -2.4 3 0 q-0.3 2.4 -1.5 2.4 q-1.2 0 -1.5 -2.4Z" fill="#3D2137" />
        <path d="M31.6 62.4 q4.4 -2.6 8.7 0 q-0.9 5.7 -4.4 5.7 q-3.5 0 -4.4 -5.7Z" fill="#7A2E44" stroke="#3D2137" strokeWidth="3.2" strokeLinejoin="round" />
        <ellipse cx="22.7" cy="61.9" rx="4" ry="2.9" fill="#FF9FB0" opacity="0.9" />
        <ellipse cx="49.3" cy="61.9" rx="4" ry="2.9" fill="#FF9FB0" opacity="0.9" />
      </g>
      <g className="an-cheer an-d2">
        <ellipse cx="76.4" cy="96" rx="5.2" ry="3.8" fill="#3D2137" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="91.6" cy="96" rx="5.2" ry="3.8" fill="#3D2137" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="84" cy="81" rx="15.2" ry="17.5" fill="#FBEEDF" stroke="#3D2137" strokeWidth="4.2" />
        <circle cx="69.6" cy="38.4" r="6.8" fill="#3D2137" stroke="#3D2137" strokeWidth="4.2" />
        <circle cx="69.6" cy="39.1" r="3.1" fill="#FFC9D6" />
        <circle cx="98.4" cy="38.4" r="6.8" fill="#3D2137" stroke="#3D2137" strokeWidth="4.2" />
        <circle cx="98.4" cy="39.1" r="3.1" fill="#FFC9D6" />
        <circle cx="84" cy="54" r="19" fill="#FBEEDF" stroke="#3D2137" strokeWidth="4.2" />
        <path d="M82.5 35.2 c-1.2 -4.4 3.4 -5.8 5.4 -2.8" stroke="#3D2137" strokeWidth="4.6" strokeLinecap="round" fill="none" />
        <ellipse cx="84" cy="63.1" rx="6.5" ry="4.9" fill="#FFF9F2" />
        <ellipse cx="75.5" cy="56.1" rx="7.2" ry="7.2" fill="#3D2137" transform="rotate(-6 75.5 56.1)" />
        <ellipse cx="92.5" cy="56.1" rx="7.2" ry="7.2" fill="#3D2137" transform="rotate(6 92.5 56.1)" />
        <path d="M70.5 55.7 q4.9 -7.4 9.8 0" stroke="#FFF7F2" strokeWidth="3.6" fill="none" strokeLinecap="round" />
        <path d="M87.6 55.7 q4.9 -7.4 9.8 0" stroke="#FFF7F2" strokeWidth="3.6" fill="none" strokeLinecap="round" />
        <path d="M82.5 60.8 q1.5 -2.4 3 0 q-0.3 2.4 -1.5 2.4 q-1.2 0 -1.5 -2.4Z" fill="#3D2137" />
        <path d="M79.6 64.5 q4.4 -2.6 8.7 0 q-0.9 5.7 -4.4 5.7 q-3.5 0 -4.4 -5.7Z" fill="#7A2E44" stroke="#3D2137" strokeWidth="3.2" strokeLinejoin="round" />
        <ellipse cx="70.7" cy="63.9" rx="4" ry="2.9" fill="#F2748C" opacity="0.9" />
        <ellipse cx="97.3" cy="63.9" rx="4" ry="2.9" fill="#F2748C" opacity="0.9" />
      </g>
      <path d="M46.6 86.3 C55.8 96.5 64.2 96.5 73.4 88.3" stroke="#3D2137" strokeWidth="11.6" strokeLinecap="round" fill="none" />
      <path d="M46.6 86.3 C55.8 96.5 64.2 96.5 73.4 88.3" stroke="#3D2137" strokeWidth="5.6" strokeLinecap="round" fill="none" />
      <g className="an-bob">
        <path d="M60 14.9 C56.9 12.1 54.5 9.8 54.5 7.9 C54.5 5.6 57.3 4.6 58.6 6.4 C59.3 7.2 59.7 7.5 60 7.8 C60.3 7.5 60.7 7.2 61.4 6.4 C62.7 4.6 65.5 5.6 65.5 7.9 C65.5 9.8 63.1 12.1 60 14.9 Z" fill="#E85D75" stroke="#3D2137" strokeWidth="3.2" strokeLinejoin="round" />
      </g>
      <g className="an-bob an-d2">
        <path d="M14 26.9 C12.2 25.2 10.7 23.9 10.7 22.8 C10.7 21.4 12.4 20.8 13.2 21.9 C13.6 22.3 13.8 22.5 14 22.7 C14.2 22.5 14.4 22.3 14.8 21.9 C15.6 20.8 17.3 21.4 17.3 22.8 C17.3 23.9 15.8 25.2 14 26.9 Z" fill="#E85D75" stroke="#3D2137" strokeWidth="3.2" strokeLinejoin="round" />
      </g>
      <g className="an-twinkle">
        <path d="M6 58.6 q0.6 2.1 3.4 3.4 q-2.1 0.6 -3.4 3.4 q-0.6 -2.1 -3.4 -3.4 q2.1 -0.6 3.4 -3.4Z" fill="#F2B880" opacity="1" />
      </g>
      <g className="an-twinkle an-d2">
        <path d="M114 63 q0.5 1.9 3 3 q-1.9 0.5 -3 3 q-0.5 -1.9 -3 -3 q1.9 -0.5 3 -3Z" fill="#F2B880" opacity="1" />
      </g>
    </Board>
  );
}

/* id -> component, ready for the registry in ./index.jsx */
export const COMPONENTS = {
  'mochi-bao/begging': MochiBaoBegging,
  'mochi-bao/waterfall-cry': MochiBaoWaterfallCry,
  'mochi-bao/big-hug': MochiBaoBigHug,
  'mochi-bao/flowers-shy': MochiBaoFlowersShy,
  'mochi-bao/pouty': MochiBaoPouty,
  'mochi-bao/cheek-kiss': MochiBaoCheekKiss,
  'mochi-bao/head-pat': MochiBaoHeadPat,
  'mochi-bao/forgive-sign': MochiBaoForgiveSign,
  'mochi-bao/sulk-rain': MochiBaoSulkRain,
  'mochi-bao/made-up': MochiBaoMadeUp,
};

export default COMPONENTS;
