/* eslint-disable */
'use client';

/**
 * Momo & Pip 🐻 — Bear and bunny — the original couple from sheet one.
 *
 * AUTO-GENERATED by tools/stickers/gen_pack_jsx.py. Do not edit by hand:
 * re-run the generator instead, or the drawings drift from the sheets.
 *
 * Ten poses, one 120x120 board each, house palette and plum ink. The
 * `an-*` classes are the little motion loops; they live in globals.css and
 * switch themselves off under prefers-reduced-motion.
 */

import { Board } from './board';

/* Begging — momo-pip/begging */
export function MomoPipBegging(props) {
  return (
    <Board {...props}>
      <ellipse cx="38" cy="104" rx="14" ry="8.5" fill="#F9B0C0" stroke="#3D2137" strokeWidth="4.2" />
      <ellipse cx="82" cy="104" rx="14" ry="8.5" fill="#F9B0C0" stroke="#3D2137" strokeWidth="4.2" />
      <ellipse cx="60" cy="90" rx="25" ry="18" fill="#F9B0C0" stroke="#3D2137" strokeWidth="4.2" />
      <path d="M42 94C40 86 46 80 53 78" stroke="#3D2137" strokeWidth="17.0" strokeLinecap="round" fill="none" />
      <path d="M42 94C40 86 46 80 53 78" stroke="#F9B0C0" strokeWidth="8.6" strokeLinecap="round" fill="none" />
      <path d="M78 94c2-8-4-14-11-16" stroke="#3D2137" strokeWidth="17.0" strokeLinecap="round" fill="none" />
      <path d="M78 94c2-8-4-14-11-16" stroke="#F9B0C0" strokeWidth="8.6" strokeLinecap="round" fill="none" />
      <circle cx="54" cy="76" r="8" fill="#F9B0C0" stroke="#3D2137" strokeWidth="4.2" />
      <circle cx="66" cy="76" r="8" fill="#F9B0C0" stroke="#3D2137" strokeWidth="4.2" />
      <g className="an-plead">
        <circle cx="39.1" cy="23.5" r="12.8" fill="#F9B0C0" stroke="#3D2137" strokeWidth="4.2" />
        <circle cx="39.1" cy="25.1" r="5.6" fill="#EF8FA4" />
        <circle cx="80.9" cy="23.5" r="12.8" fill="#F9B0C0" stroke="#3D2137" strokeWidth="4.2" />
        <circle cx="80.9" cy="25.1" r="5.6" fill="#EF8FA4" />
        <circle cx="60.0" cy="45.0" r="29.0" fill="#F9B0C0" stroke="#3D2137" strokeWidth="4.2" />
        <path d="M31.5 29.6q5.5 6.8 11.0 0" stroke="#3D2137" strokeWidth="3" fill="none" strokeLinecap="round" />
        <path d="M67.5 29.6q5.5 6.8 11.0 0" stroke="#3D2137" strokeWidth="3" fill="none" strokeLinecap="round" />
        <g transform="rotate(-6 45.0 46.0)">
          <ellipse cx="45.0" cy="46.0" rx="9.2" ry="10.5" fill="#3D2137" />
          <ellipse cx="45.0" cy="50.4" rx="7.3" ry="4.7" fill="#BFD6F5" opacity="0.85" />
          <circle cx="41.6" cy="42.2" r="3.6" fill="#FFFFFF" />
          <circle cx="48.1" cy="47.0" r="1.8" fill="#FFFFFF" />
        </g>
        <g transform="rotate(6 75.0 46.0)">
          <ellipse cx="75.0" cy="46.0" rx="9.2" ry="10.5" fill="#3D2137" />
          <ellipse cx="75.0" cy="50.4" rx="7.3" ry="4.7" fill="#BFD6F5" opacity="0.85" />
          <circle cx="71.6" cy="42.2" r="3.6" fill="#FFFFFF" />
          <circle cx="78.2" cy="47.0" r="1.8" fill="#FFFFFF" />
        </g>
        <ellipse cx="60.0" cy="57.0" rx="3.1" ry="2.3" fill="#3D2137" />
        <path d="M54.0 63.0q1.5 -2.7 3.0 0q1.5 2.7 3.0 0q1.5 -2.7 3.0 0q1.5 2.7 3.0 0" stroke="#3D2137" strokeWidth="3.2" fill="none" strokeLinecap="round" />
        <ellipse cx="30.0" cy="57.0" rx="6.4" ry="4.4" fill="#FF9FB0" opacity="0.85" />
        <ellipse cx="90.0" cy="57.0" rx="6.4" ry="4.4" fill="#FF9FB0" opacity="0.85" />
      </g>
      <g className="an-teardrop">
        <path d="M31.0 55.0c2.6 4.2 4.0 6.0 4.0 7.8a4.0 4.0 0 0 1 -7.9 0c0 -1.8 1.3 -3.6 4.0 -7.8Z" fill="#BFD6F5" stroke="#3D2137" strokeWidth="1.8" strokeLinejoin="round" />
      </g>
      <g className="an-teardrop an-d2">
        <path d="M83.0 55.0c2.6 4.2 4.0 6.0 4.0 7.8a4.0 4.0 0 0 1 -7.9 0c0 -1.8 1.3 -3.6 4.0 -7.8Z" fill="#BFD6F5" stroke="#3D2137" strokeWidth="1.8" strokeLinejoin="round" />
      </g>
    </Board>
  );
}

/* Waterfall cry — momo-pip/waterfall-cry */
export function MomoPipWaterfallCry(props) {
  return (
    <Board {...props}>
      <path d="M36 88C26 82 22 72 24 62" stroke="#3D2137" strokeWidth="17.0" strokeLinecap="round" fill="none" />
      <path d="M36 88C26 82 22 72 24 62" stroke="#FFF1E2" strokeWidth="8.6" strokeLinecap="round" fill="none" />
      <path d="M84 88c10-6 14-16 12-26" stroke="#3D2137" strokeWidth="17.0" strokeLinecap="round" fill="none" />
      <path d="M84 88c10-6 14-16 12-26" stroke="#FFF1E2" strokeWidth="8.6" strokeLinecap="round" fill="none" />
      <ellipse cx="60" cy="92" rx="23" ry="17" fill="#FFF1E2" stroke="#3D2137" strokeWidth="4.2" />
      <g className="an-sob">
        <path d="M49.9 28.2C47.5 11.9 31.9 6.6 23.4 21.4" stroke="#3D2137" strokeWidth="17.8" strokeLinecap="round" fill="none" />
        <path d="M49.9 28.2C47.5 11.9 31.9 6.6 23.4 21.4" stroke="#FFF1E2" strokeWidth="9.4" strokeLinecap="round" fill="none" />
        <path d="M70.1 28.2C72.5 11.9 88.1 6.6 96.6 21.4" stroke="#3D2137" strokeWidth="17.8" strokeLinecap="round" fill="none" />
        <path d="M70.1 28.2C72.5 11.9 88.1 6.6 96.6 21.4" stroke="#FFF1E2" strokeWidth="9.4" strokeLinecap="round" fill="none" />
        <path d="M49.9 27.3L45.6 14.3" stroke="#F6D9BE" strokeWidth="4" strokeLinecap="round" fill="none" />
        <path d="M70.1 27.3L74.4 14.3" stroke="#F6D9BE" strokeWidth="4" strokeLinecap="round" fill="none" />
        <circle cx="60.0" cy="46.0" r="24.0" fill="#FFF1E2" stroke="#3D2137" strokeWidth="4.2" />
        <path d="M29.5 47.9q6.5 -11.0 13.0 0" stroke="#3D2137" strokeWidth="4" fill="none" strokeLinecap="round" />
        <path d="M64.5 47.9q6.5 -11.0 13.0 0" stroke="#3D2137" strokeWidth="4" fill="none" strokeLinecap="round" />
        <path d="M50.5 58.0q9.5 -4.2 19.0 0q-1.9 15.0 -9.5 15.0q-7.6 0 -9.5 -15.0Z" fill="#7A2E44" stroke="#3D2137" strokeWidth="3.2" strokeLinejoin="round" />
        <ellipse cx="30.0" cy="56.0" rx="6.4" ry="4.4" fill="#FF9FB0" opacity="0.85" />
        <ellipse cx="90.0" cy="56.0" rx="6.4" ry="4.4" fill="#FF9FB0" opacity="0.85" />
      </g>
      <g className="an-stream">
        <path d="M36 54c-7 18-11 40-8 62h17c-3-22-2-44 2-62Z" fill="#BFD6F5" stroke="#3D2137" strokeWidth="3.4" strokeLinejoin="round" />
        <path d="M84 54c7 18 11 40 8 62H75c3-22 2-44-2-62Z" fill="#BFD6F5" stroke="#3D2137" strokeWidth="3.4" strokeLinejoin="round" />
        <path d="M36 66c-3 14-4 30-3 42M84 66c3 14 4 30 3 42" stroke="#FFFFFF" strokeWidth="3" strokeLinecap="round" fill="none" opacity="0.6" />
      </g>
    </Board>
  );
}

/* Big hug — momo-pip/big-hug */
export function MomoPipBigHug(props) {
  return (
    <Board {...props}>
      <g className="an-squeeze">
        <path d="M90 92 100 89" stroke="#3D2137" strokeWidth="16.8" strokeLinecap="round" fill="none" />
        <path d="M90 92 100 89" stroke="#F9B0C0" strokeWidth="8.4" strokeLinecap="round" fill="none" />
        <ellipse cx="101" cy="88" rx="7.6" ry="6.4" fill="#F9B0C0" stroke="#3D2137" strokeWidth="3.8" transform="rotate(-16 101 88)" />
        <path d="M34 91 23 88" stroke="#3D2137" strokeWidth="16.8" strokeLinecap="round" fill="none" />
        <path d="M34 91 23 88" stroke="#FFF1E2" strokeWidth="8.4" strokeLinecap="round" fill="none" />
        <ellipse cx="22" cy="87" rx="7.6" ry="6.4" fill="#FFF1E2" stroke="#3D2137" strokeWidth="3.8" transform="rotate(16 22 87)" />
        <ellipse cx="44" cy="97" rx="22" ry="16" fill="#F9B0C0" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="80" cy="98" rx="20" ry="15" fill="#FFF1E2" stroke="#3D2137" strokeWidth="4.2" />
        <g transform="rotate(-10 41 50)">
          <circle cx="23.7" cy="32.2" r="10.6" fill="#F9B0C0" stroke="#3D2137" strokeWidth="4.2" />
          <circle cx="23.7" cy="33.5" r="4.6" fill="#EF8FA4" />
          <circle cx="58.3" cy="32.2" r="10.6" fill="#F9B0C0" stroke="#3D2137" strokeWidth="4.2" />
          <circle cx="58.3" cy="33.5" r="4.6" fill="#EF8FA4" />
          <circle cx="41.0" cy="50.0" r="24.0" fill="#F9B0C0" stroke="#3D2137" strokeWidth="4.2" />
          <path d="M25.2 52.7q4.8 -6.8 9.5 0" stroke="#3D2137" strokeWidth="3.6" fill="none" strokeLinecap="round" />
          <path d="M47.2 52.7q4.8 -6.8 9.5 0" stroke="#3D2137" strokeWidth="3.6" fill="none" strokeLinecap="round" />
          <path d="M37.0 59.0q4.0 5.0 8.0 0" stroke="#3D2137" strokeWidth="3.4" fill="none" strokeLinecap="round" />
          <ellipse cx="22.0" cy="58.0" rx="6.4" ry="4.4" fill="#FF9FB0" opacity="0.85" />
          <ellipse cx="60.0" cy="58.0" rx="6.4" ry="4.4" fill="#FF9FB0" opacity="0.85" />
        </g>
        <g transform="rotate(12 81 52)">
          <path d="M72.2 36.5C70.1 22.2 61.7 13.8 55.5 18.4" stroke="#3D2137" strokeWidth="17.8" strokeLinecap="round" fill="none" />
          <path d="M72.2 36.5C70.1 22.2 61.7 13.8 55.5 18.4" stroke="#FFF1E2" strokeWidth="9.4" strokeLinecap="round" fill="none" />
          <path d="M89.8 36.5C91.9 22.2 100.3 13.8 106.5 18.4" stroke="#3D2137" strokeWidth="17.8" strokeLinecap="round" fill="none" />
          <path d="M89.8 36.5C91.9 22.2 100.3 13.8 106.5 18.4" stroke="#FFF1E2" strokeWidth="9.4" strokeLinecap="round" fill="none" />
          <path d="M72.2 35.6L68.4 24.3" stroke="#F6D9BE" strokeWidth="4" strokeLinecap="round" fill="none" />
          <path d="M89.8 35.6L93.6 24.3" stroke="#F6D9BE" strokeWidth="4" strokeLinecap="round" fill="none" />
          <circle cx="81.0" cy="52.0" r="21.0" fill="#FFF1E2" stroke="#3D2137" strokeWidth="4.2" />
          <path d="M67.5 54.5q4.5 -6.5 9.0 0" stroke="#3D2137" strokeWidth="3.6" fill="none" strokeLinecap="round" />
          <path d="M86.5 54.5q4.5 -6.5 9.0 0" stroke="#3D2137" strokeWidth="3.6" fill="none" strokeLinecap="round" />
          <path d="M78.1 60.0q2.9 -2.6 5.8 0q-2.1 3.5 -2.9 3.5q-0.8 0 -2.9 -3.5Z" fill="#E85D75" />
          <path d="M81.0 63.5v2.1M81.0 65.6q-3.2 2.9 -4.8 0M81.0 65.6q3.2 2.9 4.8 0" stroke="#3D2137" strokeWidth="2.8" fill="none" strokeLinecap="round" />
          <ellipse cx="64.0" cy="60.0" rx="6.4" ry="4.4" fill="#FF9FB0" opacity="0.85" />
          <ellipse cx="99.0" cy="60.0" rx="6.4" ry="4.4" fill="#FF9FB0" opacity="0.85" />
        </g>
        <path d="M66 80C58 75 50 75 45 78" stroke="#3D2137" strokeWidth="16.6" strokeLinecap="round" fill="none" />
        <path d="M66 80C58 75 50 75 45 78" stroke="#FFF1E2" strokeWidth="8.2" strokeLinecap="round" fill="none" />
      </g>
      <g className="an-bob">
        <path d="M60.0 22.1c-5.2 -3.5 -7.0 -7.0 -4.6 -9.0c1.7 -1.5 3.7 -0.5 4.6 1.0c0.9 -1.5 2.9 -2.6 4.6 -1.0c2.3 2.0 0.6 5.5 -4.6 9.0Z" fill="#E85D75" stroke="#3D2137" strokeWidth="3.2" strokeLinejoin="round" />
      </g>
    </Board>
  );
}

/* Flowers, shy — momo-pip/flowers-shy */
export function MomoPipFlowersShy(props) {
  return (
    <Board {...props}>
      <g className="an-sway-s">
        <path d="M88 86 85 62" stroke="#A9C3A0" strokeWidth="4" strokeLinecap="round" fill="none" />
        <path d="M94 86 98 64" stroke="#A9C3A0" strokeWidth="4" strokeLinecap="round" fill="none" />
        <circle cx="83.0" cy="49.0" r="5.6" fill="#E85D75" stroke="#3D2137" strokeWidth="2.8" transform="rotate(0 83.0 56.0)" />
        <circle cx="83.0" cy="49.0" r="5.6" fill="#E85D75" stroke="#3D2137" strokeWidth="2.8" transform="rotate(72 83.0 56.0)" />
        <circle cx="83.0" cy="49.0" r="5.6" fill="#E85D75" stroke="#3D2137" strokeWidth="2.8" transform="rotate(144 83.0 56.0)" />
        <circle cx="83.0" cy="49.0" r="5.6" fill="#E85D75" stroke="#3D2137" strokeWidth="2.8" transform="rotate(216 83.0 56.0)" />
        <circle cx="83.0" cy="49.0" r="5.6" fill="#E85D75" stroke="#3D2137" strokeWidth="2.8" transform="rotate(288 83.0 56.0)" />
        <circle cx="83.0" cy="56.0" r="4.6" fill="#FFF7F2" stroke="#3D2137" strokeWidth="2.8" />
        <circle cx="99.0" cy="51.0" r="5.6" fill="#F2B880" stroke="#3D2137" strokeWidth="2.8" transform="rotate(0 99.0 58.0)" />
        <circle cx="99.0" cy="51.0" r="5.6" fill="#F2B880" stroke="#3D2137" strokeWidth="2.8" transform="rotate(72 99.0 58.0)" />
        <circle cx="99.0" cy="51.0" r="5.6" fill="#F2B880" stroke="#3D2137" strokeWidth="2.8" transform="rotate(144 99.0 58.0)" />
        <circle cx="99.0" cy="51.0" r="5.6" fill="#F2B880" stroke="#3D2137" strokeWidth="2.8" transform="rotate(216 99.0 58.0)" />
        <circle cx="99.0" cy="51.0" r="5.6" fill="#F2B880" stroke="#3D2137" strokeWidth="2.8" transform="rotate(288 99.0 58.0)" />
        <circle cx="99.0" cy="58.0" r="4.6" fill="#FFF7F2" stroke="#3D2137" strokeWidth="2.8" />
        <circle cx="91.0" cy="35.0" r="5.6" fill="#C9B3F0" stroke="#3D2137" strokeWidth="2.8" transform="rotate(0 91.0 42.0)" />
        <circle cx="91.0" cy="35.0" r="5.6" fill="#C9B3F0" stroke="#3D2137" strokeWidth="2.8" transform="rotate(72 91.0 42.0)" />
        <circle cx="91.0" cy="35.0" r="5.6" fill="#C9B3F0" stroke="#3D2137" strokeWidth="2.8" transform="rotate(144 91.0 42.0)" />
        <circle cx="91.0" cy="35.0" r="5.6" fill="#C9B3F0" stroke="#3D2137" strokeWidth="2.8" transform="rotate(216 91.0 42.0)" />
        <circle cx="91.0" cy="35.0" r="5.6" fill="#C9B3F0" stroke="#3D2137" strokeWidth="2.8" transform="rotate(288 91.0 42.0)" />
        <circle cx="91.0" cy="42.0" r="4.6" fill="#FFF7F2" stroke="#3D2137" strokeWidth="2.8" />
      </g>
      <ellipse cx="44" cy="94" rx="24" ry="18" fill="#F9B0C0" stroke="#3D2137" strokeWidth="4.2" />
      <path d="M60 92c10 0 18-2 22-6" stroke="#3D2137" strokeWidth="17.0" strokeLinecap="round" fill="none" />
      <path d="M60 92c10 0 18-2 22-6" stroke="#F9B0C0" strokeWidth="8.6" strokeLinecap="round" fill="none" />
      <path d="M28 90c-5 4-6 10-4 15" stroke="#3D2137" strokeWidth="17.0" strokeLinecap="round" fill="none" />
      <path d="M28 90c-5 4-6 10-4 15" stroke="#F9B0C0" strokeWidth="8.6" strokeLinecap="round" fill="none" />
      <g className="an-shy">
        <circle cx="26.0" cy="30.5" r="11.0" fill="#F9B0C0" stroke="#3D2137" strokeWidth="4.2" />
        <circle cx="26.0" cy="31.8" r="4.8" fill="#EF8FA4" />
        <circle cx="62.0" cy="30.5" r="11.0" fill="#F9B0C0" stroke="#3D2137" strokeWidth="4.2" />
        <circle cx="62.0" cy="31.8" r="4.8" fill="#EF8FA4" />
        <circle cx="44.0" cy="49.0" r="25.0" fill="#F9B0C0" stroke="#3D2137" strokeWidth="4.2" />
        <path d="M26.0 33.4q5.0 5.2 10.0 0" stroke="#3D2137" strokeWidth="3" fill="none" strokeLinecap="round" />
        <path d="M52.0 33.4q5.0 5.2 10.0 0" stroke="#3D2137" strokeWidth="3" fill="none" strokeLinecap="round" />
        <path d="M26.0 46.8q5.0 7.2 10.0 0" stroke="#3D2137" strokeWidth="3.6" fill="none" strokeLinecap="round" />
        <path d="M52.0 46.8q5.0 7.2 10.0 0" stroke="#3D2137" strokeWidth="3.6" fill="none" strokeLinecap="round" />
        <ellipse cx="44.0" cy="58.0" rx="2.9" ry="2.2" fill="#3D2137" />
        <path d="M40.5 64.0q3.5 4.3 7.0 0" stroke="#3D2137" strokeWidth="3.4" fill="none" strokeLinecap="round" />
        <ellipse cx="22.0" cy="59.0" rx="8.0" ry="5.8" fill="#FF9FB0" opacity="0.9" />
        <path d="M17.6 57.8l2.8 4.0M22.0 56.6l2.8 4.0M26.4 57.8l2.8 4.0" stroke="#E85D75" strokeWidth="1.8" strokeLinecap="round" opacity="0.55" />
        <ellipse cx="66.0" cy="59.0" rx="8.0" ry="5.8" fill="#FF9FB0" opacity="0.9" />
        <path d="M61.6 57.8l2.8 4.0M66.0 56.6l2.8 4.0M70.4 57.8l2.8 4.0" stroke="#E85D75" strokeWidth="1.8" strokeLinecap="round" opacity="0.55" />
      </g>
    </Board>
  );
}

/* Pouty — momo-pip/pouty */
export function MomoPipPouty(props) {
  return (
    <Board {...props}>
      <g className="an-steam">
        <path d="M94 32c6-4 3-10-2-12s-6-7-1-10" stroke="#D5CDE6" strokeWidth="5.4" strokeLinecap="round" fill="none" />
      </g>
      <g className="an-steam an-d2">
        <path d="M106 46c5-4 2-9-2-11" stroke="#D5CDE6" strokeWidth="4.6" strokeLinecap="round" fill="none" />
      </g>
      <ellipse cx="56" cy="96" rx="29" ry="20" fill="#FFF1E2" stroke="#3D2137" strokeWidth="4.2" />
      <path d="M36 80C46 86 60 90 72 91" stroke="#3D2137" strokeWidth="15.8" strokeLinecap="round" fill="none" />
      <path d="M36 80C46 86 60 90 72 91" stroke="#FFF1E2" strokeWidth="7.4" strokeLinecap="round" fill="none" />
      <path d="M76 80C66 86 52 90 40 91" stroke="#3D2137" strokeWidth="15.8" strokeLinecap="round" fill="none" />
      <path d="M76 80C66 86 52 90 40 91" stroke="#FFF1E2" strokeWidth="7.4" strokeLinecap="round" fill="none" />
      <ellipse cx="73" cy="91" rx="6.8" ry="5.8" fill="#FFF1E2" stroke="#3D2137" strokeWidth="3.4" />
      <ellipse cx="39" cy="91" rx="6.8" ry="5.8" fill="#FFF1E2" stroke="#3D2137" strokeWidth="3.4" />
      <g className="an-huff">
        <path d="M45.5 26.5C43.0 9.5 30.8 1.1 22.9 10.1" stroke="#3D2137" strokeWidth="17.8" strokeLinecap="round" fill="none" />
        <path d="M45.5 26.5C43.0 9.5 30.8 1.1 22.9 10.1" stroke="#FFF1E2" strokeWidth="9.4" strokeLinecap="round" fill="none" />
        <path d="M66.5 26.5C69.0 9.5 81.2 1.1 89.2 10.1" stroke="#3D2137" strokeWidth="17.8" strokeLinecap="round" fill="none" />
        <path d="M66.5 26.5C69.0 9.5 81.2 1.1 89.2 10.1" stroke="#FFF1E2" strokeWidth="9.4" strokeLinecap="round" fill="none" />
        <path d="M45.5 25.5L41.0 12.0" stroke="#F6D9BE" strokeWidth="4" strokeLinecap="round" fill="none" />
        <path d="M66.5 25.5L71.0 12.0" stroke="#F6D9BE" strokeWidth="4" strokeLinecap="round" fill="none" />
        <circle cx="56.0" cy="45.0" r="25.0" fill="#FFF1E2" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="29" cy="54" rx="10.5" ry="9.5" fill="#FFF1E2" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="83" cy="54" rx="10.5" ry="9.5" fill="#FFF1E2" stroke="#3D2137" strokeWidth="4.2" />
        <path d="M30.5 29.6q5.5 6.8 11.0 0" stroke="#3D2137" strokeWidth="3" fill="none" strokeLinecap="round" />
        <path d="M58.5 29.6q5.5 6.8 11.0 0" stroke="#3D2137" strokeWidth="3" fill="none" strokeLinecap="round" />
        <path d="M30.5 42.6q5.5 7.9 11.0 0" stroke="#3D2137" strokeWidth="3.6" fill="none" strokeLinecap="round" />
        <path d="M58.5 42.6q5.5 7.9 11.0 0" stroke="#3D2137" strokeWidth="3.6" fill="none" strokeLinecap="round" />
        <path d="M48 60q4-6 8 0q4 6 8 0" stroke="#3D2137" strokeWidth="3.6" fill="none" strokeLinecap="round" />
        <ellipse cx="29.0" cy="56.0" rx="7.0" ry="5.0" fill="#FF9FB0" opacity="0.85" />
        <ellipse cx="83.0" cy="56.0" rx="7.0" ry="5.0" fill="#FF9FB0" opacity="0.85" />
      </g>
    </Board>
  );
}

/* Cheek kiss — momo-pip/cheek-kiss */
export function MomoPipCheekKiss(props) {
  return (
    <Board {...props}>
      <ellipse cx="30" cy="100" rx="19" ry="14" fill="#F9B0C0" stroke="#3D2137" strokeWidth="4.2" />
      <ellipse cx="86" cy="100" rx="21" ry="15" fill="#FFF1E2" stroke="#3D2137" strokeWidth="4.2" />
      <path d="M46 96c8 4 16 5 22 3" stroke="#3D2137" strokeWidth="16.8" strokeLinecap="round" fill="none" />
      <path d="M46 96c8 4 16 5 22 3" stroke="#F9B0C0" strokeWidth="8.4" strokeLinecap="round" fill="none" />
      <g className="an-startle">
        <path d="M75.8 33.7C73.6 18.8 65.5 9.5 59.2 13.0" stroke="#3D2137" strokeWidth="17.8" strokeLinecap="round" fill="none" />
        <path d="M75.8 33.7C73.6 18.8 65.5 9.5 59.2 13.0" stroke="#FFF1E2" strokeWidth="9.4" strokeLinecap="round" fill="none" />
        <path d="M94.2 33.7C96.4 18.8 104.5 9.5 110.8 13.0" stroke="#3D2137" strokeWidth="17.8" strokeLinecap="round" fill="none" />
        <path d="M94.2 33.7C96.4 18.8 104.5 9.5 110.8 13.0" stroke="#FFF1E2" strokeWidth="9.4" strokeLinecap="round" fill="none" />
        <path d="M75.8 32.8L71.8 21.0" stroke="#F6D9BE" strokeWidth="4" strokeLinecap="round" fill="none" />
        <path d="M94.2 32.8L98.2 21.0" stroke="#F6D9BE" strokeWidth="4" strokeLinecap="round" fill="none" />
        <circle cx="85.0" cy="50.0" r="22.0" fill="#FFF1E2" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="74.0" cy="50.0" rx="7.9" ry="9.2" fill="#3D2137" />
        <circle cx="71.2" cy="46.7" r="3.1" fill="#FFFFFF" />
        <circle cx="76.4" cy="53.1" r="1.7" fill="#FFFFFF" opacity="0.9" />
        <ellipse cx="96.0" cy="50.0" rx="7.9" ry="9.2" fill="#3D2137" />
        <circle cx="93.2" cy="46.7" r="3.1" fill="#FFFFFF" />
        <circle cx="98.4" cy="53.1" r="1.7" fill="#FFFFFF" opacity="0.9" />
        <ellipse cx="85.0" cy="66.0" rx="3.7" ry="4.6" fill="#7A2E44" stroke="#3D2137" strokeWidth="3" />
        <ellipse cx="70.0" cy="63.0" rx="9.5" ry="6.8" fill="#FF9FB0" opacity="0.9" />
        <path d="M64.8 61.6l3.3 4.8M70.0 60.1l3.3 4.8M75.2 61.6l3.3 4.8" stroke="#E85D75" strokeWidth="1.8" strokeLinecap="round" opacity="0.55" />
        <ellipse cx="101.0" cy="62.0" rx="8.0" ry="5.8" fill="#FF9FB0" opacity="0.9" />
        <path d="M96.6 60.8l2.8 4.0M101.0 59.6l2.8 4.0M105.4 60.8l2.8 4.0" stroke="#E85D75" strokeWidth="1.8" strokeLinecap="round" opacity="0.55" />
      </g>
      <g className="an-lean">
        <g transform="rotate(10 34 58)">
          <circle cx="19.6" cy="43.2" r="8.8" fill="#F9B0C0" stroke="#3D2137" strokeWidth="4.2" />
          <circle cx="19.6" cy="44.3" r="3.9" fill="#EF8FA4" />
          <circle cx="48.4" cy="43.2" r="8.8" fill="#F9B0C0" stroke="#3D2137" strokeWidth="4.2" />
          <circle cx="48.4" cy="44.3" r="3.9" fill="#EF8FA4" />
          <circle cx="34.0" cy="58.0" r="20.0" fill="#F9B0C0" stroke="#3D2137" strokeWidth="4.2" />
          <path d="M19.5 56.5q4.5 -6.5 9.0 0" stroke="#3D2137" strokeWidth="3.6" fill="none" strokeLinecap="round" />
          <path d="M38.5 56.5q4.5 -6.5 9.0 0" stroke="#3D2137" strokeWidth="3.6" fill="none" strokeLinecap="round" />
          <ellipse cx="17.0" cy="64.0" rx="6.4" ry="4.4" fill="#FF9FB0" opacity="0.85" />
          <ellipse cx="38.0" cy="66.0" rx="6.4" ry="4.4" fill="#FF9FB0" opacity="0.85" />
        </g>
        <ellipse cx="54" cy="59" rx="8.6" ry="7" fill="#FFF9F4" stroke="#3D2137" strokeWidth="3.2" transform="rotate(-12 54 59)" />
        <path d="M60 41l3.5-4.5M67 46l5-2.5" stroke="#E85D75" strokeWidth="2.6" strokeLinecap="round" opacity="0.75" />
      </g>
      <g className="an-bob">
        <path d="M110.0 35.2c-4.1 -2.8 -5.5 -5.5 -3.7 -7.1c1.4 -1.2 2.9 -0.4 3.7 0.8c0.7 -1.2 2.3 -2.0 3.7 -0.8c1.8 1.6 0.5 4.4 -3.7 7.1Z" fill="#E85D75" stroke="#3D2137" strokeWidth="3.2" strokeLinejoin="round" />
      </g>
      <g className="an-bob an-d2">
        <path d="M101.0 17.5c-3.2 -2.2 -4.3 -4.3 -2.9 -5.6c1.1 -0.9 2.3 -0.3 2.9 0.6c0.6 -0.9 1.8 -1.6 2.9 -0.6c1.4 1.3 0.4 3.4 -2.9 5.6Z" fill="#E85D75" stroke="#3D2137" strokeWidth="3.2" strokeLinejoin="round" />
      </g>
    </Board>
  );
}

/* Head pat — momo-pip/head-pat */
export function MomoPipHeadPat(props) {
  return (
    <Board {...props}>
      <ellipse cx="92" cy="96" rx="19" ry="16" fill="#FFF1E2" stroke="#3D2137" strokeWidth="4.2" />
      <path d="M84.9 45.4C83.2 33.9 76.5 27.0 71.6 30.4" stroke="#3D2137" strokeWidth="17.8" strokeLinecap="round" fill="none" />
      <path d="M84.9 45.4C83.2 33.9 76.5 27.0 71.6 30.4" stroke="#FFF1E2" strokeWidth="9.4" strokeLinecap="round" fill="none" />
      <path d="M99.1 45.4C100.8 33.9 107.5 27.0 112.4 30.4" stroke="#3D2137" strokeWidth="17.8" strokeLinecap="round" fill="none" />
      <path d="M99.1 45.4C100.8 33.9 107.5 27.0 112.4 30.4" stroke="#FFF1E2" strokeWidth="9.4" strokeLinecap="round" fill="none" />
      <path d="M84.9 44.7L81.8 35.6" stroke="#F6D9BE" strokeWidth="4" strokeLinecap="round" fill="none" />
      <path d="M99.1 44.7L102.2 35.6" stroke="#F6D9BE" strokeWidth="4" strokeLinecap="round" fill="none" />
      <circle cx="92.0" cy="58.0" r="17.0" fill="#FFF1E2" stroke="#3D2137" strokeWidth="4.2" />
      <path d="M81.0 60.2q4.0 -5.8 8.0 0" stroke="#3D2137" strokeWidth="3.6" fill="none" strokeLinecap="round" />
      <path d="M96.0 60.2q4.0 -5.8 8.0 0" stroke="#3D2137" strokeWidth="3.6" fill="none" strokeLinecap="round" />
      <path d="M89.7 65.0q2.3 -2.1 4.7 0q-1.7 2.9 -2.3 2.9q-0.7 0 -2.3 -2.9Z" fill="#E85D75" />
      <path d="M92.0 67.9v1.7M92.0 69.5q-2.6 2.3 -3.9 0M92.0 69.5q2.6 2.3 3.9 0" stroke="#3D2137" strokeWidth="2.8" fill="none" strokeLinecap="round" />
      <ellipse cx="79.0" cy="64.0" rx="5.0" ry="3.6" fill="#FF9FB0" opacity="0.85" />
      <ellipse cx="106.0" cy="64.0" rx="5.0" ry="3.6" fill="#FF9FB0" opacity="0.85" />
      <ellipse cx="38" cy="100" rx="24" ry="15" fill="#F9B0C0" stroke="#3D2137" strokeWidth="4.2" />
      <g className="an-melt">
        <circle cx="21.4" cy="55.0" r="10.1" fill="#F9B0C0" stroke="#3D2137" strokeWidth="4.2" />
        <circle cx="21.4" cy="56.2" r="4.5" fill="#EF8FA4" />
        <circle cx="54.6" cy="55.0" r="10.1" fill="#F9B0C0" stroke="#3D2137" strokeWidth="4.2" />
        <circle cx="54.6" cy="56.2" r="4.5" fill="#EF8FA4" />
        <circle cx="38.0" cy="72.0" r="23.0" fill="#F9B0C0" stroke="#3D2137" strokeWidth="4.2" />
        <path d="M20.0 69.8q5.0 7.2 10.0 0" stroke="#3D2137" strokeWidth="3.6" fill="none" strokeLinecap="round" />
        <path d="M46.0 69.8q5.0 7.2 10.0 0" stroke="#3D2137" strokeWidth="3.6" fill="none" strokeLinecap="round" />
        <ellipse cx="38.0" cy="80.0" rx="2.9" ry="2.2" fill="#3D2137" />
        <path d="M34.0 85.0q4.0 5.0 8.0 0" stroke="#3D2137" strokeWidth="3.4" fill="none" strokeLinecap="round" />
        <ellipse cx="17.0" cy="82.0" rx="6.4" ry="4.4" fill="#FF9FB0" opacity="0.85" />
        <ellipse cx="59.0" cy="82.0" rx="6.4" ry="4.4" fill="#FF9FB0" opacity="0.85" />
      </g>
      <g className="an-pat">
        <path d="M78 76C70 66 60 56 52 52" stroke="#3D2137" strokeWidth="16.6" strokeLinecap="round" fill="none" />
        <path d="M78 76C70 66 60 56 52 52" stroke="#FFF1E2" strokeWidth="8.2" strokeLinecap="round" fill="none" />
        <g transform="rotate(-26 48 52)">
          <ellipse cx="48" cy="52" rx="11" ry="7" fill="#FFF1E2" stroke="#3D2137" strokeWidth="4.2" />
          <circle cx="42" cy="55" r="1.9" fill="#F6D9BE" />
          <circle cx="48" cy="56" r="1.9" fill="#F6D9BE" />
          <circle cx="54" cy="55" r="1.9" fill="#F6D9BE" />
        </g>
      </g>
      <g className="an-twinkle">
        <path d="M13.0 48.0Q14.3 52.7 19.0 54.0Q14.3 55.3 13.0 60.0Q11.7 55.3 7.0 54.0Q11.7 52.7 13.0 48.0Z" fill="#F2B880" stroke="#3D2137" strokeWidth="2.2" strokeLinejoin="round" />
      </g>
      <g className="an-twinkle an-d2">
        <path d="M64.0 30.6Q65.2 34.8 69.4 36.0Q65.2 37.2 64.0 41.4Q62.8 37.2 58.6 36.0Q62.8 34.8 64.0 30.6Z" fill="#F2B880" stroke="#3D2137" strokeWidth="2.2" strokeLinejoin="round" />
      </g>
    </Board>
  );
}

/* Forgive me? — momo-pip/forgive-sign */
export function MomoPipForgiveSign(props) {
  return (
    <Board {...props}>
      <ellipse cx="60" cy="102" rx="24" ry="16" fill="#F9B0C0" stroke="#3D2137" strokeWidth="4.2" />
      <path d="M42 98C34 88 36 80 43 76" stroke="#3D2137" strokeWidth="17.0" strokeLinecap="round" fill="none" />
      <path d="M42 98C34 88 36 80 43 76" stroke="#F9B0C0" strokeWidth="8.6" strokeLinecap="round" fill="none" />
      <path d="M78 98c8-10 6-18-1-22" stroke="#3D2137" strokeWidth="17.0" strokeLinecap="round" fill="none" />
      <path d="M78 98c8-10 6-18-1-22" stroke="#F9B0C0" strokeWidth="8.6" strokeLinecap="round" fill="none" />
      <g className="an-tilt">
        <path d="M60 32V66" stroke="#3D2137" strokeWidth="6" strokeLinecap="round" />
        <rect x="10" y="8" width="100" height="42" rx="10" fill="#FFF7F2" stroke="#3D2137" strokeWidth="4.2" />
        <text x="60" y="35" textAnchor="middle" className="hand" fontSize="14.1" textLength="82.0" lengthAdjust="spacingAndGlyphs" fill="#E85D75">forgive me?</text>
      </g>
      <circle cx="44.9" cy="60.5" r="9.2" fill="#F9B0C0" stroke="#3D2137" strokeWidth="4.2" />
      <circle cx="44.9" cy="61.6" r="4.1" fill="#EF8FA4" />
      <circle cx="75.1" cy="60.5" r="9.2" fill="#F9B0C0" stroke="#3D2137" strokeWidth="4.2" />
      <circle cx="75.1" cy="61.6" r="4.1" fill="#EF8FA4" />
      <circle cx="60.0" cy="76.0" r="21.0" fill="#F9B0C0" stroke="#3D2137" strokeWidth="4.2" />
      <path d="M43.0 62.8q5.0 6.4 10.0 0" stroke="#3D2137" strokeWidth="3" fill="none" strokeLinecap="round" />
      <path d="M67.0 62.8q5.0 6.4 10.0 0" stroke="#3D2137" strokeWidth="3" fill="none" strokeLinecap="round" />
      <circle cx="48.0" cy="76.0" r="5.6" fill="#3D2137" />
      <circle cx="46.2" cy="73.8" r="1.7" fill="#FFFFFF" />
      <circle cx="72.0" cy="76.0" r="5.6" fill="#3D2137" />
      <circle cx="70.2" cy="73.8" r="1.7" fill="#FFFFFF" />
      <ellipse cx="60.0" cy="84.0" rx="2.9" ry="2.2" fill="#3D2137" />
      <path d="M55.0 90.0q1.2 -2.2 2.5 0q1.2 2.2 2.5 0q1.2 -2.2 2.5 0q1.2 2.2 2.5 0" stroke="#3D2137" strokeWidth="3.2" fill="none" strokeLinecap="round" />
      <ellipse cx="37.0" cy="85.0" rx="6.4" ry="4.4" fill="#FF9FB0" opacity="0.85" />
      <ellipse cx="83.0" cy="85.0" rx="6.4" ry="4.4" fill="#FF9FB0" opacity="0.85" />
    </Board>
  );
}

/* Sulk & rain — momo-pip/sulk-rain */
export function MomoPipSulkRain(props) {
  return (
    <Board {...props}>
      <g className="an-cloud">
        <path d="M47 28a10 10 0 0 1 17-5 9.5 9.5 0 0 1 15 4 8.5 8.5 0 0 1-2 16H51a9 9 0 0 1-4-15Z" fill="#D5CDE6" stroke="#3D2137" strokeWidth="4.2" strokeLinejoin="round" />
      </g>
      <g className="an-rain">
        <path d="M53 48v8" stroke="#BFD6F5" strokeWidth="4.6" strokeLinecap="round" />
      </g>
      <g className="an-rain an-d2">
        <path d="M61 48v8" stroke="#BFD6F5" strokeWidth="4.6" strokeLinecap="round" />
      </g>
      <g className="an-rain an-d3">
        <path d="M69 48v8" stroke="#BFD6F5" strokeWidth="4.6" strokeLinecap="round" />
      </g>
      <g transform="translate(-6 -8) scale(1.1)">
        <ellipse cx="28" cy="102" rx="19" ry="14" fill="#F9B0C0" stroke="#3D2137" strokeWidth="4.2" />
        <g transform="rotate(-8 27 74)">
          <circle cx="13.3" cy="59.9" r="8.4" fill="#F9B0C0" stroke="#3D2137" strokeWidth="4.2" />
          <circle cx="13.3" cy="60.9" r="3.7" fill="#EF8FA4" />
          <circle cx="40.7" cy="59.9" r="8.4" fill="#F9B0C0" stroke="#3D2137" strokeWidth="4.2" />
          <circle cx="40.7" cy="60.9" r="3.7" fill="#EF8FA4" />
          <circle cx="27.0" cy="74.0" r="19.0" fill="#F9B0C0" stroke="#3D2137" strokeWidth="4.2" />
          <path d="M12.5 62.4q4.5 5.2 9.0 0" stroke="#3D2137" strokeWidth="3" fill="none" strokeLinecap="round" />
          <path d="M30.5 62.4q4.5 5.2 9.0 0" stroke="#3D2137" strokeWidth="3" fill="none" strokeLinecap="round" />
          <circle cx="18.0" cy="74.0" r="5.0" fill="#3D2137" />
          <circle cx="18.8" cy="72.0" r="1.7" fill="#FFFFFF" />
          <circle cx="36.0" cy="74.0" r="5.0" fill="#3D2137" />
          <circle cx="36.8" cy="72.0" r="1.7" fill="#FFFFFF" />
          <ellipse cx="27.0" cy="82.0" rx="2.7" ry="2.1" fill="#3D2137" />
          <path d="M22.5 90.6q4.5 -5.4 9.0 0" stroke="#3D2137" strokeWidth="3.4" fill="none" strokeLinecap="round" />
          <ellipse cx="10.0" cy="82.0" rx="5.2" ry="3.6" fill="#FF9FB0" opacity="0.85" />
          <ellipse cx="44.0" cy="82.0" rx="5.2" ry="3.6" fill="#FF9FB0" opacity="0.85" />
        </g>
        <ellipse cx="90" cy="102" rx="18" ry="14" fill="#FFF1E2" stroke="#3D2137" strokeWidth="4.2" />
        <g transform="rotate(8 91 75)">
          <path d="M84.3 63.2C82.7 52.3 72.8 48.3 67.3 57.3" stroke="#3D2137" strokeWidth="17.8" strokeLinecap="round" fill="none" />
          <path d="M84.3 63.2C82.7 52.3 72.8 48.3 67.3 57.3" stroke="#FFF1E2" strokeWidth="9.4" strokeLinecap="round" fill="none" />
          <path d="M97.7 63.2C99.3 52.3 109.2 48.3 114.7 57.3" stroke="#3D2137" strokeWidth="17.8" strokeLinecap="round" fill="none" />
          <path d="M97.7 63.2C99.3 52.3 109.2 48.3 114.7 57.3" stroke="#FFF1E2" strokeWidth="9.4" strokeLinecap="round" fill="none" />
          <path d="M84.3 62.5L81.4 53.9" stroke="#F6D9BE" strokeWidth="4" strokeLinecap="round" fill="none" />
          <path d="M97.7 62.5L100.6 53.9" stroke="#F6D9BE" strokeWidth="4" strokeLinecap="round" fill="none" />
          <circle cx="91.0" cy="75.0" r="16.0" fill="#FFF1E2" stroke="#3D2137" strokeWidth="4.2" />
          <path d="M78.5 63.4q4.5 5.2 9.0 0" stroke="#3D2137" strokeWidth="3" fill="none" strokeLinecap="round" />
          <path d="M94.5 63.4q4.5 5.2 9.0 0" stroke="#3D2137" strokeWidth="3" fill="none" strokeLinecap="round" />
          <circle cx="83.0" cy="75.0" r="5.0" fill="#3D2137" />
          <circle cx="79.0" cy="73.0" r="1.7" fill="#FFFFFF" />
          <circle cx="100.0" cy="75.0" r="5.0" fill="#3D2137" />
          <circle cx="96.0" cy="73.0" r="1.7" fill="#FFFFFF" />
          <path d="M87.5 89.6q4.5 -5.4 9.0 0" stroke="#3D2137" strokeWidth="3.4" fill="none" strokeLinecap="round" />
          <ellipse cx="76.0" cy="83.0" rx="5.2" ry="3.6" fill="#FF9FB0" opacity="0.85" />
          <ellipse cx="107.0" cy="83.0" rx="5.2" ry="3.6" fill="#FF9FB0" opacity="0.85" />
        </g>
      </g>
    </Board>
  );
}

/* Made up — momo-pip/made-up */
export function MomoPipMadeUp(props) {
  return (
    <Board {...props}>
      <ellipse cx="34" cy="98" rx="22" ry="17" fill="#F9B0C0" stroke="#3D2137" strokeWidth="4.2" />
      <ellipse cx="86" cy="98" rx="21" ry="16" fill="#FFF1E2" stroke="#3D2137" strokeWidth="4.2" />
      <path d="M50 92c8 4 14 5 20 3" stroke="#3D2137" strokeWidth="16.8" strokeLinecap="round" fill="none" />
      <path d="M50 92c8 4 14 5 20 3" stroke="#F9B0C0" strokeWidth="8.4" strokeLinecap="round" fill="none" />
      <g className="an-cheer">
        <circle cx="18.2" cy="39.7" r="9.7" fill="#F9B0C0" stroke="#3D2137" strokeWidth="4.2" />
        <circle cx="18.2" cy="40.9" r="4.3" fill="#EF8FA4" />
        <circle cx="49.8" cy="39.7" r="9.7" fill="#F9B0C0" stroke="#3D2137" strokeWidth="4.2" />
        <circle cx="49.8" cy="40.9" r="4.3" fill="#EF8FA4" />
        <circle cx="34.0" cy="56.0" r="22.0" fill="#F9B0C0" stroke="#3D2137" strokeWidth="4.2" />
        <path d="M18.2 58.7q4.8 -6.8 9.5 0" stroke="#3D2137" strokeWidth="3.6" fill="none" strokeLinecap="round" />
        <path d="M40.2 58.7q4.8 -6.8 9.5 0" stroke="#3D2137" strokeWidth="3.6" fill="none" strokeLinecap="round" />
        <path d="M28.0 66.0q6.0 -2.6 12.0 0q-1.2 8.0 -6.0 8.0q-4.8 0 -6.0 -8.0Z" fill="#7A2E44" stroke="#3D2137" strokeWidth="3.2" strokeLinejoin="round" />
        <ellipse cx="14.0" cy="66.0" rx="6.4" ry="4.4" fill="#FF9FB0" opacity="0.85" />
        <ellipse cx="54.0" cy="66.0" rx="6.4" ry="4.4" fill="#FF9FB0" opacity="0.85" />
      </g>
      <g className="an-cheer an-d2">
        <path d="M77.6 43.2C75.6 29.6 68.3 21.1 62.6 24.3" stroke="#3D2137" strokeWidth="17.8" strokeLinecap="round" fill="none" />
        <path d="M77.6 43.2C75.6 29.6 68.3 21.1 62.6 24.3" stroke="#FFF1E2" strokeWidth="9.4" strokeLinecap="round" fill="none" />
        <path d="M94.4 43.2C96.4 29.6 103.7 21.1 109.4 24.3" stroke="#3D2137" strokeWidth="17.8" strokeLinecap="round" fill="none" />
        <path d="M94.4 43.2C96.4 29.6 103.7 21.1 109.4 24.3" stroke="#FFF1E2" strokeWidth="9.4" strokeLinecap="round" fill="none" />
        <path d="M77.6 42.4L74.0 31.6" stroke="#F6D9BE" strokeWidth="4" strokeLinecap="round" fill="none" />
        <path d="M94.4 42.4L98.0 31.6" stroke="#F6D9BE" strokeWidth="4" strokeLinecap="round" fill="none" />
        <circle cx="86.0" cy="58.0" r="20.0" fill="#FFF1E2" stroke="#3D2137" strokeWidth="4.2" />
        <path d="M71.5 60.5q4.5 -6.5 9.0 0" stroke="#3D2137" strokeWidth="3.6" fill="none" strokeLinecap="round" />
        <path d="M90.5 60.5q4.5 -6.5 9.0 0" stroke="#3D2137" strokeWidth="3.6" fill="none" strokeLinecap="round" />
        <path d="M80.5 68.0q5.5 -2.4 11.0 0q-1.1 7.5 -5.5 7.5q-4.4 0 -5.5 -7.5Z" fill="#7A2E44" stroke="#3D2137" strokeWidth="3.2" strokeLinejoin="round" />
        <ellipse cx="68.0" cy="68.0" rx="6.4" ry="4.4" fill="#FF9FB0" opacity="0.85" />
        <ellipse cx="103.0" cy="68.0" rx="6.4" ry="4.4" fill="#FF9FB0" opacity="0.85" />
      </g>
      <g className="an-bob">
        <path d="M60.0 31.6c-7.2 -4.8 -9.6 -9.6 -6.4 -12.4c2.4 -2.1 5.1 -0.6 6.4 1.4c1.3 -2.1 4.0 -3.5 6.4 -1.4c3.2 2.8 0.8 7.6 -6.4 12.4Z" fill="#E85D75" stroke="#3D2137" strokeWidth="3.2" strokeLinejoin="round" />
      </g>
      <g className="an-twinkle">
        <path d="M10.0 28.4Q11.2 32.8 15.6 34.0Q11.2 35.2 10.0 39.6Q8.8 35.2 4.4 34.0Q8.8 32.8 10.0 28.4Z" fill="#F2B880" stroke="#3D2137" strokeWidth="2.2" strokeLinejoin="round" />
      </g>
      <g className="an-twinkle an-d2">
        <path d="M112.0 35.0Q113.1 38.9 117.0 40.0Q113.1 41.1 112.0 45.0Q110.9 41.1 107.0 40.0Q110.9 38.9 112.0 35.0Z" fill="#F2B880" stroke="#3D2137" strokeWidth="2.2" strokeLinejoin="round" />
      </g>
    </Board>
  );
}

/* id -> component, ready for the registry in ./index.jsx */
export const COMPONENTS = {
  'momo-pip/begging': MomoPipBegging,
  'momo-pip/waterfall-cry': MomoPipWaterfallCry,
  'momo-pip/big-hug': MomoPipBigHug,
  'momo-pip/flowers-shy': MomoPipFlowersShy,
  'momo-pip/pouty': MomoPipPouty,
  'momo-pip/cheek-kiss': MomoPipCheekKiss,
  'momo-pip/head-pat': MomoPipHeadPat,
  'momo-pip/forgive-sign': MomoPipForgiveSign,
  'momo-pip/sulk-rain': MomoPipSulkRain,
  'momo-pip/made-up': MomoPipMadeUp,
};

export default COMPONENTS;
