/* eslint-disable */
'use client';

/**
 * Poppy & Truffle 🐷 — Pig couple; the snouts and curly tails do the acting.
 *
 * AUTO-GENERATED by tools/stickers/gen_pack_jsx.py. Do not edit by hand:
 * re-run the generator instead, or the drawings drift from the sheets.
 *
 * Ten poses, one 120x120 board each, house palette and plum ink. The
 * `an-*` classes are the little motion loops; they live in globals.css and
 * switch themselves off under prefers-reduced-motion.
 */

import { Board } from './board';

/* Begging — poppy-truffle/begging */
export function PoppyTruffleBegging(props) {
  return (
    <Board {...props}>
      <g className="an-twinkle">
        <path d="M16 35.6 q0.8 2.7 4.4 4.4 q-2.7 0.8 -4.4 4.4 q-0.8 -2.7 -4.4 -4.4 q2.7 -0.8 4.4 -4.4Z" fill="#F2B880" opacity="1" />
      </g>
      <g className="an-twinkle an-d2">
        <path d="M104 48.4 q0.6 2.2 3.6 3.6 q-2.2 0.6 -3.6 3.6 q-0.6 -2.2 -3.6 -3.6 q2.2 -0.6 3.6 -3.6Z" fill="#F2B880" opacity="1" />
      </g>
      <g className="an-bob an-d2">
        <path d="M103 21.5 c2.3 2.7 3.6 4.9 0 8.5 c-3.6 0 -3.6 -2.2 0 -8.5Z" fill="#BFD6F5" stroke="#3D2137" strokeWidth="2.2" strokeLinejoin="round" />
      </g>
      <g className="an-plead">
        <path d="M79.2 83.3 c9 0 12 -6 9.6 -10.5 c-2.1 -3.9 -8.1 -3.3 -8.4 1.2 c-.3 3.9 3.9 6 7.5 4.5" stroke="#3D2137" strokeWidth="11.4" strokeLinecap="round" fill="none" />
        <path d="M79.2 83.3 c9 0 12 -6 9.6 -10.5 c-2.1 -3.9 -8.1 -3.3 -8.4 1.2 c-.3 3.9 3.9 6 7.5 4.5" stroke="#F5A8B8" strokeWidth="5.2" strokeLinecap="round" fill="none" />
        <ellipse cx="50" cy="95.3" rx="6.8" ry="5.1" fill="#F5A8B8" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="70" cy="95.3" rx="6.8" ry="5.1" fill="#F5A8B8" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="60" cy="75.5" rx="20" ry="23" fill="#F5A8B8" stroke="#3D2137" strokeWidth="4.2" />
        <path d="M51 24.5 C50 14.5 43 11 40.5 7 C36.5 14.5 35.5 19 37.5 27 Z" fill="#F5A8B8" stroke="#3D2137" strokeWidth="4.2" strokeLinejoin="round" />
        <path d="M45 23.5 C45.5 15.5 42.5 13.5 41.5 10.5" stroke="#FFCFD9" strokeWidth="3.6" fill="none" strokeLinecap="round" opacity=".8" />
        <path d="M69 24.5 C70 14.5 77 11 79.5 7 C83.5 14.5 84.5 19 82.5 27 Z" fill="#F5A8B8" stroke="#3D2137" strokeWidth="4.2" strokeLinejoin="round" />
        <path d="M75 23.5 C74.5 15.5 77.5 13.5 78.5 10.5" stroke="#FFCFD9" strokeWidth="3.6" fill="none" strokeLinecap="round" opacity=".8" />
        <circle cx="60" cy="40" r="25" fill="#F5A8B8" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="48.8" cy="42.2" rx="9.3" ry="10.6" fill="#3D2137" />
        <circle cx="45.6" cy="38.4" r="4.3" fill="#FFFFFF" />
        <circle cx="51.9" cy="45.4" r="2.2" fill="#FFFFFF" opacity=".92" />
        <ellipse cx="71.2" cy="42.2" rx="9.3" ry="10.6" fill="#3D2137" />
        <circle cx="68.1" cy="38.4" r="4.3" fill="#FFFFFF" />
        <circle cx="74.4" cy="45.4" r="2.2" fill="#FFFFFF" opacity=".92" />
        <ellipse cx="60" cy="50" rx="11.4" ry="7.9" fill="#FFCFD9" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="56.1" cy="50" rx="1.9" ry="2.7" fill="#3D2137" />
        <ellipse cx="63.9" cy="50" rx="1.9" ry="2.7" fill="#3D2137" />
        <path d="M55 60 q1.2 -2.2 2.5 0 q1.2 2.2 2.5 0 q1.2 -2.2 2.5 0 q1.2 2.2 2.5 0" stroke="#3D2137" strokeWidth="3" fill="none" strokeLinecap="round" />
        <ellipse cx="42.5" cy="53" rx="5.2" ry="3.9" fill="#F2748C" opacity="0.9" />
        <ellipse cx="77.5" cy="53" rx="5.2" ry="3.9" fill="#F2748C" opacity="0.9" />
        <path d="M42.8 68.6 Q42.7 73.6 51.5 76.5" stroke="#3D2137" strokeWidth="11.2" strokeLinecap="round" fill="none" />
        <path d="M42.8 68.6 Q42.7 73.6 51.5 76.5" stroke="#F5A8B8" strokeWidth="5.4" strokeLinecap="round" fill="none" />
        <path d="M77.2 68.6 Q69.3 73.6 68.5 76.5" stroke="#3D2137" strokeWidth="11.2" strokeLinecap="round" fill="none" />
        <path d="M77.2 68.6 Q69.3 73.6 68.5 76.5" stroke="#F5A8B8" strokeWidth="5.4" strokeLinecap="round" fill="none" />
        <ellipse cx="51" cy="76.5" rx="5.4" ry="4.7" fill="#F5A8B8" stroke="#3D2137" strokeWidth="3.4" transform="rotate(-26 51 76.5)" />
        <ellipse cx="69" cy="76.5" rx="5.4" ry="4.7" fill="#F5A8B8" stroke="#3D2137" strokeWidth="3.4" transform="rotate(26 69 76.5)" />
      </g>
    </Board>
  );
}

/* Waterfall cry — poppy-truffle/waterfall-cry */
export function PoppyTruffleWaterfallCry(props) {
  return (
    <Board {...props}>
      <ellipse cx="60" cy="108" rx="27" ry="4.8" fill="#BFD6F5" opacity=".75" />
      <g className="an-sob">
        <path d="M78.4 79.6 c8 3.5 10 10 8 16.5" stroke="#3D2137" strokeWidth="11.4" strokeLinecap="round" fill="none" />
        <path d="M78.4 79.6 c8 3.5 10 10 8 16.5" stroke="#F5A8B8" strokeWidth="5.2" strokeLinecap="round" fill="none" />
        <ellipse cx="50.4" cy="91.1" rx="6.5" ry="4.9" fill="#F5A8B8" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="69.6" cy="91.1" rx="6.5" ry="4.9" fill="#F5A8B8" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="60" cy="72.1" rx="19.2" ry="22.1" fill="#F5A8B8" stroke="#3D2137" strokeWidth="4.2" />
        <path d="M43.5 65.5 Q43 76.1 33.6 86" stroke="#3D2137" strokeWidth="11.2" strokeLinecap="round" fill="none" />
        <path d="M43.5 65.5 Q43 76.1 33.6 86" stroke="#F5A8B8" strokeWidth="5.4" strokeLinecap="round" fill="none" />
        <path d="M76.5 65.5 Q85 76.1 86.4 86" stroke="#3D2137" strokeWidth="11.2" strokeLinecap="round" fill="none" />
        <path d="M76.5 65.5 Q85 76.1 86.4 86" stroke="#F5A8B8" strokeWidth="5.4" strokeLinecap="round" fill="none" />
        <ellipse cx="32.6" cy="87" rx="5.4" ry="4.7" fill="#F5A8B8" stroke="#3D2137" strokeWidth="3.4" transform="rotate(-18 32.6 87)" />
        <ellipse cx="87.4" cy="87" rx="5.4" ry="4.7" fill="#F5A8B8" stroke="#3D2137" strokeWidth="3.4" transform="rotate(18 87.4 87)" />
        <path d="M51.4 23.1 C50.4 13.5 45.4 11.8 43 8 C39.1 15.2 36.5 17.8 38.4 25.5 Z" fill="#F5A8B8" stroke="#3D2137" strokeWidth="4.2" strokeLinejoin="round" />
        <path d="M45.6 22.2 C46.1 14.5 44.9 14.2 43.9 11.4" stroke="#FFCFD9" strokeWidth="3.6" fill="none" strokeLinecap="round" opacity=".8" />
        <path d="M68.6 23.1 C69.6 13.5 74.6 11.8 77 8 C80.9 15.2 83.5 17.8 81.6 25.5 Z" fill="#F5A8B8" stroke="#3D2137" strokeWidth="4.2" strokeLinejoin="round" />
        <path d="M74.4 22.2 C73.9 14.5 75.1 14.2 76.1 11.4" stroke="#FFCFD9" strokeWidth="3.6" fill="none" strokeLinecap="round" opacity=".8" />
        <circle cx="60" cy="38" r="24" fill="#F5A8B8" stroke="#3D2137" strokeWidth="4.2" />
        <path d="M41.6 45.2 L49.2 35.1 L56.8 45.2" stroke="#3D2137" strokeWidth="3.6" fill="none" strokeLinecap="round" strokeLinejoin="round" />
        <path d="M63.2 45.2 L70.8 35.1 L78.4 45.2" stroke="#3D2137" strokeWidth="3.6" fill="none" strokeLinecap="round" strokeLinejoin="round" />
        <ellipse cx="60" cy="47.6" rx="12.5" ry="6.2" fill="#FFCFD9" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="55.8" cy="47.6" rx="2.1" ry="2.1" fill="#3D2137" />
        <ellipse cx="64.2" cy="47.6" rx="2.1" ry="2.1" fill="#3D2137" />
        <ellipse cx="60" cy="58.2" rx="3.6" ry="4.6" fill="#7A2E44" stroke="#3D2137" strokeWidth="3" />
        <ellipse cx="43.2" cy="50.5" rx="5" ry="3.7" fill="#F2748C" opacity="0.9" />
        <ellipse cx="76.8" cy="50.5" rx="5" ry="3.7" fill="#F2748C" opacity="0.9" />
      </g>
      <g className="an-stream">
        <path d="M49.2 45.2 v38" stroke="#BFD6F5" strokeWidth="6.2" strokeLinecap="round" opacity=".95" />
      </g>
      <g className="an-stream an-d2">
        <path d="M70.8 45.2 v38" stroke="#BFD6F5" strokeWidth="6.2" strokeLinecap="round" opacity=".95" />
      </g>
      <g className="an-teardrop">
        <path d="M18 41.3 c2 2.7 3.4 4.2 3.4 5.9 c0 2 -1.6 3.4 -3.4 3.4 c-2 0 -3.4 -1.7 -3.4 -3.4Z" fill="#BFD6F5" stroke="#3D2137" strokeWidth="2.6" strokeLinejoin="round" />
      </g>
      <g className="an-teardrop an-d3">
        <path d="M103 47.9 c1.8 2.3 3 3.7 3 5.2 c0 1.8 -1.4 3 -3 3 c-1.8 0 -3 -1.5 -3 -3Z" fill="#BFD6F5" stroke="#3D2137" strokeWidth="2.6" strokeLinejoin="round" />
      </g>
    </Board>
  );
}

/* Big hug — poppy-truffle/big-hug */
export function PoppyTruffleBigHug(props) {
  return (
    <Board {...props}>
      <g className="an-squeeze">
        <path d="M95.4 87.7 c9.8 -1.5 12.8 -9 9.6 -14 c-2.7 -4.4 -9.3 -3.3 -9 1.8 c.3 4.5 5.4 6.3 9.6 3.9" stroke="#3D2137" strokeWidth="11.4" strokeLinecap="round" fill="none" />
        <path d="M95.4 87.7 c9.8 -1.5 12.8 -9 9.6 -14 c-2.7 -4.4 -9.3 -3.3 -9 1.8 c.3 4.5 5.4 6.3 9.6 3.9" stroke="#D98CA0" strokeWidth="5.2" strokeLinecap="round" fill="none" />
        <path d="M75.2 79.6 C61.5 85.2 36.9 83.2 26.3 75.2" stroke="#3D2137" strokeWidth="11.8" strokeLinecap="round" fill="none" />
        <path d="M75.2 79.6 C61.5 85.2 36.9 83.2 26.3 75.2" stroke="#D98CA0" strokeWidth="5.8" strokeLinecap="round" fill="none" />
        <ellipse cx="24.5" cy="74.9" rx="5.7" ry="4.9" fill="#D98CA0" stroke="#3D2137" strokeWidth="3.4" transform="rotate(18 24.5 74.9)" />
        <path d="M47.6 78.7 C61.5 93.2 86.4 91.2 97.6 82.4" stroke="#3D2137" strokeWidth="11.8" strokeLinecap="round" fill="none" />
        <path d="M47.6 78.7 C61.5 93.2 86.4 91.2 97.6 82.4" stroke="#F5A8B8" strokeWidth="5.8" strokeLinecap="round" fill="none" />
        <ellipse cx="99.5" cy="82.1" rx="5.7" ry="4.9" fill="#F5A8B8" stroke="#3D2137" strokeWidth="3.4" transform="rotate(-18 99.5 82.1)" />
        <ellipse cx="35.4" cy="92" rx="5.2" ry="3.8" fill="#F5A8B8" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="50.6" cy="92" rx="5.2" ry="3.8" fill="#F5A8B8" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="43" cy="77" rx="15.2" ry="17.5" fill="#F5A8B8" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="72" cy="97.2" rx="5.4" ry="4" fill="#D98CA0" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="88" cy="97.2" rx="5.4" ry="4" fill="#D98CA0" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="80" cy="81.4" rx="16" ry="18.4" fill="#D98CA0" stroke="#3D2137" strokeWidth="4.2" />
        <path d="M36.2 38.2 C35.4 30.6 30.5 28.3 28.6 25.3 C25.5 31 24.4 34 25.9 40.1 Z" fill="#F5A8B8" stroke="#3D2137" strokeWidth="4.2" strokeLinejoin="round" />
        <path d="M31.6 37.5 C32 31.4 30.1 30.2 29.3 28" stroke="#FFCFD9" strokeWidth="3.6" fill="none" strokeLinecap="round" opacity=".8" />
        <path d="M49.8 38.2 C50.6 30.6 55.5 28.3 57.4 25.3 C60.5 31 61.6 34 60.1 40.1 Z" fill="#F5A8B8" stroke="#3D2137" strokeWidth="4.2" strokeLinejoin="round" />
        <path d="M54.4 37.5 C54 31.4 55.9 30.2 56.7 28" stroke="#FFCFD9" strokeWidth="3.6" fill="none" strokeLinecap="round" opacity=".8" />
        <circle cx="43" cy="50" r="19" fill="#F5A8B8" stroke="#3D2137" strokeWidth="4.2" />
        <path d="M28.8 51.7 q5.7 -8.6 11.4 0" stroke="#3D2137" strokeWidth="3.6" fill="none" strokeLinecap="round" />
        <path d="M45.8 51.7 q5.7 -8.6 11.4 0" stroke="#3D2137" strokeWidth="3.6" fill="none" strokeLinecap="round" />
        <ellipse cx="43" cy="57.6" rx="8.4" ry="6.3" fill="#FFCFD9" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="40.2" cy="57.6" rx="1.4" ry="2.1" fill="#3D2137" />
        <ellipse cx="45.8" cy="57.6" rx="1.4" ry="2.1" fill="#3D2137" />
        <path d="M40.5 65.2 q2.5 2.7 4.9 0" stroke="#3D2137" strokeWidth="3" fill="none" strokeLinecap="round" />
        <ellipse cx="29.7" cy="59.9" rx="4" ry="2.9" fill="#F2748C" opacity="0.9" />
        <ellipse cx="56.3" cy="59.9" rx="4" ry="2.9" fill="#F2748C" opacity="0.9" />
        <path d="M70.4 36.2 C54 28.2 46.8 46.2 53.6 54.6 C59.2 58.2 67.2 49.8 70.4 36.2 Z" fill="#D98CA0" stroke="#3D2137" strokeWidth="4.2" strokeLinejoin="round" />
        <path d="M64.8 39 C56.4 37 53.2 45.4 57.6 51.4" stroke="#F0B6C4" strokeWidth="3.4" fill="none" strokeLinecap="round" opacity=".75" />
        <path d="M89.6 36.2 C106 28.2 113.2 46.2 106.4 54.6 C100.8 58.2 92.8 49.8 89.6 36.2 Z" fill="#D98CA0" stroke="#3D2137" strokeWidth="4.2" strokeLinejoin="round" />
        <path d="M95.2 39 C103.6 37 106.8 45.4 102.4 51.4" stroke="#F0B6C4" strokeWidth="3.4" fill="none" strokeLinecap="round" opacity=".75" />
        <circle cx="80" cy="53" r="20" fill="#D98CA0" stroke="#3D2137" strokeWidth="4.2" />
        <path d="M65 54.8 q6 -9 12 0" stroke="#3D2137" strokeWidth="3.6" fill="none" strokeLinecap="round" />
        <path d="M83 54.8 q6 -9 12 0" stroke="#3D2137" strokeWidth="3.6" fill="none" strokeLinecap="round" />
        <ellipse cx="80" cy="61" rx="8.8" ry="6.6" fill="#F0B6C4" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="77" cy="61" rx="1.5" ry="2.2" fill="#3D2137" />
        <ellipse cx="83" cy="61" rx="1.5" ry="2.2" fill="#3D2137" />
        <path d="M77.4 69 q2.6 2.8 5.2 0" stroke="#3D2137" strokeWidth="3" fill="none" strokeLinecap="round" />
        <ellipse cx="66" cy="63.4" rx="4.2" ry="3.1" fill="#C8536F" opacity="0.9" />
        <ellipse cx="94" cy="63.4" rx="4.2" ry="3.1" fill="#C8536F" opacity="0.9" />
        <path d="M66 80 C58 76 48 76 42 79" stroke="#3D2137" strokeWidth="11.4" strokeLinecap="round" fill="none" />
        <path d="M66 80 C58 76 48 76 42 79" stroke="#F5A8B8" strokeWidth="5.6" strokeLinecap="round" fill="none" />
      </g>
      <g className="an-bob">
        <path d="M60 16.8 C57 14 54.6 11.8 54.6 10 C54.6 7.8 57.4 6.8 58.7 8.5 C59.3 9.2 59.7 9.6 60 9.9 C60.3 9.6 60.7 9.2 61.3 8.5 C62.6 6.8 65.4 7.8 65.4 10 C65.4 11.8 63 14 60 16.8 Z" fill="#E85D75" stroke="#3D2137" strokeWidth="3.2" strokeLinejoin="round" />
      </g>
      <g className="an-bob an-d2">
        <path d="M103 23.3 C100.9 21.4 99.3 19.9 99.3 18.6 C99.3 17.1 101.2 16.4 102.1 17.6 C102.5 18.1 102.8 18.3 103 18.5 C103.2 18.3 103.5 18.1 103.9 17.6 C104.8 16.4 106.7 17.1 106.7 18.6 C106.7 19.9 105.1 21.4 103 23.3 Z" fill="#E85D75" stroke="#3D2137" strokeWidth="3.2" strokeLinejoin="round" />
      </g>
    </Board>
  );
}

/* Flowers, shy — poppy-truffle/flowers-shy */
export function PoppyTruffleFlowersShy(props) {
  return (
    <Board {...props}>
      <g className="an-shy">
        <g transform="translate(51.1 0) scale(-1 1)">
          <path d="M25.6 83.6 c9 0 12 -6 9.6 -10.5 c-2.1 -3.9 -8.1 -3.3 -8.4 1.2 c-.3 3.9 3.9 6 7.5 4.5" stroke="#3D2137" strokeWidth="11.4" strokeLinecap="round" fill="none" />
          <path d="M25.6 83.6 c9 0 12 -6 9.6 -10.5 c-2.1 -3.9 -8.1 -3.3 -8.4 1.2 c-.3 3.9 3.9 6 7.5 4.5" stroke="#F5A8B8" strokeWidth="5.2" strokeLinecap="round" fill="none" />
        </g>
        <ellipse cx="34.4" cy="95.1" rx="6.5" ry="4.9" fill="#F5A8B8" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="53.6" cy="95.1" rx="6.5" ry="4.9" fill="#F5A8B8" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="44" cy="76.1" rx="19.2" ry="22.1" fill="#F5A8B8" stroke="#3D2137" strokeWidth="4.2" />
        <path d="M27.5 69.5 Q32 74.9 30.8 79.2" stroke="#3D2137" strokeWidth="11.2" strokeLinecap="round" fill="none" />
        <path d="M27.5 69.5 Q32 74.9 30.8 79.2" stroke="#F5A8B8" strokeWidth="5.4" strokeLinecap="round" fill="none" />
        <path d="M35.4 27.1 C34.4 17.5 28.2 14.6 25.8 10.8 C21.9 18 20.5 21.8 22.4 29.5 Z" fill="#F5A8B8" stroke="#3D2137" strokeWidth="4.2" strokeLinejoin="round" />
        <path d="M29.6 26.2 C30.1 18.5 27.7 17 26.7 14.2" stroke="#FFCFD9" strokeWidth="3.6" fill="none" strokeLinecap="round" opacity=".8" />
        <path d="M52.6 27.1 C53.6 17.5 59.8 14.6 62.2 10.8 C66.1 18 67.5 21.8 65.6 29.5 Z" fill="#F5A8B8" stroke="#3D2137" strokeWidth="4.2" strokeLinejoin="round" />
        <path d="M58.4 26.2 C57.9 18.5 60.3 17 61.3 14.2" stroke="#FFCFD9" strokeWidth="3.6" fill="none" strokeLinecap="round" opacity=".8" />
        <circle cx="44" cy="42" r="24" fill="#F5A8B8" stroke="#3D2137" strokeWidth="4.2" />
        <path d="M26 44.2 q7.2 -10.8 14.4 0" stroke="#3D2137" strokeWidth="3.6" fill="none" strokeLinecap="round" />
        <path d="M47.6 44.2 q7.2 -10.8 14.4 0" stroke="#3D2137" strokeWidth="3.6" fill="none" strokeLinecap="round" />
        <ellipse cx="44" cy="51.6" rx="10.6" ry="7.9" fill="#FFCFD9" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="40.4" cy="51.6" rx="1.8" ry="2.7" fill="#3D2137" />
        <ellipse cx="47.6" cy="51.6" rx="1.8" ry="2.7" fill="#3D2137" />
        <path d="M40.9 61.2 q3.1 3.4 6.2 0" stroke="#3D2137" strokeWidth="3" fill="none" strokeLinecap="round" />
        <ellipse cx="27.2" cy="54.5" rx="5" ry="3.7" fill="#F2748C" opacity="0.9" />
        <ellipse cx="60.8" cy="54.5" rx="5" ry="3.7" fill="#F2748C" opacity="0.9" />
        <ellipse cx="27.2" cy="54.5" rx="6.6" ry="4.8" fill="#F2748C" opacity="0.9" />
        <ellipse cx="60.8" cy="54.5" rx="6.6" ry="4.8" fill="#F2748C" opacity="0.9" />
        <path d="M60.5 69.5 Q69.3 72 89 72" stroke="#3D2137" strokeWidth="11.2" strokeLinecap="round" fill="none" />
        <path d="M60.5 69.5 Q69.3 72 89 72" stroke="#F5A8B8" strokeWidth="5.4" strokeLinecap="round" fill="none" />
        <ellipse cx="92" cy="74" rx="5.4" ry="4.7" fill="#F5A8B8" stroke="#3D2137" strokeWidth="3.4" transform="rotate(-10 92 74)" />
      </g>
      <g className="an-sway-s">
        <path d="M92 70 Q88.2 61.2 81 54" stroke="#6FA96E" strokeWidth="3.6" strokeLinecap="round" fill="none" />
        <path d="M92 70 Q92.3 55.8 93 45" stroke="#6FA96E" strokeWidth="3.6" strokeLinecap="round" fill="none" />
        <path d="M92 70 Q96.2 62.4 104 56" stroke="#6FA96E" strokeWidth="3.6" strokeLinecap="round" fill="none" />
        <path d="M89 60 l-6 3 M95 64 l6 4" stroke="#6FA96E" strokeWidth="3.2" strokeLinecap="round" fill="none" />
        <circle cx="81" cy="48.9" r="3.6" fill="#FFF3E9" stroke="#3D2137" strokeWidth="2.4" />
        <circle cx="85.8" cy="52.4" r="3.6" fill="#FFF3E9" stroke="#3D2137" strokeWidth="2.4" />
        <circle cx="84" cy="58.1" r="3.6" fill="#FFF3E9" stroke="#3D2137" strokeWidth="2.4" />
        <circle cx="78" cy="58.1" r="3.6" fill="#FFF3E9" stroke="#3D2137" strokeWidth="2.4" />
        <circle cx="76.2" cy="52.4" r="3.6" fill="#FFF3E9" stroke="#3D2137" strokeWidth="2.4" />
        <circle cx="81" cy="54" r="2.7" fill="#F2B880" stroke="#3D2137" strokeWidth="2.4" />
        <circle cx="93" cy="39.6" r="3.8" fill="#FFF3E9" stroke="#3D2137" strokeWidth="2.4" />
        <circle cx="98.1" cy="43.3" r="3.8" fill="#FFF3E9" stroke="#3D2137" strokeWidth="2.4" />
        <circle cx="96.2" cy="49.4" r="3.8" fill="#FFF3E9" stroke="#3D2137" strokeWidth="2.4" />
        <circle cx="89.8" cy="49.4" r="3.8" fill="#FFF3E9" stroke="#3D2137" strokeWidth="2.4" />
        <circle cx="87.9" cy="43.3" r="3.8" fill="#FFF3E9" stroke="#3D2137" strokeWidth="2.4" />
        <circle cx="93" cy="45" r="2.9" fill="#F2B880" stroke="#3D2137" strokeWidth="2.4" />
        <circle cx="104" cy="51.2" r="3.4" fill="#FFF3E9" stroke="#3D2137" strokeWidth="2.4" />
        <circle cx="108.5" cy="54.5" r="3.4" fill="#FFF3E9" stroke="#3D2137" strokeWidth="2.4" />
        <circle cx="106.8" cy="59.8" r="3.4" fill="#FFF3E9" stroke="#3D2137" strokeWidth="2.4" />
        <circle cx="101.2" cy="59.8" r="3.4" fill="#FFF3E9" stroke="#3D2137" strokeWidth="2.4" />
        <circle cx="99.5" cy="54.5" r="3.4" fill="#FFF3E9" stroke="#3D2137" strokeWidth="2.4" />
        <circle cx="104" cy="56" r="2.6" fill="#F2B880" stroke="#3D2137" strokeWidth="2.4" />
      </g>
      <g className="an-twinkle">
        <path d="M12 22 q0.7 2.5 4 4 q-2.5 0.7 -4 4 q-0.7 -2.5 -4 -4 q2.5 -0.7 4 -4Z" fill="#F2B880" opacity="1" />
      </g>
      <g className="an-twinkle an-d2">
        <path d="M110 36.8 q0.6 2 3.2 3.2 q-2 0.6 -3.2 3.2 q-0.6 -2 -3.2 -3.2 q2 -0.6 3.2 -3.2Z" fill="#F2B880" opacity="1" />
      </g>
    </Board>
  );
}

/* Pouty — poppy-truffle/pouty */
export function PoppyTrufflePouty(props) {
  return (
    <Board {...props}>
      <g className="an-steam">
        <path d="M100 24c6-4 3-10-2-12s-6-7-1-10" stroke="#D5CDE6" strokeWidth="5.4" strokeLinecap="round" fill="none" />
      </g>
      <g className="an-steam an-d2">
        <path d="M111 40c5-4 2-9-2-11" stroke="#D5CDE6" strokeWidth="4.6" strokeLinecap="round" fill="none" />
      </g>
      <g className="an-huff">
        <g transform="rotate(-6 56 66)">
          <g transform="translate(73.6 0) scale(-1 1)">
            <path d="M36.8 85.3 c10.5 1.5 13.5 -6 9.9 -11.4 c-2.4 -3.6 -8.1 -2.1 -6.9 2.4" stroke="#3D2137" strokeWidth="11.4" strokeLinecap="round" fill="none" />
            <path d="M36.8 85.3 c10.5 1.5 13.5 -6 9.9 -11.4 c-2.4 -3.6 -8.1 -2.1 -6.9 2.4" stroke="#D98CA0" strokeWidth="5.2" strokeLinecap="round" fill="none" />
          </g>
          <ellipse cx="46" cy="97.3" rx="6.8" ry="5.1" fill="#D98CA0" stroke="#3D2137" strokeWidth="4.2" />
          <ellipse cx="66" cy="97.3" rx="6.8" ry="5.1" fill="#D98CA0" stroke="#3D2137" strokeWidth="4.2" />
          <ellipse cx="56" cy="77.5" rx="20" ry="23" fill="#D98CA0" stroke="#3D2137" strokeWidth="4.2" />
          <path d="M44 21 C23.5 11 14.5 33.5 23 44 C30 48.5 40 38 44 21 Z" fill="#D98CA0" stroke="#3D2137" strokeWidth="4.2" strokeLinejoin="round" />
          <path d="M37 24.5 C26.5 22 22.5 32.5 28 40" stroke="#F0B6C4" strokeWidth="3.4" fill="none" strokeLinecap="round" opacity=".75" />
          <path d="M68 21 C88.5 11 97.5 33.5 89 44 C82 48.5 72 38 68 21 Z" fill="#D98CA0" stroke="#3D2137" strokeWidth="4.2" strokeLinejoin="round" />
          <path d="M75 24.5 C85.5 22 89.5 32.5 84 40" stroke="#F0B6C4" strokeWidth="3.4" fill="none" strokeLinecap="round" opacity=".75" />
          <circle cx="56" cy="42" r="25" fill="#D98CA0" stroke="#3D2137" strokeWidth="4.2" />
          <path d="M37.2 31.8 L52.2 26.8" stroke="#3D2137" strokeWidth="3.2" strokeLinecap="round" />
          <path d="M59.8 26.8 L74.8 31.8" stroke="#3D2137" strokeWidth="3.2" strokeLinecap="round" />
          <path d="M38 44.2 h13.5" stroke="#3D2137" strokeWidth="3.6" fill="none" strokeLinecap="round" />
          <path d="M60.5 44.2 h13.5" stroke="#3D2137" strokeWidth="3.6" fill="none" strokeLinecap="round" />
          <ellipse cx="56" cy="52" rx="13" ry="6.5" fill="#F0B6C4" stroke="#3D2137" strokeWidth="4.2" />
          <ellipse cx="51.6" cy="52" rx="2.2" ry="2.2" fill="#3D2137" />
          <ellipse cx="60.4" cy="52" rx="2.2" ry="2.2" fill="#3D2137" />
          <path d="M51 61.5 q2.5 -5.4 5 0 q2.5 5.4 5 0" stroke="#3D2137" strokeWidth="3.2" fill="none" strokeLinecap="round" />
          <ellipse cx="38.5" cy="55" rx="5.2" ry="3.9" fill="#C8536F" opacity="0.9" />
          <ellipse cx="73.5" cy="55" rx="5.2" ry="3.9" fill="#C8536F" opacity="0.9" />
          <path d="M44 85.3 C51.6 89 60.4 89 67.6 86.2" stroke="#3D2137" strokeWidth="9.6" strokeLinecap="round" fill="none" />
          <path d="M44 85.3 C51.6 89 60.4 89 67.6 86.2" stroke="#D98CA0" strokeWidth="4.7" strokeLinecap="round" fill="none" />
          <path d="M68 81.2 C60.4 84.4 51.6 84.4 44.4 81.6" stroke="#3D2137" strokeWidth="9.6" strokeLinecap="round" fill="none" />
          <path d="M68 81.2 C60.4 84.4 51.6 84.4 44.4 81.6" stroke="#D98CA0" strokeWidth="4.7" strokeLinecap="round" fill="none" />
          <ellipse cx="68" cy="86.2" rx="4.5" ry="3.9" fill="#D98CA0" stroke="#3D2137" strokeWidth="3.4" transform="rotate(16 68 86.2)" />
          <ellipse cx="44" cy="81.6" rx="4.5" ry="3.9" fill="#D98CA0" stroke="#3D2137" strokeWidth="3.4" transform="rotate(-16 44 81.6)" />
        </g>
      </g>
    </Board>
  );
}

/* Cheek kiss — poppy-truffle/cheek-kiss */
export function PoppyTruffleCheekKiss(props) {
  return (
    <Board {...props}>
      <g className="an-startle">
        <path d="M95.4 82.7 c9.8 -1.5 12.8 -9 9.6 -14 c-2.7 -4.4 -9.3 -3.3 -9 1.8 c.3 4.5 5.4 6.3 9.6 3.9" stroke="#3D2137" strokeWidth="11.4" strokeLinecap="round" fill="none" />
        <path d="M95.4 82.7 c9.8 -1.5 12.8 -9 9.6 -14 c-2.7 -4.4 -9.3 -3.3 -9 1.8 c.3 4.5 5.4 6.3 9.6 3.9" stroke="#D98CA0" strokeWidth="5.2" strokeLinecap="round" fill="none" />
        <ellipse cx="72" cy="92.2" rx="5.4" ry="4" fill="#D98CA0" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="88" cy="92.2" rx="5.4" ry="4" fill="#D98CA0" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="80" cy="76.4" rx="16" ry="18.4" fill="#D98CA0" stroke="#3D2137" strokeWidth="4.2" />
        <path d="M70.4 31.2 C54 23.2 46.8 41.2 53.6 49.6 C59.2 53.2 67.2 44.8 70.4 31.2 Z" fill="#D98CA0" stroke="#3D2137" strokeWidth="4.2" strokeLinejoin="round" />
        <path d="M64.8 34 C56.4 32 53.2 40.4 57.6 46.4" stroke="#F0B6C4" strokeWidth="3.4" fill="none" strokeLinecap="round" opacity=".75" />
        <path d="M89.6 31.2 C106 23.2 113.2 41.2 106.4 49.6 C100.8 53.2 92.8 44.8 89.6 31.2 Z" fill="#D98CA0" stroke="#3D2137" strokeWidth="4.2" strokeLinejoin="round" />
        <path d="M95.2 34 C103.6 32 106.8 40.4 102.4 46.4" stroke="#F0B6C4" strokeWidth="3.4" fill="none" strokeLinecap="round" opacity=".75" />
        <circle cx="80" cy="48" r="20" fill="#D98CA0" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="71" cy="49.8" rx="7" ry="7.9" fill="#3D2137" />
        <circle cx="68.6" cy="46.9" r="3.2" fill="#FFFFFF" />
        <circle cx="73.4" cy="52.2" r="1.7" fill="#FFFFFF" opacity=".92" />
        <ellipse cx="89" cy="49.8" rx="7" ry="7.9" fill="#3D2137" />
        <circle cx="86.6" cy="46.9" r="3.2" fill="#FFFFFF" />
        <circle cx="91.4" cy="52.2" r="1.7" fill="#FFFFFF" opacity=".92" />
        <ellipse cx="80" cy="56" rx="8.8" ry="6.6" fill="#F0B6C4" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="77" cy="56" rx="1.5" ry="2.2" fill="#3D2137" />
        <ellipse cx="83" cy="56" rx="1.5" ry="2.2" fill="#3D2137" />
        <path d="M77.4 64 q2.6 2.8 5.2 0" stroke="#3D2137" strokeWidth="3" fill="none" strokeLinecap="round" />
        <ellipse cx="66" cy="58.4" rx="4.2" ry="3.1" fill="#C8536F" opacity="0.9" />
        <ellipse cx="94" cy="58.4" rx="4.2" ry="3.1" fill="#C8536F" opacity="0.9" />
        <ellipse cx="66" cy="58.4" rx="5.7" ry="4.2" fill="#C8536F" opacity="0.9" />
        <ellipse cx="94" cy="58.4" rx="5.7" ry="4.2" fill="#C8536F" opacity="0.9" />
      </g>
      <g className="an-lean">
        <g transform="rotate(11 34 62)">
          <ellipse cx="26.8" cy="97.8" rx="4.9" ry="3.6" fill="#F5A8B8" stroke="#3D2137" strokeWidth="4.2" />
          <ellipse cx="41.2" cy="97.8" rx="4.9" ry="3.6" fill="#F5A8B8" stroke="#3D2137" strokeWidth="4.2" />
          <ellipse cx="34" cy="83.6" rx="14.4" ry="16.6" fill="#F5A8B8" stroke="#3D2137" strokeWidth="4.2" />
          <path d="M27.5 46.8 C26.8 39.6 21.9 37.3 20.1 34.4 C17.3 39.8 16.4 42.9 17.8 48.6 Z" fill="#F5A8B8" stroke="#3D2137" strokeWidth="4.2" strokeLinejoin="round" />
          <path d="M23.2 46.1 C23.6 40.4 21.6 39.1 20.9 36.9" stroke="#FFCFD9" strokeWidth="3.6" fill="none" strokeLinecap="round" opacity=".8" />
          <path d="M40.5 46.8 C41.2 39.6 46.1 37.3 47.9 34.4 C50.7 39.8 51.6 42.9 50.2 48.6 Z" fill="#F5A8B8" stroke="#3D2137" strokeWidth="4.2" strokeLinejoin="round" />
          <path d="M44.8 46.1 C44.4 40.4 46.4 39.1 47.1 36.9" stroke="#FFCFD9" strokeWidth="3.6" fill="none" strokeLinecap="round" opacity=".8" />
          <circle cx="34" cy="58" r="18" fill="#F5A8B8" stroke="#3D2137" strokeWidth="4.2" />
          <path d="M20.5 59.6 q5.4 -8.1 10.8 0" stroke="#3D2137" strokeWidth="3.6" fill="none" strokeLinecap="round" />
          <path d="M36.7 59.6 q5.4 -8.1 10.8 0" stroke="#3D2137" strokeWidth="3.6" fill="none" strokeLinecap="round" />
          <ellipse cx="38" cy="64.2" rx="8.6" ry="5.3" fill="#FFCFD9" stroke="#3D2137" strokeWidth="4.2" />
          <ellipse cx="35.1" cy="64.2" rx="1.5" ry="1.8" fill="#3D2137" />
          <ellipse cx="40.9" cy="64.2" rx="1.5" ry="1.8" fill="#3D2137" />
          <ellipse cx="34" cy="72.4" rx="2" ry="2.5" fill="#7A2E44" stroke="#3D2137" strokeWidth="3" />
          <ellipse cx="21.4" cy="67.4" rx="3.8" ry="2.8" fill="#F2748C" opacity="0.9" />
          <ellipse cx="46.6" cy="67.4" rx="3.8" ry="2.8" fill="#F2748C" opacity="0.9" />
        </g>
        <path d="M57 54l2.8 -3.8M61 59l4.0 -1.8M52 56l1.0 -4.2" stroke="#E85D75" strokeWidth="2.2" strokeLinecap="round" opacity=".85" />
        <circle cx="55" cy="60" r="1.9" fill="#FFD9E2" stroke="#3D2137" strokeWidth="1.4" />
      </g>
      <g className="an-bob">
        <path d="M104 22.1 C101.4 19.7 99.5 17.8 99.5 16.3 C99.5 14.4 101.8 13.6 102.9 15 C103.4 15.7 103.7 16 104 16.2 C104.3 16 104.6 15.7 105.1 15 C106.2 13.6 108.5 14.4 108.5 16.3 C108.5 17.8 106.6 19.7 104 22.1 Z" fill="#E85D75" stroke="#3D2137" strokeWidth="3.2" strokeLinejoin="round" />
      </g>
      <g className="an-bob an-d2">
        <path d="M94 6.8 C92.2 5.2 90.9 3.9 90.9 2.8 C90.9 1.5 92.5 0.9 93.2 1.9 C93.6 2.4 93.8 2.6 94 2.8 C94.2 2.6 94.4 2.4 94.8 1.9 C95.5 0.9 97.1 1.5 97.1 2.8 C97.1 3.9 95.8 5.2 94 6.8 Z" fill="#E85D75" stroke="#3D2137" strokeWidth="3.2" strokeLinejoin="round" />
      </g>
    </Board>
  );
}

/* Head pat — poppy-truffle/head-pat */
export function PoppyTruffleHeadPat(props) {
  return (
    <Board {...props}>
      <g className="an-melt">
        <g transform="translate(45.3 0) scale(-1 1)">
          <path d="M22.6 96.7 c9 0 12 -6 9.6 -10.5 c-2.1 -3.9 -8.1 -3.3 -8.4 1.2 c-.3 3.9 3.9 6 7.5 4.5" stroke="#3D2137" strokeWidth="11.4" strokeLinecap="round" fill="none" />
          <path d="M22.6 96.7 c9 0 12 -6 9.6 -10.5 c-2.1 -3.9 -8.1 -3.3 -8.4 1.2 c-.3 3.9 3.9 6 7.5 4.5" stroke="#F5A8B8" strokeWidth="5.2" strokeLinecap="round" fill="none" />
        </g>
        <ellipse cx="30" cy="106.2" rx="5.4" ry="4" fill="#F5A8B8" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="46" cy="106.2" rx="5.4" ry="4" fill="#F5A8B8" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="38" cy="90.4" rx="16" ry="18.4" fill="#F5A8B8" stroke="#3D2137" strokeWidth="4.2" />
        <path d="M30.8 49.6 C30 41.6 25.8 40.2 23.8 37 C20.6 43 18.4 45.2 20 51.6 Z" fill="#F5A8B8" stroke="#3D2137" strokeWidth="4.2" strokeLinejoin="round" />
        <path d="M26 48.8 C26.4 42.4 25.4 42.2 24.6 39.8" stroke="#FFCFD9" strokeWidth="3.6" fill="none" strokeLinecap="round" opacity=".8" />
        <path d="M45.2 49.6 C46 41.6 50.2 40.2 52.2 37 C55.4 43 57.6 45.2 56 51.6 Z" fill="#F5A8B8" stroke="#3D2137" strokeWidth="4.2" strokeLinejoin="round" />
        <path d="M50 48.8 C49.6 42.4 50.6 42.2 51.4 39.8" stroke="#FFCFD9" strokeWidth="3.6" fill="none" strokeLinecap="round" opacity=".8" />
        <circle cx="38" cy="62" r="20" fill="#F5A8B8" stroke="#3D2137" strokeWidth="4.2" />
        <path d="M23 63.8 q6 -9 12 0" stroke="#3D2137" strokeWidth="3.6" fill="none" strokeLinecap="round" />
        <path d="M41 63.8 q6 -9 12 0" stroke="#3D2137" strokeWidth="3.6" fill="none" strokeLinecap="round" />
        <ellipse cx="38" cy="70" rx="8.8" ry="6.6" fill="#FFCFD9" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="35" cy="70" rx="1.5" ry="2.2" fill="#3D2137" />
        <ellipse cx="41" cy="70" rx="1.5" ry="2.2" fill="#3D2137" />
        <path d="M35.4 78 q2.6 2.8 5.2 0" stroke="#3D2137" strokeWidth="3" fill="none" strokeLinecap="round" />
        <ellipse cx="24" cy="72.4" rx="4.2" ry="3.1" fill="#F2748C" opacity="0.9" />
        <ellipse cx="52" cy="72.4" rx="4.2" ry="3.1" fill="#F2748C" opacity="0.9" />
      </g>
      <ellipse cx="85.2" cy="91.6" rx="4.6" ry="3.4" fill="#D98CA0" stroke="#3D2137" strokeWidth="4.2" />
      <ellipse cx="98.8" cy="91.6" rx="4.6" ry="3.4" fill="#D98CA0" stroke="#3D2137" strokeWidth="4.2" />
      <ellipse cx="92" cy="78.1" rx="13.6" ry="15.6" fill="#D98CA0" stroke="#3D2137" strokeWidth="4.2" />
      <path d="M83.8 39.7 C69.9 32.9 63.8 48.2 69.6 55.4 C74.3 58.4 81.1 51.3 83.8 39.7 Z" fill="#D98CA0" stroke="#3D2137" strokeWidth="4.2" strokeLinejoin="round" />
      <path d="M79.1 42.1 C71.9 40.4 69.2 47.5 73 52.6" stroke="#F0B6C4" strokeWidth="3.4" fill="none" strokeLinecap="round" opacity=".75" />
      <path d="M100.2 39.7 C114.1 32.9 120.2 48.2 114.4 55.4 C109.7 58.4 102.9 51.3 100.2 39.7 Z" fill="#D98CA0" stroke="#3D2137" strokeWidth="4.2" strokeLinejoin="round" />
      <path d="M104.9 42.1 C112.1 40.4 114.8 47.5 111 52.6" stroke="#F0B6C4" strokeWidth="3.4" fill="none" strokeLinecap="round" opacity=".75" />
      <circle cx="92" cy="54" r="17" fill="#D98CA0" stroke="#3D2137" strokeWidth="4.2" />
      <path d="M79.2 55.5 q5.1 -7.6 10.2 0" stroke="#3D2137" strokeWidth="3.6" fill="none" strokeLinecap="round" />
      <path d="M94.6 55.5 q5.1 -7.6 10.2 0" stroke="#3D2137" strokeWidth="3.6" fill="none" strokeLinecap="round" />
      <ellipse cx="92" cy="60.8" rx="7.5" ry="5.6" fill="#F0B6C4" stroke="#3D2137" strokeWidth="4.2" />
      <ellipse cx="89.5" cy="60.8" rx="1.3" ry="1.9" fill="#3D2137" />
      <ellipse cx="94.5" cy="60.8" rx="1.3" ry="1.9" fill="#3D2137" />
      <path d="M89.8 67.6 q2.2 2.4 4.4 0" stroke="#3D2137" strokeWidth="3" fill="none" strokeLinecap="round" />
      <ellipse cx="80.1" cy="62.8" rx="3.6" ry="2.6" fill="#C8536F" opacity="0.9" />
      <ellipse cx="103.9" cy="62.8" rx="3.6" ry="2.6" fill="#C8536F" opacity="0.9" />
      <g className="an-pat">
        <path d="M80 70 C72 58 60 46 50 42" stroke="#3D2137" strokeWidth="10.2" strokeLinecap="round" fill="none" />
        <path d="M80 70 C72 58 60 46 50 42" stroke="#D98CA0" strokeWidth="5" strokeLinecap="round" fill="none" />
        <g transform="rotate(-32 45 40)">
          <ellipse cx="45" cy="40" rx="8.6" ry="5.4" fill="#D98CA0" stroke="#3D2137" strokeWidth="4.2" />
          <circle cx="40.1" cy="42.4" r="1.9" fill="#F0B6C4" />
          <circle cx="45" cy="43.1" r="1.9" fill="#F0B6C4" />
          <circle cx="49.9" cy="42.4" r="1.9" fill="#F0B6C4" />
        </g>
      </g>
      <g className="an-twinkle">
        <path d="M8 37.8 q0.8 2.6 4.2 4.2 q-2.6 0.8 -4.2 4.2 q-0.8 -2.6 -4.2 -4.2 q2.6 -0.8 4.2 -4.2Z" fill="#F2B880" opacity="1" />
      </g>
      <g className="an-twinkle an-d2">
        <path d="M66 18.6 q0.6 2.1 3.4 3.4 q-2.1 0.6 -3.4 3.4 q-0.6 -2.1 -3.4 -3.4 q2.1 -0.6 3.4 -3.4Z" fill="#F2B880" opacity="1" />
      </g>
    </Board>
  );
}

/* Forgive me? — poppy-truffle/forgive-sign */
export function PoppyTruffleForgiveSign(props) {
  return (
    <Board {...props}>
      <g className="an-tilt">
        <path d="M77.7 79.9 c9 0 12 -6 9.6 -10.5 c-2.1 -3.9 -8.1 -3.3 -8.4 1.2 c-.3 3.9 3.9 6 7.5 4.5" stroke="#3D2137" strokeWidth="11.4" strokeLinecap="round" fill="none" />
        <path d="M77.7 79.9 c9 0 12 -6 9.6 -10.5 c-2.1 -3.9 -8.1 -3.3 -8.4 1.2 c-.3 3.9 3.9 6 7.5 4.5" stroke="#F5A8B8" strokeWidth="5.2" strokeLinecap="round" fill="none" />
        <ellipse cx="50.8" cy="90.9" rx="6.3" ry="4.7" fill="#F5A8B8" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="69.2" cy="90.9" rx="6.3" ry="4.7" fill="#F5A8B8" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="60" cy="72.7" rx="18.4" ry="21.2" fill="#F5A8B8" stroke="#3D2137" strokeWidth="4.2" />
        <path d="M51.7 25.7 C50.8 16.5 44.6 13.5 42.3 9.9 C38.6 16.8 37.5 20.7 39.3 28 Z" fill="#F5A8B8" stroke="#3D2137" strokeWidth="4.2" strokeLinejoin="round" />
        <path d="M46.2 24.8 C46.7 17.5 44.1 15.8 43.2 13.1" stroke="#FFCFD9" strokeWidth="3.6" fill="none" strokeLinecap="round" opacity=".8" />
        <path d="M68.3 25.7 C69.2 16.5 75.4 13.5 77.7 9.9 C81.4 16.8 82.5 20.7 80.7 28 Z" fill="#F5A8B8" stroke="#3D2137" strokeWidth="4.2" strokeLinejoin="round" />
        <path d="M73.8 24.8 C73.3 17.5 75.9 15.8 76.8 13.1" stroke="#FFCFD9" strokeWidth="3.6" fill="none" strokeLinecap="round" opacity=".8" />
        <circle cx="60" cy="40" r="23" fill="#F5A8B8" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="49.6" cy="42.1" rx="8.6" ry="9.8" fill="#3D2137" />
        <circle cx="46.7" cy="38.6" r="3.9" fill="#FFFFFF" />
        <circle cx="52.6" cy="45" r="2.1" fill="#FFFFFF" opacity=".92" />
        <ellipse cx="70.3" cy="42.1" rx="8.6" ry="9.8" fill="#3D2137" />
        <circle cx="67.4" cy="38.6" r="3.9" fill="#FFFFFF" />
        <circle cx="73.3" cy="45" r="2.1" fill="#FFFFFF" opacity=".92" />
        <ellipse cx="60" cy="49.2" rx="10.7" ry="7.1" fill="#FFCFD9" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="56.4" cy="49.2" rx="1.8" ry="2.4" fill="#3D2137" />
        <ellipse cx="63.6" cy="49.2" rx="1.8" ry="2.4" fill="#3D2137" />
        <path d="M55.4 58.4 q1.2 -2.2 2.3 0 q1.2 2.2 2.3 0 q1.2 -2.2 2.3 0 q1.2 2.2 2.3 0" stroke="#3D2137" strokeWidth="3" fill="none" strokeLinecap="round" />
        <ellipse cx="43.9" cy="52" rx="4.8" ry="3.6" fill="#F2748C" opacity="0.9" />
        <ellipse cx="76.1" cy="52" rx="4.8" ry="3.6" fill="#F2748C" opacity="0.9" />
        <path d="M44.2 66.3 Q39.4 69.9 27 72" stroke="#3D2137" strokeWidth="11.2" strokeLinecap="round" fill="none" />
        <path d="M44.2 66.3 Q39.4 69.9 27 72" stroke="#F5A8B8" strokeWidth="5.4" strokeLinecap="round" fill="none" />
        <path d="M75.8 66.3 Q86.6 69.9 93 72" stroke="#3D2137" strokeWidth="11.2" strokeLinecap="round" fill="none" />
        <path d="M75.8 66.3 Q86.6 69.9 93 72" stroke="#F5A8B8" strokeWidth="5.4" strokeLinecap="round" fill="none" />
        <rect x="19" y="68" width="82" height="32" rx="11" fill="#FFF7F2" stroke="#3D2137" strokeWidth="4.2" />
        <text x="60" y="89.1" textAnchor="middle" className="hand" fontSize="11.0" textLength="64.0" lengthAdjust="spacingAndGlyphs" fill="#E85D75">forgive me?</text>
        <ellipse cx="27" cy="67" rx="6.5" ry="5.6" fill="#F5A8B8" stroke="#3D2137" strokeWidth="3.4" transform="rotate(-18 27 67)" />
        <ellipse cx="93" cy="67" rx="6.5" ry="5.6" fill="#F5A8B8" stroke="#3D2137" strokeWidth="3.4" transform="rotate(18 93 67)" />
      </g>
    </Board>
  );
}

/* Sulk & rain — poppy-truffle/sulk-rain */
export function PoppyTruffleSulkRain(props) {
  return (
    <Board {...props}>
      <g className="an-cloud">
        <path d="M20.1 17a8.4 8.4 0 0 1 14.3 -4.2 8 8 0 0 1 12.6 3.4 7.1 7.1 0 0 1 -1.7 13.4H23.4 a7.6 7.6 0 0 1 -3.4 -12.6Z" fill="#D5CDE6" stroke="#3D2137" strokeWidth="4.2" strokeLinejoin="round" />
      </g>
      <g className="an-rain">
        <path d="M23 34 v9" stroke="#BFD6F5" strokeWidth="4.6" strokeLinecap="round" />
      </g>
      <g className="an-rain an-d2">
        <path d="M31 34 v9" stroke="#BFD6F5" strokeWidth="4.6" strokeLinecap="round" />
      </g>
      <g className="an-rain an-d3">
        <path d="M39 34 v9" stroke="#BFD6F5" strokeWidth="4.6" strokeLinecap="round" />
      </g>
      <g transform="rotate(-6 31 84)">
        <path d="M44.1 95.5 c8 3.5 10 10 8 16.5" stroke="#3D2137" strokeWidth="11.4" strokeLinecap="round" fill="none" />
        <path d="M44.1 95.5 c8 3.5 10 10 8 16.5" stroke="#D98CA0" strokeWidth="5.2" strokeLinecap="round" fill="none" />
        <ellipse cx="24.2" cy="103.6" rx="4.6" ry="3.4" fill="#D98CA0" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="37.8" cy="103.6" rx="4.6" ry="3.4" fill="#D98CA0" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="31" cy="90.1" rx="13.6" ry="15.6" fill="#D98CA0" stroke="#3D2137" strokeWidth="4.2" />
        <path d="M22.8 51.7 C8.9 44.9 2.8 60.2 8.6 67.4 C13.3 70.4 20.1 63.3 22.8 51.7 Z" fill="#D98CA0" stroke="#3D2137" strokeWidth="4.2" strokeLinejoin="round" />
        <path d="M18.1 54.1 C10.9 52.4 8.2 59.5 12 64.6" stroke="#F0B6C4" strokeWidth="3.4" fill="none" strokeLinecap="round" opacity=".75" />
        <path d="M39.2 51.7 C53.1 44.9 59.2 60.2 53.4 67.4 C48.7 70.4 41.9 63.3 39.2 51.7 Z" fill="#D98CA0" stroke="#3D2137" strokeWidth="4.2" strokeLinejoin="round" />
        <path d="M43.9 54.1 C51.1 52.4 53.8 59.5 50 64.6" stroke="#F0B6C4" strokeWidth="3.4" fill="none" strokeLinecap="round" opacity=".75" />
        <circle cx="31" cy="66" r="17" fill="#D98CA0" stroke="#3D2137" strokeWidth="4.2" />
        <path d="M18.8 67.5 h9.2" stroke="#3D2137" strokeWidth="3.6" fill="none" strokeLinecap="round" />
        <path d="M34.1 67.5 h9.2" stroke="#3D2137" strokeWidth="3.6" fill="none" strokeLinecap="round" />
        <ellipse cx="31" cy="72.8" rx="8.3" ry="4.9" fill="#F0B6C4" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="28.2" cy="72.8" rx="1.4" ry="1.7" fill="#3D2137" />
        <ellipse cx="33.8" cy="72.8" rx="1.4" ry="1.7" fill="#3D2137" />
        <path d="M28.8 80.3 q2.2 -2.4 4.4 0" stroke="#3D2137" strokeWidth="3.4" fill="none" strokeLinecap="round" />
      </g>
      <ellipse cx="81.2" cy="101.6" rx="4.6" ry="3.4" fill="#F5A8B8" stroke="#3D2137" strokeWidth="4.2" />
      <ellipse cx="94.8" cy="101.6" rx="4.6" ry="3.4" fill="#F5A8B8" stroke="#3D2137" strokeWidth="4.2" />
      <ellipse cx="88" cy="88.1" rx="13.6" ry="15.6" fill="#F5A8B8" stroke="#3D2137" strokeWidth="4.2" />
      <path d="M81.9 53.5 C81.2 46.7 78 45.8 76.3 43.1 C73.5 48.2 71.3 49.7 72.7 55.2 Z" fill="#F5A8B8" stroke="#3D2137" strokeWidth="4.2" strokeLinejoin="round" />
      <path d="M77.8 52.8 C78.1 47.3 77.6 47.5 77 45.5" stroke="#FFCFD9" strokeWidth="3.6" fill="none" strokeLinecap="round" opacity=".8" />
      <path d="M94.1 53.5 C94.8 46.7 98 45.8 99.7 43.1 C102.5 48.2 104.7 49.7 103.3 55.2 Z" fill="#F5A8B8" stroke="#3D2137" strokeWidth="4.2" strokeLinejoin="round" />
      <path d="M98.2 52.8 C97.9 47.3 98.4 47.5 99 45.5" stroke="#FFCFD9" strokeWidth="3.6" fill="none" strokeLinecap="round" opacity=".8" />
      <circle cx="88" cy="64" r="17" fill="#F5A8B8" stroke="#3D2137" strokeWidth="4.2" />
      <path d="M75.2 67.3 q5.1 6.6 10.2 0" stroke="#3D2137" strokeWidth="3.6" fill="none" strokeLinecap="round" />
      <path d="M90.6 67.3 q5.1 6.6 10.2 0" stroke="#3D2137" strokeWidth="3.6" fill="none" strokeLinecap="round" />
      <ellipse cx="88" cy="70.8" rx="7.5" ry="5.6" fill="#FFCFD9" stroke="#3D2137" strokeWidth="4.2" />
      <ellipse cx="85.5" cy="70.8" rx="1.3" ry="1.9" fill="#3D2137" />
      <ellipse cx="90.5" cy="70.8" rx="1.3" ry="1.9" fill="#3D2137" />
      <path d="M86 77.6 h4.1" stroke="#3D2137" strokeWidth="3.6" fill="none" strokeLinecap="round" />
      <ellipse cx="76.1" cy="72.8" rx="3.6" ry="2.6" fill="#F2748C" opacity="0.9" />
      <ellipse cx="99.9" cy="72.8" rx="3.6" ry="2.6" fill="#F2748C" opacity="0.9" />
      <path d="M72 92 C66 90 62 91 58 92" stroke="#3D2137" strokeWidth="10.4" strokeLinecap="round" fill="none" />
      <path d="M72 92 C66 90 62 91 58 92" stroke="#F5A8B8" strokeWidth="5.2" strokeLinecap="round" fill="none" />
      <g transform="rotate(12 53 92)">
        <ellipse cx="53" cy="92" rx="7.8" ry="5.2" fill="#F5A8B8" stroke="#3D2137" strokeWidth="4.2" />
        <circle cx="48.6" cy="94.3" r="1.9" fill="#FFCFD9" />
        <circle cx="53" cy="95" r="1.9" fill="#FFCFD9" />
        <circle cx="57.4" cy="94.3" r="1.9" fill="#FFCFD9" />
      </g>
    </Board>
  );
}

/* Made up — poppy-truffle/made-up */
export function PoppyTruffleMadeUp(props) {
  return (
    <Board {...props}>
      <g className="an-cheer">
        <g transform="translate(42.8 0) scale(-1 1)">
          <path d="M21.4 84.9 c9.8 -1.5 12.8 -9 9.6 -14 c-2.7 -4.4 -9.3 -3.3 -9 1.8 c.3 4.5 5.4 6.3 9.6 3.9" stroke="#3D2137" strokeWidth="11.4" strokeLinecap="round" fill="none" />
          <path d="M21.4 84.9 c9.8 -1.5 12.8 -9 9.6 -14 c-2.7 -4.4 -9.3 -3.3 -9 1.8 c.3 4.5 5.4 6.3 9.6 3.9" stroke="#F5A8B8" strokeWidth="5.2" strokeLinecap="round" fill="none" />
        </g>
        <ellipse cx="28.4" cy="94" rx="5.2" ry="3.8" fill="#F5A8B8" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="43.6" cy="94" rx="5.2" ry="3.8" fill="#F5A8B8" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="36" cy="79" rx="15.2" ry="17.5" fill="#F5A8B8" stroke="#3D2137" strokeWidth="4.2" />
        <path d="M29.2 40.2 C28.4 32.6 22.1 29 20.2 26 C17.2 31.7 17.4 36 18.9 42.1 Z" fill="#F5A8B8" stroke="#3D2137" strokeWidth="4.2" strokeLinejoin="round" />
        <path d="M24.6 39.5 C25 33.4 21.7 30.9 21 28.6" stroke="#FFCFD9" strokeWidth="3.6" fill="none" strokeLinecap="round" opacity=".8" />
        <path d="M42.8 40.2 C43.6 32.6 49.9 29 51.8 26 C54.8 31.7 54.6 36 53.1 42.1 Z" fill="#F5A8B8" stroke="#3D2137" strokeWidth="4.2" strokeLinejoin="round" />
        <path d="M47.4 39.5 C47 33.4 50.2 30.9 51 28.6" stroke="#FFCFD9" strokeWidth="3.6" fill="none" strokeLinecap="round" opacity=".8" />
        <circle cx="36" cy="52" r="19" fill="#F5A8B8" stroke="#3D2137" strokeWidth="4.2" />
        <path d="M21.8 53.7 q5.7 -8.6 11.4 0" stroke="#3D2137" strokeWidth="3.6" fill="none" strokeLinecap="round" />
        <path d="M38.8 53.7 q5.7 -8.6 11.4 0" stroke="#3D2137" strokeWidth="3.6" fill="none" strokeLinecap="round" />
        <ellipse cx="36" cy="59.6" rx="8.4" ry="6.3" fill="#FFCFD9" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="33.2" cy="59.6" rx="1.4" ry="2.1" fill="#3D2137" />
        <ellipse cx="38.8" cy="59.6" rx="1.4" ry="2.1" fill="#3D2137" />
        <path d="M32.2 66.1 q3.8 -2.6 7.6 0 q-0.8 4.9 -3.8 4.9 q-3 0 -3.8 -4.9Z" fill="#7A2E44" stroke="#3D2137" strokeWidth="3.2" strokeLinejoin="round" />
        <ellipse cx="22.7" cy="61.9" rx="4" ry="2.9" fill="#F2748C" opacity="0.9" />
        <ellipse cx="49.3" cy="61.9" rx="4" ry="2.9" fill="#F2748C" opacity="0.9" />
      </g>
      <g className="an-cheer an-d2">
        <path d="M98.6 86.9 c9.8 -1.5 12.8 -9 9.6 -14 c-2.7 -4.4 -9.3 -3.3 -9 1.8 c.3 4.5 5.4 6.3 9.6 3.9" stroke="#3D2137" strokeWidth="11.4" strokeLinecap="round" fill="none" />
        <path d="M98.6 86.9 c9.8 -1.5 12.8 -9 9.6 -14 c-2.7 -4.4 -9.3 -3.3 -9 1.8 c.3 4.5 5.4 6.3 9.6 3.9" stroke="#D98CA0" strokeWidth="5.2" strokeLinecap="round" fill="none" />
        <ellipse cx="76.4" cy="96" rx="5.2" ry="3.8" fill="#D98CA0" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="91.6" cy="96" rx="5.2" ry="3.8" fill="#D98CA0" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="84" cy="81" rx="15.2" ry="17.5" fill="#D98CA0" stroke="#3D2137" strokeWidth="4.2" />
        <path d="M74.9 38 C59.3 30.4 52.5 47.5 58.9 55.5 C64.2 58.9 71.8 51 74.9 38 Z" fill="#D98CA0" stroke="#3D2137" strokeWidth="4.2" strokeLinejoin="round" />
        <path d="M69.6 40.7 C61.6 38.8 58.5 46.8 62.7 52.5" stroke="#F0B6C4" strokeWidth="3.4" fill="none" strokeLinecap="round" opacity=".75" />
        <path d="M93.1 38 C108.7 30.4 115.5 47.5 109.1 55.5 C103.8 58.9 96.2 51 93.1 38 Z" fill="#D98CA0" stroke="#3D2137" strokeWidth="4.2" strokeLinejoin="round" />
        <path d="M98.4 40.7 C106.4 38.8 109.5 46.8 105.3 52.5" stroke="#F0B6C4" strokeWidth="3.4" fill="none" strokeLinecap="round" opacity=".75" />
        <circle cx="84" cy="54" r="19" fill="#D98CA0" stroke="#3D2137" strokeWidth="4.2" />
        <path d="M69.8 55.7 q5.7 -8.6 11.4 0" stroke="#3D2137" strokeWidth="3.6" fill="none" strokeLinecap="round" />
        <path d="M86.8 55.7 q5.7 -8.6 11.4 0" stroke="#3D2137" strokeWidth="3.6" fill="none" strokeLinecap="round" />
        <ellipse cx="84" cy="61.6" rx="8.4" ry="6.3" fill="#F0B6C4" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="81.2" cy="61.6" rx="1.4" ry="2.1" fill="#3D2137" />
        <ellipse cx="86.8" cy="61.6" rx="1.4" ry="2.1" fill="#3D2137" />
        <path d="M80.2 68.1 q3.8 -2.6 7.6 0 q-0.8 4.9 -3.8 4.9 q-3 0 -3.8 -4.9Z" fill="#7A2E44" stroke="#3D2137" strokeWidth="3.2" strokeLinejoin="round" />
        <ellipse cx="70.7" cy="63.9" rx="4" ry="2.9" fill="#C8536F" opacity="0.9" />
        <ellipse cx="97.3" cy="63.9" rx="4" ry="2.9" fill="#C8536F" opacity="0.9" />
      </g>
      <path d="M46.6 86.3 C55.8 96.5 64.2 96.5 73.4 88.3" stroke="#3D2137" strokeWidth="11.6" strokeLinecap="round" fill="none" />
      <path d="M46.6 86.3 C55.8 96.5 64.2 96.5 73.4 88.3" stroke="#F5A8B8" strokeWidth="5.6" strokeLinecap="round" fill="none" />
      <g className="an-bob">
        <path d="M60 14.9 C56.9 12.1 54.5 9.8 54.5 7.9 C54.5 5.6 57.3 4.6 58.6 6.4 C59.3 7.2 59.7 7.5 60 7.8 C60.3 7.5 60.7 7.2 61.4 6.4 C62.7 4.6 65.5 5.6 65.5 7.9 C65.5 9.8 63.1 12.1 60 14.9 Z" fill="#E85D75" stroke="#3D2137" strokeWidth="3.2" strokeLinejoin="round" />
      </g>
      <g className="an-bob an-d2">
        <path d="M14 26.9 C12.2 25.2 10.7 23.9 10.7 22.8 C10.7 21.4 12.4 20.8 13.2 21.9 C13.6 22.3 13.8 22.5 14 22.7 C14.2 22.5 14.4 22.3 14.8 21.9 C15.6 20.8 17.3 21.4 17.3 22.8 C17.3 23.9 15.8 25.2 14 26.9 Z" fill="#E85D75" stroke="#3D2137" strokeWidth="3.2" strokeLinejoin="round" />
      </g>
      <g className="an-twinkle">
        <path d="M6 58.6 q0.6 2.1 3.4 3.4 q-2.1 0.6 -3.4 3.4 q-0.6 -2.1 -3.4 -3.4 q2.1 -0.6 3.4 -3.4Z" fill="#F2B880" opacity="1" />
      </g>
      <g className="an-twinkle an-d2">
        <path d="M114 63 q0.5 1.9 3 3 q-1.9 0.5 -3 3 q-0.5 -1.9 -3 -3 q1.9 -0.5 3 -3Z" fill="#F2B880" opacity="1" />
      </g>
    </Board>
  );
}

/* id -> component, ready for the registry in ./index.jsx */
export const COMPONENTS = {
  'poppy-truffle/begging': PoppyTruffleBegging,
  'poppy-truffle/waterfall-cry': PoppyTruffleWaterfallCry,
  'poppy-truffle/big-hug': PoppyTruffleBigHug,
  'poppy-truffle/flowers-shy': PoppyTruffleFlowersShy,
  'poppy-truffle/pouty': PoppyTrufflePouty,
  'poppy-truffle/cheek-kiss': PoppyTruffleCheekKiss,
  'poppy-truffle/head-pat': PoppyTruffleHeadPat,
  'poppy-truffle/forgive-sign': PoppyTruffleForgiveSign,
  'poppy-truffle/sulk-rain': PoppyTruffleSulkRain,
  'poppy-truffle/made-up': PoppyTruffleMadeUp,
};

export default COMPONENTS;
