/* eslint-disable */
'use client';

/**
 * Rosie & Plum 💕 — Two little hearts with arms; the most on-brand of the couples.
 *
 * AUTO-GENERATED by tools/stickers/gen_pack_jsx.py. Do not edit by hand:
 * re-run the generator instead, or the drawings drift from the sheets.
 *
 * Ten poses, one 120x120 board each, house palette and plum ink. The
 * `an-*` classes are the little motion loops; they live in globals.css and
 * switch themselves off under prefers-reduced-motion.
 */

import { Board } from './board';

/* Begging — rosie-plum/begging */
export function RosiePlumBegging(props) {
  return (
    <Board {...props}>
      <g className="an-twinkle">
        <path d="M20 37.6 q0.8 2.7 4.4 4.4 q-2.7 0.8 -4.4 4.4 q-0.8 -2.7 -4.4 -4.4 q2.7 -0.8 4.4 -4.4Z" fill="#F2B880" opacity="1" />
      </g>
      <g className="an-twinkle an-d2">
        <path d="M100 46.4 q0.6 2.2 3.6 3.6 q-2.2 0.6 -3.6 3.6 q-0.6 -2.2 -3.6 -3.6 q2.2 -0.6 3.6 -3.6Z" fill="#F2B880" opacity="1" />
      </g>
      <g className="an-bob an-d2">
        <path d="M96 25.5 c2.3 2.7 3.6 4.9 0 8.5 c-3.6 0 -3.6 -2.2 0 -8.5Z" fill="#BFD6F5" stroke="#3D2137" strokeWidth="2.2" strokeLinejoin="round" />
      </g>
      <g className="an-plead">
        <path d="M60 84.3 C44.1 69.1 32 57 32 46.9 C32 34.7 46.2 29.2 53.1 38.8 C56.3 42.8 58.4 44.8 60 46.4 C61.6 44.8 63.7 42.8 66.9 38.8 C73.8 29.2 88 34.7 88 46.9 C88 57 75.9 69.1 60 84.3 Z" fill="#E85D75" stroke="#3D2137" strokeWidth="4.2" strokeLinejoin="round" />
        <ellipse cx="60" cy="53.7" rx="17.2" ry="13.9" fill="#FFDFE6" />
        <ellipse cx="52.3" cy="52.2" rx="7" ry="7.9" fill="#3D2137" />
        <circle cx="50" cy="49.5" r="2.8" fill="#FFFFFF" />
        <circle cx="54.4" cy="54.7" r="1.5" fill="#FFFFFF" opacity="0.9" />
        <ellipse cx="67.7" cy="52.2" rx="7" ry="7.9" fill="#3D2137" />
        <circle cx="65.3" cy="49.5" r="2.8" fill="#FFFFFF" />
        <circle cx="69.8" cy="54.7" r="1.5" fill="#FFFFFF" opacity="0.9" />
        <path d="M53.1 60.8 q1.7 -2.2 3.4 0 q1.7 2.2 3.4 0 q1.7 -2.2 3.4 0 q1.7 2.2 3.4 0" stroke="#3D2137" strokeWidth="3.2" fill="none" strokeLinecap="round" />
        <ellipse cx="46.5" cy="58.3" rx="4.7" ry="3.1" fill="#FF8FA6" opacity="0.85" />
        <ellipse cx="73.5" cy="58.3" rx="4.7" ry="3.1" fill="#FF8FA6" opacity="0.85" />
        <path d="M38.8 64.1 C42 74 50 76 56 75" stroke="#3D2137" strokeWidth="14.2" strokeLinecap="round" fill="none" />
        <path d="M38.8 64.1 C42 74 50 76 56 75" stroke="#F1798D" strokeWidth="7" strokeLinecap="round" fill="none" />
        <path d="M81.2 64.1 C78 74 70 76 64 75" stroke="#3D2137" strokeWidth="14.2" strokeLinecap="round" fill="none" />
        <path d="M81.2 64.1 C78 74 70 76 64 75" stroke="#F1798D" strokeWidth="7" strokeLinecap="round" fill="none" />
        <ellipse cx="55" cy="74" rx="6" ry="5.2" fill="#F1798D" stroke="#3D2137" strokeWidth="3.4" transform="rotate(-20 55 74)" />
        <ellipse cx="65" cy="74" rx="6" ry="5.2" fill="#F1798D" stroke="#3D2137" strokeWidth="3.4" transform="rotate(20 65 74)" />
      </g>
    </Board>
  );
}

/* Waterfall cry — rosie-plum/waterfall-cry */
export function RosiePlumWaterfallCry(props) {
  return (
    <Board {...props}>
      <ellipse cx="60" cy="99" rx="26" ry="5" fill="#BFD6F5" opacity=".75" />
      <g className="an-sob">
        <ellipse cx="47.9" cy="75.1" rx="8.2" ry="5.1" fill="#F1798D" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="72.1" cy="75.1" rx="8.2" ry="5.1" fill="#F1798D" stroke="#3D2137" strokeWidth="4.2" />
        <path d="M60 76 C45.5 62.2 34.4 51.1 34.4 41.8 C34.4 30.7 47.4 25.7 53.7 34.4 C56.6 38.1 58.6 40 60 41.4 C61.4 40 63.4 38.1 66.3 34.4 C72.6 25.7 85.6 30.7 85.6 41.8 C85.6 51.1 74.5 62.2 60 76 Z" fill="#E85D75" stroke="#3D2137" strokeWidth="4.2" strokeLinejoin="round" />
        <ellipse cx="60" cy="48.1" rx="15.7" ry="12.7" fill="#FFDFE6" />
        <path d="M47.5 50.1 L53 43.3 L58.5 50.1" stroke="#3D2137" strokeWidth="3.4" fill="none" strokeLinecap="round" strokeLinejoin="round" />
        <path d="M61.5 50.1 L67 43.3 L72.5 50.1" stroke="#3D2137" strokeWidth="3.4" fill="none" strokeLinecap="round" strokeLinejoin="round" />
        <ellipse cx="60" cy="55.5" rx="5.3" ry="6.5" fill="#7A2E44" stroke="#3D2137" strokeWidth="3" />
        <ellipse cx="47.7" cy="52.2" rx="4.3" ry="2.9" fill="#FF8FA6" opacity="0.85" />
        <ellipse cx="72.3" cy="52.2" rx="4.3" ry="2.9" fill="#FF8FA6" opacity="0.85" />
      </g>
      <g className="an-stream">
        <path d="M49 50.7 v40" stroke="#BFD6F5" strokeWidth="5.8" strokeLinecap="round" opacity=".95" />
      </g>
      <g className="an-stream an-d2">
        <path d="M71 50.7 v40" stroke="#BFD6F5" strokeWidth="5.8" strokeLinecap="round" opacity=".95" />
      </g>
      <g className="an-teardrop">
        <path d="M24 43.2 c2.1 2.7 3.5 4.3 3.5 6.1 c0 2.1 -1.6 3.5 -3.5 3.5 c-2.1 0 -3.5 -1.8 -3.5 -3.5Z" fill="#BFD6F5" stroke="#3D2137" strokeWidth="2.6" strokeLinejoin="round" />
      </g>
      <g className="an-teardrop an-d3">
        <path d="M98 49.8 c1.8 2.4 3.1 3.8 3.1 5.3 c0 1.8 -1.4 3.1 -3.1 3.1 c-1.8 0 -3.1 -1.5 -3.1 -3.1Z" fill="#BFD6F5" stroke="#3D2137" strokeWidth="2.6" strokeLinejoin="round" />
      </g>
    </Board>
  );
}

/* Big hug — rosie-plum/big-hug */
export function RosiePlumBigHug(props) {
  return (
    <Board {...props}>
      <g className="an-squeeze">
        <path d="M72 78 C60 71 44 70 30 72" stroke="#3D2137" strokeWidth="14.6" strokeLinecap="round" fill="none" />
        <path d="M72 78 C60 71 44 70 30 72" stroke="#B98BB0" strokeWidth="7.2" strokeLinecap="round" fill="none" />
        <ellipse cx="26" cy="71" rx="7" ry="6" fill="#B98BB0" stroke="#3D2137" strokeWidth="3.4" transform="rotate(18 26 71)" />
        <path d="M50 80 C62 74 80 72 96 73" stroke="#3D2137" strokeWidth="14.6" strokeLinecap="round" fill="none" />
        <path d="M50 80 C62 74 80 72 96 73" stroke="#F1798D" strokeWidth="7.2" strokeLinecap="round" fill="none" />
        <ellipse cx="100" cy="72" rx="7" ry="6" fill="#F1798D" stroke="#3D2137" strokeWidth="3.4" transform="rotate(-18 100 72)" />
        <path d="M42 87.7 C28.9 75.2 18.8 65.2 18.8 56.8 C18.8 46.8 30.6 42.2 36.3 50.1 C38.9 53.5 40.7 55.1 42 56.4 C43.3 55.1 45.1 53.5 47.7 50.1 C53.4 42.2 65.2 46.8 65.2 56.8 C65.2 65.2 55.1 75.2 42 87.7 Z" fill="#E85D75" stroke="#3D2137" strokeWidth="4.2" strokeLinejoin="round" />
        <ellipse cx="42" cy="62.4" rx="14.2" ry="11.5" fill="#FFDFE6" />
        <path d="M30.9 61.2 q4.7 -6.6 9.4 0" stroke="#3D2137" strokeWidth="3.4" fill="none" strokeLinecap="round" />
        <path d="M43.6 61.2 q4.7 -6.6 9.4 0" stroke="#3D2137" strokeWidth="3.4" fill="none" strokeLinecap="round" />
        <path d="M37.8 68.3 q4.2 4.6 8.3 0" stroke="#3D2137" strokeWidth="3.4" fill="none" strokeLinecap="round" />
        <ellipse cx="30.9" cy="66.2" rx="3.8" ry="2.6" fill="#FF8FA6" opacity="0.85" />
        <ellipse cx="53.1" cy="66.2" rx="3.8" ry="2.6" fill="#FF8FA6" opacity="0.85" />
        <path d="M82 84.9 C68.2 71.7 57.6 61.1 57.6 52.3 C57.6 41.8 70 36.9 76 45.3 C78.8 48.8 80.6 50.6 82 51.9 C83.4 50.6 85.2 48.8 88 45.3 C94 36.9 106.4 41.8 106.4 52.3 C106.4 61.1 95.8 71.7 82 84.9 Z" fill="#6B3A5F" stroke="#3D2137" strokeWidth="4.2" strokeLinejoin="round" />
        <ellipse cx="82" cy="58.3" rx="15" ry="12.1" fill="#F0DDEB" />
        <path d="M70.4 56.9 q5 -7 9.9 0" stroke="#3D2137" strokeWidth="3.4" fill="none" strokeLinecap="round" />
        <path d="M83.7 56.9 q5 -7 9.9 0" stroke="#3D2137" strokeWidth="3.4" fill="none" strokeLinecap="round" />
        <path d="M77.6 64.4 q4.4 4.8 8.7 0" stroke="#3D2137" strokeWidth="3.4" fill="none" strokeLinecap="round" />
        <ellipse cx="70.3" cy="62.2" rx="4" ry="2.7" fill="#D98CBE" opacity="0.85" />
        <ellipse cx="93.7" cy="62.2" rx="4" ry="2.7" fill="#D98CBE" opacity="0.85" />
        <path d="M72 72 C64 67 54 67 47 70" stroke="#3D2137" strokeWidth="14.2" strokeLinecap="round" fill="none" />
        <path d="M72 72 C64 67 54 67 47 70" stroke="#B98BB0" strokeWidth="7" strokeLinecap="round" fill="none" />
      </g>
      <g className="an-bob">
        <path d="M60 19.9 C56.9 17.1 54.5 14.8 54.5 12.9 C54.5 10.6 57.3 9.6 58.6 11.4 C59.3 12.2 59.7 12.5 60 12.8 C60.3 12.5 60.7 12.2 61.4 11.4 C62.7 9.6 65.5 10.6 65.5 12.9 C65.5 14.8 63.1 17.1 60 19.9 Z" fill="#E85D75" stroke="#3D2137" strokeWidth="3.2" strokeLinejoin="round" />
      </g>
      <g className="an-bob an-d2">
        <path d="M98 27.5 C95.8 25.5 94 23.9 94 22.5 C94 20.9 96.1 20.1 97 21.4 C97.5 22 97.8 22.2 98 22.4 C98.2 22.2 98.5 22 99 21.4 C99.9 20.1 102 20.9 102 22.5 C102 23.9 100.2 25.5 98 27.5 Z" fill="#E85D75" stroke="#3D2137" strokeWidth="3.2" strokeLinejoin="round" />
      </g>
    </Board>
  );
}

/* Flowers, shy — rosie-plum/flowers-shy */
export function RosiePlumFlowersShy(props) {
  return (
    <Board {...props}>
      <g className="an-shy">
        <ellipse cx="33.4" cy="86.2" rx="8.6" ry="5.3" fill="#F1798D" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="58.6" cy="86.2" rx="8.6" ry="5.3" fill="#F1798D" stroke="#3D2137" strokeWidth="4.2" />
        <path d="M46 87.2 C30.8 72.6 19.2 61 19.2 51.4 C19.2 39.7 32.8 34.4 39.4 43.6 C42.5 47.5 44.5 49.4 46 50.9 C47.5 49.4 49.5 47.5 52.6 43.6 C59.2 34.4 72.8 39.7 72.8 51.4 C72.8 61 61.2 72.6 46 87.2 Z" fill="#E85D75" stroke="#3D2137" strokeWidth="4.2" strokeLinejoin="round" />
        <ellipse cx="46" cy="57.9" rx="16.4" ry="13.3" fill="#FFDFE6" />
        <path d="M33.2 56.4 q5.5 -7.7 10.9 0" stroke="#3D2137" strokeWidth="3.4" fill="none" strokeLinecap="round" />
        <path d="M47.9 56.4 q5.5 -7.7 10.9 0" stroke="#3D2137" strokeWidth="3.4" fill="none" strokeLinecap="round" />
        <path d="M41.2 64.7 q4.8 5.3 9.6 0" stroke="#3D2137" strokeWidth="3.4" fill="none" strokeLinecap="round" />
        <ellipse cx="33.1" cy="62.2" rx="4.5" ry="3" fill="#FF8FA6" opacity="0.85" />
        <ellipse cx="58.9" cy="62.2" rx="4.5" ry="3" fill="#FF8FA6" opacity="0.85" />
        <ellipse cx="32.8" cy="63.5" rx="7.6" ry="5.2" fill="#FF8FA6" opacity="0.95" />
        <ellipse cx="59.2" cy="63.5" rx="7.6" ry="5.2" fill="#FF8FA6" opacity="0.95" />
        <path d="M66.2 67.8 C72 72 78 74 83 72" stroke="#3D2137" strokeWidth="15" strokeLinecap="round" fill="none" />
        <path d="M66.2 67.8 C72 72 78 74 83 72" stroke="#F1798D" strokeWidth="7.4" strokeLinecap="round" fill="none" />
        <ellipse cx="84" cy="74" rx="6.4" ry="5.6" fill="#F1798D" stroke="#3D2137" strokeWidth="3.4" transform="rotate(-10 84 74)" />
      </g>
      <g className="an-sway-s">
        <path d="M84 70 Q80.2 61.2 73 54" stroke="#6FA96E" strokeWidth="3.6" strokeLinecap="round" fill="none" />
        <path d="M84 70 Q84.3 55.8 85 45" stroke="#6FA96E" strokeWidth="3.6" strokeLinecap="round" fill="none" />
        <path d="M84 70 Q88.2 62.4 96 56" stroke="#6FA96E" strokeWidth="3.6" strokeLinecap="round" fill="none" />
        <path d="M81 60 l-6 3 M87 64 l6 4" stroke="#6FA96E" strokeWidth="3.2" strokeLinecap="round" fill="none" />
        <circle cx="73" cy="48.9" r="3.6" fill="#FFF3E9" stroke="#3D2137" strokeWidth="2.4" />
        <circle cx="77.8" cy="52.4" r="3.6" fill="#FFF3E9" stroke="#3D2137" strokeWidth="2.4" />
        <circle cx="76" cy="58.1" r="3.6" fill="#FFF3E9" stroke="#3D2137" strokeWidth="2.4" />
        <circle cx="70" cy="58.1" r="3.6" fill="#FFF3E9" stroke="#3D2137" strokeWidth="2.4" />
        <circle cx="68.2" cy="52.4" r="3.6" fill="#FFF3E9" stroke="#3D2137" strokeWidth="2.4" />
        <circle cx="73" cy="54" r="2.7" fill="#F2B880" stroke="#3D2137" strokeWidth="2.4" />
        <circle cx="85" cy="39.6" r="3.8" fill="#FFF3E9" stroke="#3D2137" strokeWidth="2.4" />
        <circle cx="90.1" cy="43.3" r="3.8" fill="#FFF3E9" stroke="#3D2137" strokeWidth="2.4" />
        <circle cx="88.2" cy="49.4" r="3.8" fill="#FFF3E9" stroke="#3D2137" strokeWidth="2.4" />
        <circle cx="81.8" cy="49.4" r="3.8" fill="#FFF3E9" stroke="#3D2137" strokeWidth="2.4" />
        <circle cx="79.9" cy="43.3" r="3.8" fill="#FFF3E9" stroke="#3D2137" strokeWidth="2.4" />
        <circle cx="85" cy="45" r="2.9" fill="#F2B880" stroke="#3D2137" strokeWidth="2.4" />
        <circle cx="96" cy="51.2" r="3.4" fill="#FFF3E9" stroke="#3D2137" strokeWidth="2.4" />
        <circle cx="100.5" cy="54.5" r="3.4" fill="#FFF3E9" stroke="#3D2137" strokeWidth="2.4" />
        <circle cx="98.8" cy="59.8" r="3.4" fill="#FFF3E9" stroke="#3D2137" strokeWidth="2.4" />
        <circle cx="93.2" cy="59.8" r="3.4" fill="#FFF3E9" stroke="#3D2137" strokeWidth="2.4" />
        <circle cx="91.5" cy="54.5" r="3.4" fill="#FFF3E9" stroke="#3D2137" strokeWidth="2.4" />
        <circle cx="96" cy="56" r="2.6" fill="#F2B880" stroke="#3D2137" strokeWidth="2.4" />
      </g>
      <g className="an-twinkle">
        <path d="M18 34 q0.7 2.5 4 4 q-2.5 0.7 -4 4 q-0.7 -2.5 -4 -4 q2.5 -0.7 4 -4Z" fill="#F2B880" opacity="1" />
      </g>
    </Board>
  );
}

/* Pouty — rosie-plum/pouty */
export function RosiePlumPouty(props) {
  return (
    <Board {...props}>
      <g className="an-steam">
        <path d="M96 30c6-4 3-10-2-12s-6-7-1-10" stroke="#D5CDE6" strokeWidth="5.4" strokeLinecap="round" fill="none" />
      </g>
      <g className="an-steam an-d2">
        <path d="M108 44c5-4 2-9-2-11" stroke="#D5CDE6" strokeWidth="4.6" strokeLinecap="round" fill="none" />
      </g>
      <g className="an-huff">
        <g transform="rotate(-7 58 62)">
          <path d="M58 85.5 C41.4 69.6 28.7 56.9 28.7 46.4 C28.7 33.7 43.6 27.9 50.8 37.9 C54.1 42.2 56.3 44.3 58 45.9 C59.7 44.3 61.9 42.2 65.2 37.9 C72.4 27.9 87.3 33.7 87.3 46.4 C87.3 56.9 74.6 69.6 58 85.5 Z" fill="#6B3A5F" stroke="#3D2137" strokeWidth="4.2" strokeLinejoin="round" />
          <ellipse cx="58" cy="53.5" rx="17.9" ry="14.5" fill="#F0DDEB" />
          <path d="M44.3 37.9 L55.7 43.3" stroke="#3D2137" strokeWidth="3.2" fill="none" strokeLinecap="round" />
          <path d="M60.3 43.3 L71.7 37.9" stroke="#3D2137" strokeWidth="3.2" fill="none" strokeLinecap="round" />
          <path d="M44.3 51.9 h11.3" stroke="#3D2137" strokeWidth="3.4" fill="none" strokeLinecap="round" />
          <path d="M60.3 51.9 h11.3" stroke="#3D2137" strokeWidth="3.4" fill="none" strokeLinecap="round" />
          <path d="M50 60.9 q4 -5.4 8 0 q4 5.4 8 0" stroke="#3D2137" strokeWidth="3.6" fill="none" strokeLinecap="round" />
          <ellipse cx="43.9" cy="58.3" rx="4.9" ry="3.3" fill="#D98CBE" opacity="0.85" />
          <ellipse cx="72.1" cy="58.3" rx="4.9" ry="3.3" fill="#D98CBE" opacity="0.85" />
          <path d="M34 70 C44 76 58 79 71 78" stroke="#3D2137" strokeWidth="13.4" strokeLinecap="round" fill="none" />
          <path d="M34 70 C44 76 58 79 71 78" stroke="#B98BB0" strokeWidth="6.8" strokeLinecap="round" fill="none" />
          <path d="M78 69 C68 75 54 78 41 77" stroke="#3D2137" strokeWidth="13.4" strokeLinecap="round" fill="none" />
          <path d="M78 69 C68 75 54 78 41 77" stroke="#B98BB0" strokeWidth="6.8" strokeLinecap="round" fill="none" />
          <ellipse cx="73" cy="78" rx="6.2" ry="5.4" fill="#B98BB0" stroke="#3D2137" strokeWidth="3.4" transform="rotate(14 73 78)" />
          <ellipse cx="39" cy="77" rx="6.2" ry="5.4" fill="#B98BB0" stroke="#3D2137" strokeWidth="3.4" transform="rotate(-14 39 77)" />
        </g>
      </g>
    </Board>
  );
}

/* Cheek kiss — rosie-plum/cheek-kiss */
export function RosiePlumCheekKiss(props) {
  return (
    <Board {...props}>
      <g className="an-startle">
        <ellipse cx="72.3" cy="76.4" rx="8" ry="4.9" fill="#F1798D" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="95.7" cy="76.4" rx="8" ry="4.9" fill="#F1798D" stroke="#3D2137" strokeWidth="4.2" />
        <path d="M84 77.3 C69.9 63.9 59.1 53.1 59.1 44.1 C59.1 33.4 71.8 28.4 77.9 36.9 C80.7 40.5 82.6 42.3 84 43.7 C85.4 42.3 87.3 40.5 90.1 36.9 C96.2 28.4 108.9 33.4 108.9 44.1 C108.9 53.1 98.1 63.9 84 77.3 Z" fill="#E85D75" stroke="#3D2137" strokeWidth="4.2" strokeLinejoin="round" />
        <ellipse cx="84" cy="50.2" rx="15.2" ry="12.3" fill="#FFDFE6" />
        <ellipse cx="77.2" cy="48.8" rx="6.8" ry="7.7" fill="#3D2137" />
        <circle cx="74.9" cy="46.2" r="2.7" fill="#FFFFFF" />
        <circle cx="79.2" cy="51.3" r="1.4" fill="#FFFFFF" opacity="0.9" />
        <ellipse cx="90.8" cy="48.8" rx="6.8" ry="7.7" fill="#3D2137" />
        <circle cx="88.5" cy="46.2" r="2.7" fill="#FFFFFF" />
        <circle cx="92.8" cy="51.3" r="1.4" fill="#FFFFFF" opacity="0.9" />
        <ellipse cx="84" cy="56.5" rx="4" ry="4.5" fill="#7A2E44" stroke="#3D2137" strokeWidth="3" />
        <ellipse cx="72" cy="54.2" rx="4.1" ry="2.8" fill="#FF8FA6" opacity="0.85" />
        <ellipse cx="96" cy="54.2" rx="4.1" ry="2.8" fill="#FF8FA6" opacity="0.85" />
        <ellipse cx="71.8" cy="56.2" rx="8.4" ry="5.8" fill="#FF8FA6" opacity="0.95" />
        <ellipse cx="96.2" cy="56.2" rx="7.6" ry="5.2" fill="#FF8FA6" opacity="0.95" />
      </g>
      <g className="an-lean">
        <g transform="rotate(9 30 62)">
          <ellipse cx="19.2" cy="82.7" rx="7.4" ry="4.5" fill="#B98BB0" stroke="#3D2137" strokeWidth="4.2" />
          <ellipse cx="40.8" cy="82.7" rx="7.4" ry="4.5" fill="#B98BB0" stroke="#3D2137" strokeWidth="4.2" />
          <path d="M30 83.5 C17 71.1 7.1 61.2 7.1 52.9 C7.1 43 18.8 38.4 24.4 46.3 C27 49.6 28.7 51.2 30 52.5 C31.3 51.2 33 49.6 35.6 46.3 C41.2 38.4 52.9 43 52.9 52.9 C52.9 61.2 43 71.1 30 83.5 Z" fill="#6B3A5F" stroke="#3D2137" strokeWidth="4.2" strokeLinejoin="round" />
          <ellipse cx="30" cy="58.5" rx="14.1" ry="11.4" fill="#F0DDEB" />
          <path d="M19.1 57.2 q4.7 -6.5 9.3 0" stroke="#3D2137" strokeWidth="3.4" fill="none" strokeLinecap="round" />
          <path d="M31.6 57.2 q4.7 -6.5 9.3 0" stroke="#3D2137" strokeWidth="3.4" fill="none" strokeLinecap="round" />
          <ellipse cx="30" cy="64.3" rx="3.7" ry="4.1" fill="#7A2E44" stroke="#3D2137" strokeWidth="3" />
          <ellipse cx="19" cy="62.2" rx="3.8" ry="2.6" fill="#D98CBE" opacity="0.85" />
          <ellipse cx="41" cy="62.2" rx="3.8" ry="2.6" fill="#D98CBE" opacity="0.85" />
        </g>
        <g transform="rotate(-16 66 47)">
          <ellipse cx="66" cy="47" rx="6.6" ry="5.2" fill="#FFD9E2" stroke="#3D2137" strokeWidth="3.0" />
          <path d="M61.4 47 h9.2" stroke="#3D2137" strokeWidth="2.0" strokeLinecap="round" />
        </g>
      </g>
      <g className="an-bob">
        <path d="M104 30.2 C101.4 27.8 99.3 25.8 99.3 24.2 C99.3 22.3 101.7 21.4 102.9 23 C103.4 23.6 103.7 23.9 104 24.2 C104.3 23.9 104.6 23.6 105.1 23 C106.3 21.4 108.7 22.3 108.7 24.2 C108.7 25.8 106.6 27.8 104 30.2 Z" fill="#E85D75" stroke="#3D2137" strokeWidth="3.2" strokeLinejoin="round" />
      </g>
      <g className="an-bob an-d2">
        <path d="M94 14 C92.1 12.3 90.6 10.9 90.6 9.7 C90.6 8.3 92.3 7.7 93.2 8.8 C93.6 9.3 93.8 9.5 94 9.7 C94.2 9.5 94.4 9.3 94.8 8.8 C95.7 7.7 97.4 8.3 97.4 9.7 C97.4 10.9 95.9 12.3 94 14 Z" fill="#E85D75" stroke="#3D2137" strokeWidth="3.2" strokeLinejoin="round" />
      </g>
    </Board>
  );
}

/* Head pat — rosie-plum/head-pat */
export function RosiePlumHeadPat(props) {
  return (
    <Board {...props}>
      <g className="an-melt">
        <ellipse cx="26.3" cy="100.4" rx="8" ry="4.9" fill="#F1798D" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="49.7" cy="100.4" rx="8" ry="4.9" fill="#F1798D" stroke="#3D2137" strokeWidth="4.2" />
        <path d="M38 101.3 C23.9 87.9 13.1 77.1 13.1 68.1 C13.1 57.4 25.8 52.4 31.9 60.9 C34.7 64.5 36.6 66.3 38 67.7 C39.4 66.3 41.3 64.5 44.1 60.9 C50.2 52.4 62.9 57.4 62.9 68.1 C62.9 77.1 52.1 87.9 38 101.3 Z" fill="#E85D75" stroke="#3D2137" strokeWidth="4.2" strokeLinejoin="round" />
        <ellipse cx="38" cy="74.2" rx="15.2" ry="12.3" fill="#FFDFE6" />
        <path d="M26.1 72.8 q5.1 -7.1 10.1 0" stroke="#3D2137" strokeWidth="3.4" fill="none" strokeLinecap="round" />
        <path d="M39.7 72.8 q5.1 -7.1 10.1 0" stroke="#3D2137" strokeWidth="3.4" fill="none" strokeLinecap="round" />
        <path d="M33.5 80.5 q4.5 4.9 8.9 0" stroke="#3D2137" strokeWidth="3.4" fill="none" strokeLinecap="round" />
        <ellipse cx="26" cy="78.2" rx="4.1" ry="2.8" fill="#FF8FA6" opacity="0.85" />
        <ellipse cx="50" cy="78.2" rx="4.1" ry="2.8" fill="#FF8FA6" opacity="0.85" />
      </g>
      <ellipse cx="79.7" cy="75.8" rx="7" ry="4.4" fill="#B98BB0" stroke="#3D2137" strokeWidth="4.2" />
      <ellipse cx="100.3" cy="75.8" rx="7" ry="4.4" fill="#B98BB0" stroke="#3D2137" strokeWidth="4.2" />
      <path d="M90 76.6 C77.6 64.7 68.1 55.2 68.1 47.3 C68.1 37.8 79.2 33.4 84.6 41 C87.1 44.1 88.8 45.7 90 46.9 C91.2 45.7 92.9 44.1 95.4 41 C100.8 33.4 111.9 37.8 111.9 47.3 C111.9 55.2 102.4 64.7 90 76.6 Z" fill="#6B3A5F" stroke="#3D2137" strokeWidth="4.2" strokeLinejoin="round" />
      <ellipse cx="90" cy="52.6" rx="13.5" ry="10.9" fill="#F0DDEB" />
      <path d="M79.5 51.4 q4.5 -6.3 8.9 0" stroke="#3D2137" strokeWidth="3.4" fill="none" strokeLinecap="round" />
      <path d="M91.5 51.4 q4.5 -6.3 8.9 0" stroke="#3D2137" strokeWidth="3.4" fill="none" strokeLinecap="round" />
      <path d="M86.1 58.2 q3.9 4.4 7.9 0" stroke="#3D2137" strokeWidth="3.4" fill="none" strokeLinecap="round" />
      <ellipse cx="79.4" cy="56.2" rx="3.6" ry="2.5" fill="#D98CBE" opacity="0.85" />
      <ellipse cx="100.6" cy="56.2" rx="3.6" ry="2.5" fill="#D98CBE" opacity="0.85" />
      <g className="an-pat">
        <path d="M82 68 C74 56 62 46 52 42" stroke="#3D2137" strokeWidth="13" strokeLinecap="round" fill="none" />
        <path d="M82 68 C74 56 62 46 52 42" stroke="#B98BB0" strokeWidth="6.4" strokeLinecap="round" fill="none" />
        <g transform="rotate(-34 45 41)">
          <ellipse cx="45" cy="41" rx="9.6" ry="6" fill="#B98BB0" stroke="#3D2137" strokeWidth="4.2" />
          <circle cx="39.5" cy="43.7" r="1.9" fill="#F0DDEB" />
          <circle cx="45" cy="44.5" r="1.9" fill="#F0DDEB" />
          <circle cx="50.5" cy="43.7" r="1.9" fill="#F0DDEB" />
        </g>
      </g>
      <g className="an-twinkle">
        <path d="M12 49.8 q0.8 2.6 4.2 4.2 q-2.6 0.8 -4.2 4.2 q-0.8 -2.6 -4.2 -4.2 q2.6 -0.8 4.2 -4.2Z" fill="#F2B880" opacity="1" />
      </g>
      <g className="an-twinkle an-d2">
        <path d="M66 22.6 q0.6 2.1 3.4 3.4 q-2.1 0.6 -3.4 3.4 q-0.6 -2.1 -3.4 -3.4 q2.1 -0.6 3.4 -3.4Z" fill="#F2B880" opacity="1" />
      </g>
    </Board>
  );
}

/* Forgive me? — rosie-plum/forgive-sign */
export function RosiePlumForgiveSign(props) {
  return (
    <Board {...props}>
      <ellipse cx="48.5" cy="106" rx="7.8" ry="4.8" fill="#F1798D" stroke="#3D2137" strokeWidth="4.2" />
      <ellipse cx="71.5" cy="106" rx="7.8" ry="4.8" fill="#F1798D" stroke="#3D2137" strokeWidth="4.2" />
      <path d="M60 106.9 C46.2 93.7 35.6 83.1 35.6 74.3 C35.6 63.8 48 58.9 54 67.3 C56.8 70.8 58.6 72.6 60 73.9 C61.4 72.6 63.2 70.8 66 67.3 C72 58.9 84.4 63.8 84.4 74.3 C84.4 83.1 73.8 93.7 60 106.9 Z" fill="#E85D75" stroke="#3D2137" strokeWidth="4.2" strokeLinejoin="round" />
      <ellipse cx="60" cy="80.3" rx="15" ry="12.1" fill="#FFDFE6" />
      <path d="M41.6 89.3 C34 92 33 99 37 103" stroke="#3D2137" strokeWidth="14.2" strokeLinecap="round" fill="none" />
      <path d="M41.6 89.3 C34 92 33 99 37 103" stroke="#F1798D" strokeWidth="7" strokeLinecap="round" fill="none" />
      <path d="M78.4 89.3 C86 92 87 99 83 103" stroke="#3D2137" strokeWidth="14.2" strokeLinecap="round" fill="none" />
      <path d="M78.4 89.3 C86 92 87 99 83 103" stroke="#F1798D" strokeWidth="7" strokeLinecap="round" fill="none" />
      <ellipse cx="36" cy="105" rx="6.2" ry="5.4" fill="#F1798D" stroke="#3D2137" strokeWidth="3.4" transform="rotate(-18 36 105)" />
      <ellipse cx="84" cy="105" rx="6.2" ry="5.4" fill="#F1798D" stroke="#3D2137" strokeWidth="3.4" transform="rotate(18 84 105)" />
      <g className="an-tilt">
        <path d="M60 38 V64" stroke="#3D2137" strokeWidth="6" strokeLinecap="round" />
        <rect x="8" y="4" width="104" height="38" rx="10" fill="#FFF7F2" stroke="#3D2137" strokeWidth="4.2" />
        <text x="60" y="29.8" textAnchor="middle" className="hand" fontSize="14.8" textLength="86.0" lengthAdjust="spacingAndGlyphs" fill="#E85D75">forgive me?</text>
      </g>
      <ellipse cx="53.3" cy="78.9" rx="6.1" ry="6.9" fill="#3D2137" />
      <circle cx="51.3" cy="76.6" r="2.4" fill="#FFFFFF" />
      <circle cx="55.1" cy="81.2" r="1.3" fill="#FFFFFF" opacity="0.9" />
      <ellipse cx="66.7" cy="78.9" rx="6.1" ry="6.9" fill="#3D2137" />
      <circle cx="64.6" cy="76.6" r="2.4" fill="#FFFFFF" />
      <circle cx="68.5" cy="81.2" r="1.3" fill="#FFFFFF" opacity="0.9" />
      <path d="M54 86.4 q1.5 -2.2 3 0 q1.5 2.2 3 0 q1.5 -2.2 3 0 q1.5 2.2 3 0" stroke="#3D2137" strokeWidth="3.2" fill="none" strokeLinecap="round" />
      <ellipse cx="48.3" cy="84.2" rx="4" ry="2.7" fill="#FF8FA6" opacity="0.85" />
      <ellipse cx="71.7" cy="84.2" rx="4" ry="2.7" fill="#FF8FA6" opacity="0.85" />
    </Board>
  );
}

/* Sulk & rain — rosie-plum/sulk-rain */
export function RosiePlumSulkRain(props) {
  return (
    <Board {...props}>
      <g className="an-cloud">
        <path d="M21 20a9.2 9.2 0 0 1 15.6 -4.6 8.7 8.7 0 0 1 13.8 3.7 7.8 7.8 0 0 1 -1.8 14.7H24.7 a8.3 8.3 0 0 1 -3.7 -13.8Z" fill="#D5CDE6" stroke="#3D2137" strokeWidth="4.2" strokeLinejoin="round" />
      </g>
      <g className="an-rain">
        <path d="M25 40 v9" stroke="#BFD6F5" strokeWidth="4.6" strokeLinecap="round" />
      </g>
      <g className="an-rain an-d2">
        <path d="M33 40 v9" stroke="#BFD6F5" strokeWidth="4.6" strokeLinecap="round" />
      </g>
      <g className="an-rain an-d3">
        <path d="M41 40 v9" stroke="#BFD6F5" strokeWidth="4.6" strokeLinecap="round" />
      </g>
      <g transform="rotate(-6 32 80)">
        <ellipse cx="21.6" cy="99.8" rx="7" ry="4.4" fill="#F1798D" stroke="#3D2137" strokeWidth="4.2" />
        <ellipse cx="42.4" cy="99.8" rx="7" ry="4.4" fill="#F1798D" stroke="#3D2137" strokeWidth="4.2" />
        <path d="M32 100.6 C19.6 88.7 10.1 79.2 10.1 71.3 C10.1 61.8 21.2 57.4 26.6 65 C29.1 68.1 30.8 69.7 32 70.9 C33.2 69.7 34.9 68.1 37.4 65 C42.8 57.4 53.9 61.8 53.9 71.3 C53.9 79.2 44.4 88.7 32 100.6 Z" fill="#E85D75" stroke="#3D2137" strokeWidth="4.2" strokeLinejoin="round" />
        <ellipse cx="32" cy="76.6" rx="13.5" ry="10.9" fill="#FFDFE6" />
        <path d="M21.7 75.4 h8.5" stroke="#3D2137" strokeWidth="3.4" fill="none" strokeLinecap="round" />
        <path d="M33.8 75.4 h8.5" stroke="#3D2137" strokeWidth="3.4" fill="none" strokeLinecap="round" />
        <path d="M28.1 83.4 q3.9 -4 7.9 0" stroke="#3D2137" strokeWidth="3.4" fill="none" strokeLinecap="round" />
      </g>
      <ellipse cx="77.7" cy="95.8" rx="7" ry="4.4" fill="#B98BB0" stroke="#3D2137" strokeWidth="4.2" />
      <ellipse cx="98.3" cy="95.8" rx="7" ry="4.4" fill="#B98BB0" stroke="#3D2137" strokeWidth="4.2" />
      <path d="M88 96.6 C75.6 84.7 66.1 75.2 66.1 67.3 C66.1 57.8 77.2 53.4 82.6 61 C85.1 64.1 86.8 65.7 88 66.9 C89.2 65.7 90.9 64.1 93.4 61 C98.8 53.4 109.9 57.8 109.9 67.3 C109.9 75.2 100.4 84.7 88 96.6 Z" fill="#6B3A5F" stroke="#3D2137" strokeWidth="4.2" strokeLinejoin="round" />
      <ellipse cx="88" cy="72.6" rx="13.5" ry="10.9" fill="#F0DDEB" />
      <path d="M77.5 73.7 q4.5 5.8 8.9 0" stroke="#3D2137" strokeWidth="3.4" fill="none" strokeLinecap="round" />
      <path d="M89.5 73.7 q4.5 5.8 8.9 0" stroke="#3D2137" strokeWidth="3.4" fill="none" strokeLinecap="round" />
      <path d="M84.5 78.2 h7" stroke="#3D2137" strokeWidth="3.4" fill="none" strokeLinecap="round" />
      <ellipse cx="77.4" cy="76.2" rx="3.6" ry="2.5" fill="#D98CBE" opacity="0.85" />
      <ellipse cx="98.6" cy="76.2" rx="3.6" ry="2.5" fill="#D98CBE" opacity="0.85" />
      <path d="M71.4 80.8 C68 84 64 86 61 87" stroke="#3D2137" strokeWidth="12.6" strokeLinecap="round" fill="none" />
      <path d="M71.4 80.8 C68 84 64 86 61 87" stroke="#B98BB0" strokeWidth="6.2" strokeLinecap="round" fill="none" />
      <g transform="rotate(14 56 87)">
        <ellipse cx="56" cy="87" rx="7.8" ry="5.2" fill="#B98BB0" stroke="#3D2137" strokeWidth="4.2" />
        <circle cx="51.6" cy="89.3" r="1.9" fill="#F0DDEB" />
        <circle cx="56" cy="90" r="1.9" fill="#F0DDEB" />
        <circle cx="60.4" cy="89.3" r="1.9" fill="#F0DDEB" />
      </g>
    </Board>
  );
}

/* Made up — rosie-plum/made-up */
export function RosiePlumMadeUp(props) {
  return (
    <Board {...props}>
      <g className="an-cheer">
        <path d="M38 97.3 C23.9 83.9 13.1 73.1 13.1 64.1 C13.1 53.4 25.8 48.4 31.9 56.9 C34.7 60.5 36.6 62.3 38 63.7 C39.4 62.3 41.3 60.5 44.1 56.9 C50.2 48.4 62.9 53.4 62.9 64.1 C62.9 73.1 52.1 83.9 38 97.3 Z" fill="#E85D75" stroke="#3D2137" strokeWidth="4.2" strokeLinejoin="round" />
        <ellipse cx="38" cy="70.2" rx="15.2" ry="12.3" fill="#FFDFE6" />
        <path d="M26.1 68.8 q5.1 -7.1 10.1 0" stroke="#3D2137" strokeWidth="3.4" fill="none" strokeLinecap="round" />
        <path d="M39.7 68.8 q5.1 -7.1 10.1 0" stroke="#3D2137" strokeWidth="3.4" fill="none" strokeLinecap="round" />
        <path d="M31.9 75.1 q6.1 -2.6 12.2 0 q-1.2 7.6 -6.1 7.6 q-4.9 0 -6.1 -7.6Z" fill="#7A2E44" stroke="#3D2137" strokeWidth="3.2" strokeLinejoin="round" />
        <ellipse cx="26" cy="74.2" rx="4.1" ry="2.8" fill="#FF8FA6" opacity="0.85" />
        <ellipse cx="50" cy="74.2" rx="4.1" ry="2.8" fill="#FF8FA6" opacity="0.85" />
      </g>
      <g className="an-cheer an-d2">
        <path d="M84 93.9 C70.2 80.7 59.6 70.1 59.6 61.3 C59.6 50.8 72 45.9 78 54.3 C80.8 57.8 82.6 59.6 84 60.9 C85.4 59.6 87.2 57.8 90 54.3 C96 45.9 108.4 50.8 108.4 61.3 C108.4 70.1 97.8 80.7 84 93.9 Z" fill="#6B3A5F" stroke="#3D2137" strokeWidth="4.2" strokeLinejoin="round" />
        <ellipse cx="84" cy="67.3" rx="15" ry="12.1" fill="#F0DDEB" />
        <path d="M72.4 65.9 q5 -7 9.9 0" stroke="#3D2137" strokeWidth="3.4" fill="none" strokeLinecap="round" />
        <path d="M85.7 65.9 q5 -7 9.9 0" stroke="#3D2137" strokeWidth="3.4" fill="none" strokeLinecap="round" />
        <path d="M78 72.1 q6 -2.6 12 0 q-1.2 7.5 -6 7.5 q-4.8 0 -6 -7.5Z" fill="#7A2E44" stroke="#3D2137" strokeWidth="3.2" strokeLinejoin="round" />
        <ellipse cx="72.3" cy="71.2" rx="4" ry="2.7" fill="#D98CBE" opacity="0.85" />
        <ellipse cx="95.7" cy="71.2" rx="4" ry="2.7" fill="#D98CBE" opacity="0.85" />
      </g>
      <path d="M52 88 C60 92 68 92 76 88" stroke="#3D2137" strokeWidth="14.6" strokeLinecap="round" fill="none" />
      <path d="M52 88 C60 92 68 92 76 88" stroke="#F1798D" strokeWidth="7.2" strokeLinecap="round" fill="none" />
      <g className="an-bob">
        <path d="M60 21.2 C56.7 18.2 54.2 15.8 54.2 13.8 C54.2 11.4 57.1 10.3 58.6 12.2 C59.2 13 59.7 13.4 60 13.7 C60.3 13.4 60.8 13 61.4 12.2 C62.9 10.3 65.8 11.4 65.8 13.8 C65.8 15.8 63.3 18.2 60 21.2 Z" fill="#E85D75" stroke="#3D2137" strokeWidth="3.2" strokeLinejoin="round" />
      </g>
      <g className="an-bob an-d2">
        <path d="M22 33 C20.1 31.3 18.6 29.9 18.6 28.7 C18.6 27.3 20.3 26.7 21.2 27.8 C21.6 28.3 21.8 28.5 22 28.7 C22.2 28.5 22.4 28.3 22.8 27.8 C23.7 26.7 25.4 27.3 25.4 28.7 C25.4 29.9 23.9 31.3 22 33 Z" fill="#E85D75" stroke="#3D2137" strokeWidth="3.2" strokeLinejoin="round" />
      </g>
      <g className="an-twinkle">
        <path d="M8 56.4 q0.6 2.2 3.6 3.6 q-2.2 0.6 -3.6 3.6 q-0.6 -2.2 -3.6 -3.6 q2.2 -0.6 3.6 -3.6Z" fill="#F2B880" opacity="1" />
      </g>
      <g className="an-twinkle an-d2">
        <path d="M112 36.6 q0.6 2.1 3.4 3.4 q-2.1 0.6 -3.4 3.4 q-0.6 -2.1 -3.4 -3.4 q2.1 -0.6 3.4 -3.4Z" fill="#F2B880" opacity="1" />
      </g>
    </Board>
  );
}

/* id -> component, ready for the registry in ./index.jsx */
export const COMPONENTS = {
  'rosie-plum/begging': RosiePlumBegging,
  'rosie-plum/waterfall-cry': RosiePlumWaterfallCry,
  'rosie-plum/big-hug': RosiePlumBigHug,
  'rosie-plum/flowers-shy': RosiePlumFlowersShy,
  'rosie-plum/pouty': RosiePlumPouty,
  'rosie-plum/cheek-kiss': RosiePlumCheekKiss,
  'rosie-plum/head-pat': RosiePlumHeadPat,
  'rosie-plum/forgive-sign': RosiePlumForgiveSign,
  'rosie-plum/sulk-rain': RosiePlumSulkRain,
  'rosie-plum/made-up': RosiePlumMadeUp,
};

export default COMPONENTS;
